(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite2 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite3 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite4 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite5 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite6 - satellite
	instrument47 - instrument
	instrument48 - instrument
	satellite7 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	satellite8 - satellite
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	satellite9 - satellite
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	instrument68 - instrument
	instrument69 - instrument
	image3 - mode
	image2 - mode
	infrared1 - mode
	spectrograph0 - mode
	image4 - mode
	GroundStation2 - direction
	GroundStation10 - direction
	Star14 - direction
	Star12 - direction
	Star15 - direction
	Star13 - direction
	GroundStation1 - direction
	Star5 - direction
	Star3 - direction
	GroundStation16 - direction
	Star7 - direction
	Star6 - direction
	Star0 - direction
	GroundStation9 - direction
	GroundStation11 - direction
	GroundStation4 - direction
	Star8 - direction
	Star17 - direction
	Phenomenon18 - direction
)
(:init
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 Star14)
	(supports instrument1 image2)
	(supports instrument1 image4)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 GroundStation16)
	(supports instrument2 image4)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star15)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 Star13)
	(calibration_target instrument2 GroundStation16)
	(supports instrument3 image3)
	(supports instrument3 image4)
	(calibration_target instrument3 Star5)
	(supports instrument4 image3)
	(calibration_target instrument4 Star7)
	(supports instrument5 spectrograph0)
	(supports instrument5 infrared1)
	(supports instrument5 image3)
	(calibration_target instrument5 GroundStation9)
	(calibration_target instrument5 Star14)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 Star15)
	(supports instrument6 spectrograph0)
	(supports instrument6 image4)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 GroundStation11)
	(calibration_target instrument6 GroundStation16)
	(supports instrument7 image2)
	(supports instrument7 infrared1)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star5)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 GroundStation10)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star5)
	(supports instrument8 infrared1)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 GroundStation16)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 Star0)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation16)
	(calibration_target instrument9 Star7)
	(supports instrument10 infrared1)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 Star8)
	(supports instrument11 image3)
	(supports instrument11 image4)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation9)
	(calibration_target instrument11 Star13)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star8)
	(supports instrument12 spectrograph0)
	(supports instrument12 image3)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star14)
	(supports instrument13 image2)
	(supports instrument13 spectrograph0)
	(supports instrument13 image4)
	(calibration_target instrument13 Star13)
	(calibration_target instrument13 Star14)
	(supports instrument14 image2)
	(supports instrument14 infrared1)
	(supports instrument14 image3)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 Star13)
	(calibration_target instrument14 Star12)
	(supports instrument15 image3)
	(supports instrument15 infrared1)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 Star14)
	(supports instrument16 image2)
	(supports instrument16 image3)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star14)
	(calibration_target instrument16 Star5)
	(supports instrument17 spectrograph0)
	(supports instrument17 infrared1)
	(supports instrument17 image3)
	(calibration_target instrument17 GroundStation11)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star13)
	(supports instrument18 image2)
	(calibration_target instrument18 Star5)
	(supports instrument19 image4)
	(calibration_target instrument19 Star15)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 Star14)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 Star12)
	(supports instrument20 image4)
	(calibration_target instrument20 GroundStation10)
	(supports instrument21 spectrograph0)
	(supports instrument21 image3)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 Star14)
	(calibration_target instrument21 Star7)
	(calibration_target instrument21 Star3)
	(supports instrument22 image2)
	(supports instrument22 image3)
	(calibration_target instrument22 Star7)
	(supports instrument23 infrared1)
	(supports instrument23 image2)
	(supports instrument23 image4)
	(calibration_target instrument23 GroundStation10)
	(calibration_target instrument23 GroundStation9)
	(calibration_target instrument23 GroundStation1)
	(calibration_target instrument23 GroundStation2)
	(calibration_target instrument23 Star12)
	(supports instrument24 spectrograph0)
	(supports instrument24 image4)
	(supports instrument24 image3)
	(calibration_target instrument24 Star13)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 GroundStation10)
	(supports instrument25 spectrograph0)
	(calibration_target instrument25 Star13)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 Star3)
	(supports instrument26 image4)
	(calibration_target instrument26 Star5)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 Star12)
	(calibration_target instrument26 Star13)
	(calibration_target instrument26 Star14)
	(supports instrument27 image4)
	(calibration_target instrument27 GroundStation2)
	(calibration_target instrument27 GroundStation16)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 GroundStation9)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(on_board instrument24 satellite2)
	(on_board instrument25 satellite2)
	(on_board instrument26 satellite2)
	(on_board instrument27 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star5)
	(supports instrument28 image2)
	(calibration_target instrument28 Star7)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 GroundStation11)
	(supports instrument29 infrared1)
	(calibration_target instrument29 Star8)
	(supports instrument30 infrared1)
	(supports instrument30 image2)
	(supports instrument30 image4)
	(calibration_target instrument30 GroundStation10)
	(calibration_target instrument30 Star14)
	(calibration_target instrument30 Star5)
	(supports instrument31 infrared1)
	(supports instrument31 image2)
	(calibration_target instrument31 GroundStation1)
	(calibration_target instrument31 GroundStation16)
	(supports instrument32 image2)
	(calibration_target instrument32 GroundStation4)
	(supports instrument33 spectrograph0)
	(supports instrument33 image3)
	(calibration_target instrument33 GroundStation9)
	(calibration_target instrument33 Star7)
	(calibration_target instrument33 GroundStation4)
	(supports instrument34 image4)
	(calibration_target instrument34 GroundStation11)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(on_board instrument32 satellite3)
	(on_board instrument33 satellite3)
	(on_board instrument34 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star13)
	(supports instrument35 image4)
	(calibration_target instrument35 Star0)
	(supports instrument36 image3)
	(supports instrument36 infrared1)
	(supports instrument36 image4)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 Star15)
	(calibration_target instrument36 Star5)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 image2)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 Star6)
	(supports instrument38 spectrograph0)
	(calibration_target instrument38 Star13)
	(calibration_target instrument38 GroundStation10)
	(calibration_target instrument38 Star0)
	(calibration_target instrument38 Star8)
	(supports instrument39 image4)
	(supports instrument39 spectrograph0)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 GroundStation9)
	(calibration_target instrument39 Star6)
	(calibration_target instrument39 Star8)
	(calibration_target instrument39 GroundStation2)
	(supports instrument40 spectrograph0)
	(supports instrument40 image4)
	(supports instrument40 image2)
	(calibration_target instrument40 Star12)
	(supports instrument41 image4)
	(calibration_target instrument41 GroundStation1)
	(calibration_target instrument41 Star5)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(on_board instrument38 satellite4)
	(on_board instrument39 satellite4)
	(on_board instrument40 satellite4)
	(on_board instrument41 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation9)
	(supports instrument42 image3)
	(supports instrument42 infrared1)
	(calibration_target instrument42 GroundStation1)
	(calibration_target instrument42 Star13)
	(calibration_target instrument42 GroundStation4)
	(supports instrument43 infrared1)
	(supports instrument43 image2)
	(calibration_target instrument43 Star5)
	(calibration_target instrument43 Star7)
	(calibration_target instrument43 Star3)
	(supports instrument44 image4)
	(supports instrument44 image3)
	(calibration_target instrument44 GroundStation16)
	(calibration_target instrument44 Star7)
	(calibration_target instrument44 Star12)
	(supports instrument45 spectrograph0)
	(calibration_target instrument45 Star14)
	(calibration_target instrument45 GroundStation9)
	(calibration_target instrument45 Star7)
	(calibration_target instrument45 Star13)
	(calibration_target instrument45 Star3)
	(supports instrument46 image4)
	(calibration_target instrument46 Star8)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(on_board instrument44 satellite5)
	(on_board instrument45 satellite5)
	(on_board instrument46 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star13)
	(supports instrument47 spectrograph0)
	(supports instrument47 image4)
	(calibration_target instrument47 Star15)
	(supports instrument48 image2)
	(calibration_target instrument48 GroundStation2)
	(calibration_target instrument48 Star13)
	(calibration_target instrument48 GroundStation1)
	(on_board instrument47 satellite6)
	(on_board instrument48 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
	(supports instrument49 image3)
	(calibration_target instrument49 GroundStation4)
	(supports instrument50 image2)
	(supports instrument50 image4)
	(supports instrument50 image3)
	(calibration_target instrument50 GroundStation10)
	(calibration_target instrument50 Star13)
	(supports instrument51 image3)
	(calibration_target instrument51 GroundStation1)
	(calibration_target instrument51 Star15)
	(supports instrument52 spectrograph0)
	(supports instrument52 infrared1)
	(calibration_target instrument52 GroundStation10)
	(calibration_target instrument52 Star12)
	(calibration_target instrument52 Star8)
	(calibration_target instrument52 GroundStation9)
	(calibration_target instrument52 Star6)
	(supports instrument53 infrared1)
	(calibration_target instrument53 Star6)
	(calibration_target instrument53 Star13)
	(calibration_target instrument53 Star12)
	(calibration_target instrument53 GroundStation9)
	(supports instrument54 image3)
	(supports instrument54 spectrograph0)
	(supports instrument54 image2)
	(calibration_target instrument54 GroundStation1)
	(calibration_target instrument54 Star0)
	(supports instrument55 spectrograph0)
	(calibration_target instrument55 GroundStation9)
	(supports instrument56 infrared1)
	(calibration_target instrument56 Star13)
	(calibration_target instrument56 Star5)
	(calibration_target instrument56 GroundStation10)
	(calibration_target instrument56 GroundStation9)
	(supports instrument57 image3)
	(calibration_target instrument57 Star15)
	(calibration_target instrument57 Star6)
	(calibration_target instrument57 Star8)
	(calibration_target instrument57 Star14)
	(supports instrument58 image3)
	(supports instrument58 image4)
	(calibration_target instrument58 Star15)
	(calibration_target instrument58 Star13)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(on_board instrument55 satellite7)
	(on_board instrument56 satellite7)
	(on_board instrument57 satellite7)
	(on_board instrument58 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star3)
	(supports instrument59 image4)
	(supports instrument59 infrared1)
	(calibration_target instrument59 GroundStation16)
	(supports instrument60 image4)
	(supports instrument60 spectrograph0)
	(calibration_target instrument60 Star12)
	(calibration_target instrument60 Star5)
	(supports instrument61 spectrograph0)
	(supports instrument61 image4)
	(calibration_target instrument61 Star15)
	(calibration_target instrument61 Star0)
	(calibration_target instrument61 GroundStation9)
	(supports instrument62 image3)
	(supports instrument62 image2)
	(calibration_target instrument62 Star5)
	(calibration_target instrument62 Star7)
	(supports instrument63 spectrograph0)
	(supports instrument63 infrared1)
	(supports instrument63 image3)
	(calibration_target instrument63 Star0)
	(calibration_target instrument63 Star15)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(on_board instrument61 satellite8)
	(on_board instrument62 satellite8)
	(on_board instrument63 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
	(supports instrument64 infrared1)
	(calibration_target instrument64 GroundStation16)
	(calibration_target instrument64 GroundStation1)
	(calibration_target instrument64 Star13)
	(calibration_target instrument64 Star7)
	(calibration_target instrument64 Star15)
	(supports instrument65 spectrograph0)
	(calibration_target instrument65 Star5)
	(calibration_target instrument65 GroundStation16)
	(calibration_target instrument65 Star7)
	(calibration_target instrument65 GroundStation1)
	(calibration_target instrument65 Star0)
	(supports instrument66 image2)
	(calibration_target instrument66 Star5)
	(calibration_target instrument66 GroundStation1)
	(calibration_target instrument66 GroundStation9)
	(supports instrument67 image3)
	(supports instrument67 image2)
	(supports instrument67 spectrograph0)
	(calibration_target instrument67 GroundStation16)
	(calibration_target instrument67 Star3)
	(supports instrument68 image2)
	(calibration_target instrument68 GroundStation9)
	(calibration_target instrument68 Star0)
	(calibration_target instrument68 Star6)
	(calibration_target instrument68 Star7)
	(supports instrument69 image4)
	(supports instrument69 spectrograph0)
	(supports instrument69 infrared1)
	(calibration_target instrument69 Star8)
	(calibration_target instrument69 GroundStation4)
	(calibration_target instrument69 GroundStation11)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(on_board instrument68 satellite9)
	(on_board instrument69 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite8 Phenomenon18)
	(have_image Star17 image2)
	(have_image Phenomenon18 image3)
))

)
