(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite6 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite7 - satellite
	instrument26 - instrument
	instrument27 - instrument
	satellite8 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite9 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	thermograph0 - mode
	image1 - mode
	thermograph4 - mode
	thermograph3 - mode
	thermograph2 - mode
	GroundStation15 - direction
	GroundStation5 - direction
	GroundStation16 - direction
	GroundStation10 - direction
	Star1 - direction
	GroundStation13 - direction
	Star4 - direction
	Star8 - direction
	GroundStation11 - direction
	GroundStation6 - direction
	GroundStation12 - direction
	GroundStation7 - direction
	Star9 - direction
	Star0 - direction
	GroundStation2 - direction
	GroundStation14 - direction
	Star3 - direction
	Star17 - direction
	Star18 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 thermograph3)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation14)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star18)
	(supports instrument1 image1)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star4)
	(supports instrument2 thermograph4)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation12)
	(calibration_target instrument2 Star1)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation15)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 GroundStation2)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 Star3)
	(supports instrument5 image1)
	(supports instrument5 thermograph0)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 GroundStation15)
	(calibration_target instrument5 GroundStation12)
	(supports instrument6 thermograph4)
	(supports instrument6 thermograph3)
	(calibration_target instrument6 GroundStation15)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 GroundStation11)
	(calibration_target instrument6 GroundStation7)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument7 thermograph2)
	(supports instrument7 image1)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 GroundStation16)
	(calibration_target instrument7 GroundStation14)
	(supports instrument8 image1)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star0)
	(supports instrument9 thermograph4)
	(supports instrument9 image1)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 GroundStation14)
	(supports instrument10 image1)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star8)
	(calibration_target instrument10 Star9)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 GroundStation6)
	(supports instrument11 thermograph4)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 GroundStation14)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation15)
	(calibration_target instrument11 GroundStation10)
	(supports instrument12 image1)
	(calibration_target instrument12 GroundStation13)
	(calibration_target instrument12 GroundStation15)
	(calibration_target instrument12 Star1)
	(supports instrument13 thermograph3)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 Star3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation12)
	(supports instrument14 image1)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 GroundStation13)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star9)
	(supports instrument15 thermograph2)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 GroundStation6)
	(calibration_target instrument15 GroundStation13)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 GroundStation5)
	(supports instrument16 thermograph0)
	(supports instrument16 image1)
	(supports instrument16 thermograph3)
	(calibration_target instrument16 GroundStation15)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation14)
	(supports instrument17 image1)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 GroundStation10)
	(calibration_target instrument17 GroundStation11)
	(calibration_target instrument17 GroundStation13)
	(calibration_target instrument17 Star4)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 GroundStation12)
	(calibration_target instrument18 GroundStation10)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument19 thermograph2)
	(supports instrument19 thermograph0)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation10)
	(calibration_target instrument19 Star4)
	(supports instrument20 thermograph3)
	(supports instrument20 thermograph2)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 Star9)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 Star1)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 Star3)
	(supports instrument22 thermograph2)
	(supports instrument22 thermograph3)
	(calibration_target instrument22 GroundStation12)
	(supports instrument23 thermograph4)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 GroundStation14)
	(calibration_target instrument23 Star3)
	(supports instrument24 thermograph2)
	(calibration_target instrument24 Star9)
	(calibration_target instrument24 GroundStation15)
	(calibration_target instrument24 GroundStation14)
	(calibration_target instrument24 GroundStation16)
	(calibration_target instrument24 GroundStation2)
	(supports instrument25 thermograph3)
	(supports instrument25 image1)
	(calibration_target instrument25 GroundStation16)
	(calibration_target instrument25 Star3)
	(calibration_target instrument25 GroundStation12)
	(calibration_target instrument25 GroundStation15)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation10)
	(supports instrument26 thermograph0)
	(supports instrument26 thermograph3)
	(calibration_target instrument26 GroundStation7)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 GroundStation5)
	(calibration_target instrument26 GroundStation13)
	(calibration_target instrument26 GroundStation2)
	(supports instrument27 image1)
	(supports instrument27 thermograph3)
	(calibration_target instrument27 GroundStation10)
	(calibration_target instrument27 GroundStation16)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation2)
	(supports instrument28 thermograph0)
	(supports instrument28 thermograph2)
	(calibration_target instrument28 Star4)
	(calibration_target instrument28 GroundStation11)
	(calibration_target instrument28 Star3)
	(calibration_target instrument28 Star1)
	(supports instrument29 thermograph3)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 Star9)
	(calibration_target instrument29 GroundStation14)
	(supports instrument30 thermograph0)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 GroundStation11)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 GroundStation13)
	(calibration_target instrument30 Star8)
	(calibration_target instrument30 GroundStation6)
	(supports instrument31 thermograph2)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 Star4)
	(supports instrument32 image1)
	(calibration_target instrument32 Star8)
	(calibration_target instrument32 Star9)
	(supports instrument33 thermograph3)
	(supports instrument33 thermograph4)
	(supports instrument33 image1)
	(calibration_target instrument33 Star0)
	(calibration_target instrument33 GroundStation6)
	(calibration_target instrument33 GroundStation11)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 thermograph2)
	(calibration_target instrument34 GroundStation2)
	(calibration_target instrument34 GroundStation12)
	(on_board instrument28 satellite8)
	(on_board instrument29 satellite8)
	(on_board instrument30 satellite8)
	(on_board instrument31 satellite8)
	(on_board instrument32 satellite8)
	(on_board instrument33 satellite8)
	(on_board instrument34 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star17)
	(supports instrument35 thermograph4)
	(supports instrument35 image1)
	(supports instrument35 thermograph3)
	(calibration_target instrument35 Star9)
	(calibration_target instrument35 GroundStation7)
	(supports instrument36 image1)
	(calibration_target instrument36 GroundStation2)
	(supports instrument37 thermograph4)
	(calibration_target instrument37 GroundStation14)
	(calibration_target instrument37 GroundStation2)
	(calibration_target instrument37 Star0)
	(supports instrument38 thermograph2)
	(supports instrument38 thermograph3)
	(calibration_target instrument38 Star3)
	(on_board instrument35 satellite9)
	(on_board instrument36 satellite9)
	(on_board instrument37 satellite9)
	(on_board instrument38 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation12)
)
(:goal (and
	(pointing satellite3 GroundStation10)
	(pointing satellite7 Star8)
	(have_image Star18 image1)
))

)
