(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite2 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite4 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite5 - satellite
	instrument38 - instrument
	instrument39 - instrument
	satellite6 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite7 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite9 - satellite
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	thermograph3 - mode
	image1 - mode
	thermograph0 - mode
	thermograph4 - mode
	thermograph2 - mode
	Star0 - direction
	GroundStation6 - direction
	GroundStation7 - direction
	Star9 - direction
	Star3 - direction
	Star1 - direction
	GroundStation10 - direction
	GroundStation5 - direction
	Star8 - direction
	GroundStation2 - direction
	Star4 - direction
	Phenomenon11 - direction
	Phenomenon12 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph3)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation10)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 thermograph0)
	(supports instrument1 thermograph3)
	(supports instrument1 image1)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 GroundStation6)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 GroundStation10)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 GroundStation6)
	(supports instrument4 thermograph0)
	(supports instrument4 thermograph4)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 thermograph3)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 Star3)
	(supports instrument6 thermograph4)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 Star4)
	(supports instrument7 thermograph2)
	(supports instrument7 thermograph0)
	(supports instrument7 image1)
	(calibration_target instrument7 Star8)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 GroundStation2)
	(supports instrument8 thermograph0)
	(supports instrument8 thermograph3)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star4)
	(calibration_target instrument8 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument9 image1)
	(calibration_target instrument9 Star4)
	(calibration_target instrument9 Star3)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 Star8)
	(calibration_target instrument10 Star4)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation6)
	(calibration_target instrument11 Star8)
	(supports instrument12 thermograph3)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 Star8)
	(supports instrument13 thermograph3)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation7)
	(supports instrument14 thermograph4)
	(supports instrument14 thermograph0)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation10)
	(calibration_target instrument14 Star1)
	(supports instrument15 thermograph3)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 GroundStation10)
	(calibration_target instrument15 Star1)
	(supports instrument16 thermograph4)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 Star0)
	(supports instrument17 thermograph0)
	(supports instrument17 thermograph3)
	(calibration_target instrument17 GroundStation2)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument18 thermograph3)
	(supports instrument18 thermograph4)
	(supports instrument18 image1)
	(calibration_target instrument18 GroundStation7)
	(calibration_target instrument18 Star0)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 GroundStation6)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon12)
	(supports instrument20 thermograph2)
	(supports instrument20 image1)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 GroundStation6)
	(supports instrument21 image1)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 Star4)
	(supports instrument22 thermograph0)
	(supports instrument22 thermograph2)
	(calibration_target instrument22 GroundStation6)
	(calibration_target instrument22 GroundStation10)
	(supports instrument23 image1)
	(supports instrument23 thermograph3)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 Star4)
	(calibration_target instrument23 Star3)
	(supports instrument24 thermograph4)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 Star9)
	(calibration_target instrument24 Star0)
	(supports instrument25 thermograph2)
	(supports instrument25 thermograph4)
	(supports instrument25 thermograph3)
	(calibration_target instrument25 GroundStation7)
	(supports instrument26 thermograph2)
	(supports instrument26 image1)
	(calibration_target instrument26 GroundStation5)
	(supports instrument27 image1)
	(calibration_target instrument27 Star9)
	(calibration_target instrument27 GroundStation10)
	(calibration_target instrument27 Star3)
	(supports instrument28 thermograph4)
	(supports instrument28 thermograph0)
	(calibration_target instrument28 Star1)
	(calibration_target instrument28 Star0)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star9)
	(supports instrument29 thermograph2)
	(supports instrument29 thermograph0)
	(supports instrument29 thermograph3)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 Star3)
	(supports instrument30 thermograph4)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 Star9)
	(calibration_target instrument30 GroundStation6)
	(calibration_target instrument30 GroundStation2)
	(supports instrument31 thermograph0)
	(supports instrument31 thermograph2)
	(calibration_target instrument31 Star4)
	(supports instrument32 thermograph2)
	(calibration_target instrument32 GroundStation7)
	(calibration_target instrument32 Star1)
	(calibration_target instrument32 GroundStation6)
	(supports instrument33 image1)
	(supports instrument33 thermograph3)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 Star4)
	(calibration_target instrument33 GroundStation7)
	(calibration_target instrument33 GroundStation5)
	(supports instrument34 thermograph3)
	(supports instrument34 image1)
	(calibration_target instrument34 Star4)
	(supports instrument35 thermograph0)
	(supports instrument35 image1)
	(supports instrument35 thermograph3)
	(calibration_target instrument35 GroundStation5)
	(calibration_target instrument35 Star9)
	(calibration_target instrument35 GroundStation6)
	(supports instrument36 thermograph3)
	(supports instrument36 image1)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 GroundStation6)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 GroundStation7)
	(supports instrument37 thermograph3)
	(supports instrument37 thermograph0)
	(supports instrument37 thermograph2)
	(calibration_target instrument37 Star9)
	(calibration_target instrument37 GroundStation5)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star4)
	(supports instrument38 thermograph2)
	(supports instrument38 thermograph4)
	(calibration_target instrument38 Star1)
	(calibration_target instrument38 Star3)
	(calibration_target instrument38 Star4)
	(supports instrument39 image1)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 GroundStation6)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star8)
	(supports instrument40 image1)
	(supports instrument40 thermograph2)
	(calibration_target instrument40 GroundStation7)
	(calibration_target instrument40 GroundStation6)
	(supports instrument41 thermograph2)
	(supports instrument41 thermograph3)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 Star9)
	(supports instrument42 thermograph2)
	(supports instrument42 thermograph3)
	(calibration_target instrument42 Star3)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon11)
	(supports instrument43 thermograph4)
	(supports instrument43 thermograph3)
	(calibration_target instrument43 Star1)
	(supports instrument44 thermograph4)
	(supports instrument44 thermograph0)
	(calibration_target instrument44 Star3)
	(calibration_target instrument44 GroundStation10)
	(supports instrument45 thermograph3)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 Star8)
	(calibration_target instrument45 GroundStation7)
	(supports instrument46 thermograph2)
	(calibration_target instrument46 Star8)
	(supports instrument47 thermograph2)
	(supports instrument47 thermograph3)
	(supports instrument47 image1)
	(calibration_target instrument47 Star9)
	(calibration_target instrument47 Star3)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star9)
	(supports instrument48 thermograph2)
	(calibration_target instrument48 Star3)
	(supports instrument49 thermograph2)
	(supports instrument49 thermograph4)
	(supports instrument49 thermograph0)
	(calibration_target instrument49 GroundStation5)
	(supports instrument50 image1)
	(calibration_target instrument50 GroundStation5)
	(supports instrument51 thermograph3)
	(calibration_target instrument51 Star8)
	(calibration_target instrument51 GroundStation5)
	(supports instrument52 thermograph4)
	(calibration_target instrument52 Star1)
	(calibration_target instrument52 Star4)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star4)
	(supports instrument53 thermograph0)
	(supports instrument53 thermograph3)
	(supports instrument53 thermograph2)
	(calibration_target instrument53 GroundStation5)
	(calibration_target instrument53 GroundStation10)
	(supports instrument54 image1)
	(supports instrument54 thermograph0)
	(calibration_target instrument54 Star4)
	(calibration_target instrument54 Star8)
	(calibration_target instrument54 GroundStation5)
	(supports instrument55 thermograph4)
	(supports instrument55 thermograph0)
	(supports instrument55 thermograph2)
	(calibration_target instrument55 GroundStation2)
	(supports instrument56 thermograph2)
	(calibration_target instrument56 Star4)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation6)
)
(:goal (and
	(pointing satellite0 GroundStation6)
	(pointing satellite3 Star0)
	(have_image Phenomenon12 thermograph4)
))
)
