(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	satellite6 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite7 - satellite
	instrument27 - instrument
	instrument28 - instrument
	satellite8 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite9 - satellite
	instrument33 - instrument
	instrument34 - instrument
	image3 - mode
	spectrograph2 - mode
	thermograph4 - mode
	image0 - mode
	spectrograph1 - mode
	Star11 - direction
	GroundStation10 - direction
	Star12 - direction
	GroundStation13 - direction
	Star1 - direction
	GroundStation18 - direction
	Star14 - direction
	GroundStation15 - direction
	GroundStation0 - direction
	Star9 - direction
	Star19 - direction
	GroundStation6 - direction
	GroundStation3 - direction
	GroundStation16 - direction
	Star5 - direction
	Star17 - direction
	GroundStation2 - direction
	GroundStation8 - direction
	GroundStation4 - direction
	Star7 - direction
	Phenomenon20 - direction
	Star21 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 spectrograph2)
	(supports instrument0 image0)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation0)
	(calibration_target instrument0 GroundStation15)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 spectrograph2)
	(supports instrument1 thermograph4)
	(supports instrument1 image0)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 image3)
	(supports instrument2 image0)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 GroundStation0)
	(calibration_target instrument2 Star17)
	(calibration_target instrument2 GroundStation10)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation0)
	(supports instrument3 image3)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 Star11)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation16)
	(supports instrument4 image3)
	(calibration_target instrument4 Star19)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 GroundStation10)
	(supports instrument5 image3)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation15)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 GroundStation3)
	(calibration_target instrument5 GroundStation13)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 Star19)
	(supports instrument6 image3)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation13)
	(calibration_target instrument6 GroundStation16)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 Star7)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument7 thermograph4)
	(supports instrument7 image0)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 image0)
	(supports instrument8 image3)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star19)
	(calibration_target instrument8 GroundStation8)
	(supports instrument9 spectrograph2)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation16)
	(calibration_target instrument9 Star14)
	(supports instrument10 thermograph4)
	(supports instrument10 image3)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 GroundStation13)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation6)
	(supports instrument11 image3)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 GroundStation6)
	(calibration_target instrument11 Star11)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 Star14)
	(supports instrument12 spectrograph1)
	(supports instrument12 image3)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation10)
	(calibration_target instrument12 GroundStation13)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 GroundStation13)
	(calibration_target instrument13 GroundStation8)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation15)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 Star17)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 GroundStation3)
	(supports instrument15 image3)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 Star11)
	(calibration_target instrument15 Star7)
	(supports instrument16 image0)
	(calibration_target instrument16 Star11)
	(calibration_target instrument16 GroundStation6)
	(calibration_target instrument16 Star19)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 Star17)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 Star12)
	(calibration_target instrument17 Star11)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 Star17)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 Star11)
	(supports instrument19 spectrograph1)
	(supports instrument19 image0)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star17)
	(supports instrument20 image0)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 Star19)
	(calibration_target instrument20 GroundStation3)
	(calibration_target instrument20 GroundStation10)
	(supports instrument21 image0)
	(supports instrument21 spectrograph1)
	(supports instrument21 spectrograph2)
	(calibration_target instrument21 GroundStation18)
	(calibration_target instrument21 GroundStation15)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 Star11)
	(calibration_target instrument21 GroundStation0)
	(supports instrument22 thermograph4)
	(supports instrument22 image0)
	(calibration_target instrument22 Star12)
	(calibration_target instrument22 Star7)
	(calibration_target instrument22 GroundStation13)
	(calibration_target instrument22 Star1)
	(calibration_target instrument22 Star14)
	(supports instrument23 spectrograph2)
	(supports instrument23 image0)
	(supports instrument23 spectrograph1)
	(calibration_target instrument23 GroundStation16)
	(calibration_target instrument23 GroundStation10)
	(supports instrument24 spectrograph2)
	(supports instrument24 spectrograph1)
	(calibration_target instrument24 Star7)
	(calibration_target instrument24 Star19)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 GroundStation13)
	(calibration_target instrument25 Star12)
	(supports instrument26 spectrograph1)
	(supports instrument26 image0)
	(calibration_target instrument26 GroundStation15)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 Star1)
	(calibration_target instrument26 GroundStation6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation8)
	(supports instrument27 thermograph4)
	(supports instrument27 spectrograph1)
	(supports instrument27 image0)
	(calibration_target instrument27 GroundStation0)
	(calibration_target instrument27 Star14)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 GroundStation2)
	(calibration_target instrument27 Star9)
	(calibration_target instrument27 GroundStation18)
	(supports instrument28 image0)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 GroundStation15)
	(calibration_target instrument28 GroundStation2)
	(calibration_target instrument28 Star17)
	(on_board instrument27 satellite7)
	(on_board instrument28 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star12)
	(supports instrument29 thermograph4)
	(supports instrument29 spectrograph1)
	(calibration_target instrument29 GroundStation0)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 image0)
	(supports instrument30 thermograph4)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 GroundStation16)
	(calibration_target instrument30 GroundStation3)
	(calibration_target instrument30 GroundStation6)
	(calibration_target instrument30 Star19)
	(calibration_target instrument30 Star9)
	(supports instrument31 spectrograph2)
	(supports instrument31 image0)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 Star5)
	(supports instrument32 thermograph4)
	(supports instrument32 spectrograph2)
	(calibration_target instrument32 GroundStation2)
	(calibration_target instrument32 Star17)
	(on_board instrument29 satellite8)
	(on_board instrument30 satellite8)
	(on_board instrument31 satellite8)
	(on_board instrument32 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
	(supports instrument33 thermograph4)
	(supports instrument33 spectrograph1)
	(calibration_target instrument33 GroundStation8)
	(supports instrument34 spectrograph1)
	(supports instrument34 image0)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 Star7)
	(calibration_target instrument34 GroundStation4)
	(on_board instrument33 satellite9)
	(on_board instrument34 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation13)
)
(:goal (and
	(pointing satellite1 GroundStation2)
	(pointing satellite3 GroundStation0)
	(pointing satellite5 Star7)
	(pointing satellite7 Star11)
	(have_image Phenomenon20 image0)
	(have_image Star21 spectrograph2)
))

)
