(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite6 - satellite
	instrument25 - instrument
	instrument26 - instrument
	satellite7 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite8 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite9 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	infrared1 - mode
	image0 - mode
	infrared3 - mode
	infrared4 - mode
	thermograph2 - mode
	GroundStation7 - direction
	Star0 - direction
	Star10 - direction
	GroundStation6 - direction
	GroundStation4 - direction
	Star16 - direction
	Star13 - direction
	Star8 - direction
	Star2 - direction
	GroundStation17 - direction
	Star1 - direction
	GroundStation18 - direction
	GroundStation11 - direction
	GroundStation5 - direction
	Star19 - direction
	Star14 - direction
	Star3 - direction
	GroundStation15 - direction
	Star9 - direction
	Star12 - direction
	Star20 - direction
	Planet21 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation15)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star13)
	(supports instrument1 thermograph2)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star12)
	(supports instrument2 infrared1)
	(supports instrument2 infrared4)
	(supports instrument2 image0)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 GroundStation17)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 Star3)
	(supports instrument3 infrared3)
	(supports instrument3 infrared1)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 image0)
	(supports instrument4 thermograph2)
	(supports instrument4 infrared1)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 Star3)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation11)
	(supports instrument5 infrared4)
	(supports instrument5 infrared3)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation6)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star13)
	(calibration_target instrument5 GroundStation15)
	(calibration_target instrument5 Star1)
	(supports instrument6 thermograph2)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation11)
	(supports instrument7 thermograph2)
	(supports instrument7 image0)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 Star16)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 Star1)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 GroundStation15)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star0)
	(supports instrument9 image0)
	(supports instrument9 infrared3)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star19)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation18)
	(supports instrument10 infrared3)
	(supports instrument10 infrared1)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 GroundStation17)
	(supports instrument11 thermograph2)
	(supports instrument11 infrared1)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 GroundStation11)
	(supports instrument12 infrared3)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 Star19)
	(calibration_target instrument12 GroundStation15)
	(calibration_target instrument12 GroundStation11)
	(calibration_target instrument12 Star9)
	(calibration_target instrument12 Star2)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation15)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star12)
	(supports instrument14 image0)
	(supports instrument14 infrared3)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 GroundStation15)
	(calibration_target instrument14 Star10)
	(supports instrument15 infrared3)
	(calibration_target instrument15 Star13)
	(calibration_target instrument15 Star12)
	(calibration_target instrument15 Star16)
	(calibration_target instrument15 Star14)
	(supports instrument16 infrared4)
	(calibration_target instrument16 Star14)
	(calibration_target instrument16 Star2)
	(calibration_target instrument16 Star10)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 Star8)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 GroundStation17)
	(supports instrument18 infrared3)
	(calibration_target instrument18 Star8)
	(supports instrument19 image0)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation17)
	(calibration_target instrument19 Star13)
	(calibration_target instrument19 Star2)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 GroundStation6)
	(supports instrument20 image0)
	(supports instrument20 infrared4)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 GroundStation6)
	(calibration_target instrument20 Star19)
	(calibration_target instrument20 Star13)
	(calibration_target instrument20 Star9)
	(supports instrument21 infrared3)
	(supports instrument21 thermograph2)
	(supports instrument21 infrared4)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 GroundStation11)
	(supports instrument22 image0)
	(supports instrument22 infrared4)
	(calibration_target instrument22 Star16)
	(calibration_target instrument22 Star8)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 Star1)
	(supports instrument23 image0)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 Star14)
	(calibration_target instrument23 GroundStation7)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 Star16)
	(calibration_target instrument23 Star13)
	(supports instrument24 infrared4)
	(calibration_target instrument24 Star14)
	(calibration_target instrument24 GroundStation11)
	(calibration_target instrument24 Star16)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star9)
	(supports instrument25 image0)
	(calibration_target instrument25 Star2)
	(supports instrument26 infrared1)
	(calibration_target instrument26 Star0)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation7)
	(supports instrument27 infrared3)
	(supports instrument27 infrared4)
	(supports instrument27 infrared1)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 Star12)
	(calibration_target instrument27 Star0)
	(supports instrument28 thermograph2)
	(supports instrument28 infrared3)
	(supports instrument28 infrared4)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 GroundStation18)
	(calibration_target instrument28 Star3)
	(calibration_target instrument28 GroundStation17)
	(calibration_target instrument28 Star10)
	(supports instrument29 image0)
	(supports instrument29 infrared3)
	(supports instrument29 infrared1)
	(calibration_target instrument29 GroundStation6)
	(calibration_target instrument29 GroundStation4)
	(calibration_target instrument29 GroundStation15)
	(calibration_target instrument29 Star9)
	(calibration_target instrument29 Star10)
	(supports instrument30 infrared4)
	(calibration_target instrument30 Star13)
	(supports instrument31 thermograph2)
	(supports instrument31 infrared4)
	(supports instrument31 image0)
	(calibration_target instrument31 Star13)
	(calibration_target instrument31 Star9)
	(supports instrument32 thermograph2)
	(supports instrument32 infrared4)
	(supports instrument32 image0)
	(calibration_target instrument32 GroundStation4)
	(calibration_target instrument32 Star12)
	(calibration_target instrument32 Star9)
	(supports instrument33 thermograph2)
	(supports instrument33 infrared3)
	(supports instrument33 image0)
	(calibration_target instrument33 Star2)
	(calibration_target instrument33 GroundStation6)
	(supports instrument34 infrared1)
	(supports instrument34 image0)
	(supports instrument34 infrared4)
	(calibration_target instrument34 Star8)
	(calibration_target instrument34 GroundStation17)
	(calibration_target instrument34 Star9)
	(calibration_target instrument34 GroundStation5)
	(calibration_target instrument34 Star16)
	(on_board instrument27 satellite7)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star8)
	(supports instrument35 thermograph2)
	(calibration_target instrument35 Star12)
	(calibration_target instrument35 GroundStation4)
	(calibration_target instrument35 GroundStation18)
	(calibration_target instrument35 Star3)
	(calibration_target instrument35 GroundStation17)
	(calibration_target instrument35 Star8)
	(supports instrument36 image0)
	(supports instrument36 infrared1)
	(supports instrument36 infrared3)
	(calibration_target instrument36 Star14)
	(supports instrument37 infrared1)
	(supports instrument37 image0)
	(calibration_target instrument37 Star2)
	(calibration_target instrument37 GroundStation6)
	(calibration_target instrument37 Star12)
	(calibration_target instrument37 Star14)
	(supports instrument38 infrared1)
	(supports instrument38 thermograph2)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation15)
	(calibration_target instrument38 GroundStation11)
	(calibration_target instrument38 GroundStation17)
	(calibration_target instrument38 Star3)
	(calibration_target instrument38 Star9)
	(supports instrument39 infrared1)
	(supports instrument39 image0)
	(supports instrument39 infrared4)
	(calibration_target instrument39 Star8)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 Star1)
	(calibration_target instrument39 GroundStation11)
	(supports instrument40 infrared1)
	(calibration_target instrument40 Star13)
	(calibration_target instrument40 GroundStation5)
	(calibration_target instrument40 Star16)
	(supports instrument41 thermograph2)
	(supports instrument41 infrared3)
	(calibration_target instrument41 GroundStation17)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 GroundStation11)
	(calibration_target instrument41 GroundStation18)
	(calibration_target instrument41 Star8)
	(calibration_target instrument41 Star12)
	(on_board instrument35 satellite8)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star14)
	(supports instrument42 infrared4)
	(supports instrument42 infrared1)
	(calibration_target instrument42 Star9)
	(calibration_target instrument42 Star1)
	(calibration_target instrument42 Star3)
	(calibration_target instrument42 GroundStation18)
	(calibration_target instrument42 Star19)
	(supports instrument43 thermograph2)
	(supports instrument43 image0)
	(calibration_target instrument43 Star19)
	(calibration_target instrument43 GroundStation5)
	(calibration_target instrument43 Star12)
	(calibration_target instrument43 GroundStation11)
	(calibration_target instrument43 Star14)
	(calibration_target instrument43 GroundStation18)
	(supports instrument44 thermograph2)
	(supports instrument44 infrared4)
	(supports instrument44 infrared3)
	(calibration_target instrument44 Star12)
	(calibration_target instrument44 Star9)
	(calibration_target instrument44 GroundStation15)
	(calibration_target instrument44 Star3)
	(calibration_target instrument44 Star14)
	(on_board instrument42 satellite9)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet21)
)
(:goal (and
	(pointing satellite2 Star13)
	(pointing satellite4 Star2)
	(pointing satellite5 Star20)
	(pointing satellite8 Star12)
	(have_image Star20 image0)
	(have_image Planet21 infrared4)
))

)
