(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite7 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite8 - satellite
	instrument44 - instrument
	satellite9 - satellite
	instrument45 - instrument
	spectrograph2 - mode
	image0 - mode
	image3 - mode
	spectrograph1 - mode
	thermograph4 - mode
	GroundStation20 - direction
	GroundStation13 - direction
	Star7 - direction
	GroundStation4 - direction
	Star14 - direction
	Star9 - direction
	GroundStation2 - direction
	Star1 - direction
	Star12 - direction
	Star22 - direction
	GroundStation8 - direction
	GroundStation15 - direction
	Star5 - direction
	Star17 - direction
	GroundStation3 - direction
	GroundStation16 - direction
	GroundStation10 - direction
	Star19 - direction
	GroundStation6 - direction
	GroundStation0 - direction
	Star11 - direction
	GroundStation18 - direction
	GroundStation21 - direction
	Phenomenon23 - direction
	Planet24 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 Star11)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 Star9)
	(supports instrument1 image0)
	(supports instrument1 thermograph4)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 GroundStation21)
	(calibration_target instrument1 GroundStation0)
	(calibration_target instrument1 Star22)
	(calibration_target instrument1 Star5)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 Star19)
	(supports instrument3 image0)
	(supports instrument3 spectrograph2)
	(supports instrument3 image3)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star9)
	(supports instrument4 image0)
	(calibration_target instrument4 Star14)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 GroundStation13)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation16)
	(calibration_target instrument5 GroundStation20)
	(calibration_target instrument5 GroundStation6)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star17)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 Star19)
	(calibration_target instrument6 Star11)
	(calibration_target instrument6 GroundStation15)
	(calibration_target instrument6 GroundStation20)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation10)
	(supports instrument7 image0)
	(supports instrument7 image3)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 GroundStation20)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation6)
	(supports instrument8 thermograph4)
	(supports instrument8 image3)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 GroundStation10)
	(supports instrument9 spectrograph2)
	(supports instrument9 image3)
	(supports instrument9 image0)
	(calibration_target instrument9 GroundStation4)
	(calibration_target instrument9 Star22)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 Star14)
	(calibration_target instrument9 Star19)
	(supports instrument10 spectrograph2)
	(supports instrument10 image0)
	(supports instrument10 image3)
	(calibration_target instrument10 GroundStation4)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 Star19)
	(supports instrument12 thermograph4)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 Star12)
	(supports instrument13 spectrograph2)
	(supports instrument13 image0)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 GroundStation16)
	(calibration_target instrument13 Star17)
	(calibration_target instrument13 GroundStation21)
	(calibration_target instrument13 GroundStation3)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 spectrograph1)
	(supports instrument14 image0)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation18)
	(calibration_target instrument14 GroundStation2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation10)
	(supports instrument15 image3)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 GroundStation4)
	(calibration_target instrument15 GroundStation0)
	(calibration_target instrument15 GroundStation3)
	(calibration_target instrument15 GroundStation16)
	(supports instrument16 spectrograph1)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 spectrograph2)
	(supports instrument17 image3)
	(supports instrument17 image0)
	(calibration_target instrument17 Star17)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation20)
	(supports instrument18 image0)
	(supports instrument18 spectrograph2)
	(supports instrument18 image3)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 Star19)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 Star14)
	(calibration_target instrument18 Star22)
	(calibration_target instrument18 GroundStation20)
	(supports instrument19 thermograph4)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 GroundStation8)
	(calibration_target instrument19 GroundStation0)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 GroundStation18)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 spectrograph2)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 GroundStation15)
	(supports instrument21 thermograph4)
	(supports instrument21 spectrograph2)
	(supports instrument21 image3)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 GroundStation15)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 GroundStation21)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 Star12)
	(supports instrument22 image3)
	(supports instrument22 spectrograph1)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 Star19)
	(supports instrument23 image0)
	(supports instrument23 spectrograph1)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation3)
	(calibration_target instrument23 GroundStation16)
	(supports instrument24 spectrograph1)
	(supports instrument24 image3)
	(supports instrument24 spectrograph2)
	(calibration_target instrument24 GroundStation10)
	(calibration_target instrument24 GroundStation18)
	(calibration_target instrument24 Star1)
	(calibration_target instrument24 GroundStation13)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation2)
	(supports instrument25 image0)
	(supports instrument25 thermograph4)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 Star9)
	(calibration_target instrument25 Star14)
	(calibration_target instrument25 Star22)
	(calibration_target instrument25 GroundStation3)
	(calibration_target instrument25 Star7)
	(calibration_target instrument25 GroundStation13)
	(calibration_target instrument25 GroundStation16)
	(supports instrument26 image0)
	(calibration_target instrument26 Star7)
	(calibration_target instrument26 Star12)
	(calibration_target instrument26 GroundStation6)
	(calibration_target instrument26 Star17)
	(supports instrument27 image3)
	(supports instrument27 spectrograph2)
	(supports instrument27 image0)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 GroundStation18)
	(supports instrument28 image3)
	(calibration_target instrument28 GroundStation4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation6)
	(supports instrument29 spectrograph2)
	(calibration_target instrument29 GroundStation3)
	(calibration_target instrument29 Star12)
	(calibration_target instrument29 Star1)
	(supports instrument30 spectrograph1)
	(calibration_target instrument30 GroundStation15)
	(supports instrument31 image3)
	(calibration_target instrument31 GroundStation6)
	(calibration_target instrument31 Star7)
	(calibration_target instrument31 Star14)
	(supports instrument32 thermograph4)
	(supports instrument32 spectrograph1)
	(calibration_target instrument32 Star17)
	(calibration_target instrument32 Star12)
	(calibration_target instrument32 GroundStation0)
	(calibration_target instrument32 GroundStation2)
	(calibration_target instrument32 Star7)
	(calibration_target instrument32 GroundStation3)
	(calibration_target instrument32 GroundStation13)
	(supports instrument33 thermograph4)
	(supports instrument33 spectrograph2)
	(supports instrument33 spectrograph1)
	(calibration_target instrument33 GroundStation3)
	(calibration_target instrument33 GroundStation21)
	(supports instrument34 image3)
	(supports instrument34 spectrograph1)
	(supports instrument34 spectrograph2)
	(calibration_target instrument34 GroundStation4)
	(calibration_target instrument34 Star17)
	(calibration_target instrument34 GroundStation6)
	(calibration_target instrument34 GroundStation20)
	(calibration_target instrument34 Star14)
	(calibration_target instrument34 GroundStation2)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation18)
	(supports instrument35 image3)
	(calibration_target instrument35 GroundStation4)
	(calibration_target instrument35 GroundStation8)
	(calibration_target instrument35 GroundStation15)
	(calibration_target instrument35 GroundStation13)
	(supports instrument36 thermograph4)
	(supports instrument36 image0)
	(calibration_target instrument36 Star9)
	(calibration_target instrument36 GroundStation6)
	(supports instrument37 image3)
	(calibration_target instrument37 Star7)
	(calibration_target instrument37 Star14)
	(supports instrument38 spectrograph1)
	(supports instrument38 spectrograph2)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation18)
	(calibration_target instrument38 Star17)
	(calibration_target instrument38 Star1)
	(calibration_target instrument38 Star22)
	(calibration_target instrument38 GroundStation8)
	(calibration_target instrument38 GroundStation4)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation6)
	(supports instrument39 image3)
	(calibration_target instrument39 GroundStation2)
	(calibration_target instrument39 GroundStation16)
	(calibration_target instrument39 Star9)
	(calibration_target instrument39 Star14)
	(calibration_target instrument39 Star17)
	(supports instrument40 image3)
	(calibration_target instrument40 Star11)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 Star5)
	(supports instrument41 thermograph4)
	(supports instrument41 image0)
	(calibration_target instrument41 Star22)
	(calibration_target instrument41 GroundStation21)
	(calibration_target instrument41 Star12)
	(supports instrument42 image3)
	(calibration_target instrument42 Star17)
	(calibration_target instrument42 Star19)
	(calibration_target instrument42 GroundStation15)
	(calibration_target instrument42 GroundStation8)
	(calibration_target instrument42 Star22)
	(supports instrument43 spectrograph1)
	(supports instrument43 image0)
	(calibration_target instrument43 GroundStation18)
	(calibration_target instrument43 Star17)
	(calibration_target instrument43 Star5)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation18)
	(supports instrument44 image3)
	(calibration_target instrument44 Star19)
	(calibration_target instrument44 GroundStation10)
	(calibration_target instrument44 GroundStation16)
	(calibration_target instrument44 GroundStation3)
	(on_board instrument44 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star19)
	(supports instrument45 thermograph4)
	(supports instrument45 spectrograph1)
	(supports instrument45 image3)
	(calibration_target instrument45 GroundStation21)
	(calibration_target instrument45 GroundStation18)
	(calibration_target instrument45 Star11)
	(calibration_target instrument45 GroundStation0)
	(calibration_target instrument45 GroundStation6)
	(on_board instrument45 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation13)
)
(:goal (and
	(pointing satellite1 Star5)
	(pointing satellite4 GroundStation4)
	(pointing satellite5 GroundStation10)
	(pointing satellite8 GroundStation4)
	(have_image Phenomenon23 spectrograph2)
	(have_image Planet24 image3)
))

)
