(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite4 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite5 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite6 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite7 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	satellite9 - satellite
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	thermograph0 - mode
	infrared2 - mode
	infrared1 - mode
	image3 - mode
	infrared4 - mode
	GroundStation13 - direction
	GroundStation2 - direction
	Star3 - direction
	Star14 - direction
	Star10 - direction
	Star6 - direction
	Star0 - direction
	Star15 - direction
	GroundStation4 - direction
	Star1 - direction
	Star5 - direction
	GroundStation11 - direction
	GroundStation18 - direction
	GroundStation8 - direction
	Star12 - direction
	GroundStation17 - direction
	Star9 - direction
	Star16 - direction
	GroundStation7 - direction
	Star19 - direction
	Star20 - direction
)
(:init
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star9)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star15)
	(supports instrument1 infrared1)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 Star6)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared4)
	(supports instrument2 infrared1)
	(calibration_target instrument2 Star15)
	(calibration_target instrument2 Star3)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 GroundStation7)
	(supports instrument4 image3)
	(supports instrument4 infrared4)
	(calibration_target instrument4 Star15)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 Star12)
	(calibration_target instrument4 Star16)
	(calibration_target instrument4 GroundStation4)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation13)
	(calibration_target instrument5 Star5)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument6 thermograph0)
	(supports instrument6 image3)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 GroundStation11)
	(calibration_target instrument6 Star12)
	(supports instrument7 infrared1)
	(supports instrument7 infrared4)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 Star6)
	(supports instrument8 image3)
	(calibration_target instrument8 Star14)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 Star15)
	(supports instrument9 infrared4)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 Star15)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation4)
	(calibration_target instrument9 GroundStation8)
	(supports instrument10 image3)
	(supports instrument10 infrared2)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 Star15)
	(calibration_target instrument10 GroundStation7)
	(supports instrument11 infrared2)
	(calibration_target instrument11 Star16)
	(calibration_target instrument11 GroundStation13)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 Star14)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 GroundStation18)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 Star5)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star20)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation7)
	(calibration_target instrument13 Star9)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 GroundStation11)
	(supports instrument14 infrared4)
	(supports instrument14 infrared2)
	(calibration_target instrument14 Star6)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 Star10)
	(calibration_target instrument14 GroundStation17)
	(calibration_target instrument14 Star15)
	(calibration_target instrument14 GroundStation4)
	(supports instrument15 image3)
	(supports instrument15 infrared2)
	(calibration_target instrument15 Star12)
	(supports instrument16 infrared4)
	(calibration_target instrument16 Star15)
	(calibration_target instrument16 Star10)
	(supports instrument17 infrared1)
	(supports instrument17 infrared4)
	(supports instrument17 image3)
	(calibration_target instrument17 GroundStation17)
	(calibration_target instrument17 Star9)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument18 infrared2)
	(supports instrument18 image3)
	(supports instrument18 infrared1)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 Star10)
	(calibration_target instrument18 GroundStation17)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation13)
	(supports instrument19 infrared2)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 GroundStation17)
	(supports instrument20 thermograph0)
	(supports instrument20 infrared2)
	(supports instrument20 image3)
	(calibration_target instrument20 Star10)
	(calibration_target instrument20 GroundStation7)
	(calibration_target instrument20 Star3)
	(supports instrument21 thermograph0)
	(supports instrument21 image3)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 GroundStation17)
	(supports instrument22 infrared2)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation18)
	(supports instrument23 infrared1)
	(supports instrument23 infrared4)
	(calibration_target instrument23 GroundStation7)
	(calibration_target instrument23 GroundStation17)
	(calibration_target instrument23 Star16)
	(supports instrument24 image3)
	(supports instrument24 infrared2)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 GroundStation7)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 GroundStation11)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 Star1)
	(supports instrument25 infrared1)
	(calibration_target instrument25 Star9)
	(calibration_target instrument25 Star3)
	(calibration_target instrument25 Star6)
	(supports instrument26 infrared1)
	(supports instrument26 infrared4)
	(supports instrument26 image3)
	(calibration_target instrument26 Star9)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 Star1)
	(calibration_target instrument26 Star15)
	(supports instrument27 infrared1)
	(calibration_target instrument27 GroundStation11)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star9)
	(supports instrument28 infrared1)
	(supports instrument28 image3)
	(calibration_target instrument28 Star15)
	(calibration_target instrument28 GroundStation2)
	(calibration_target instrument28 Star16)
	(calibration_target instrument28 GroundStation7)
	(supports instrument29 infrared1)
	(supports instrument29 infrared4)
	(calibration_target instrument29 GroundStation11)
	(calibration_target instrument29 Star9)
	(calibration_target instrument29 GroundStation2)
	(calibration_target instrument29 Star16)
	(calibration_target instrument29 Star6)
	(calibration_target instrument29 GroundStation7)
	(supports instrument30 infrared1)
	(calibration_target instrument30 Star15)
	(calibration_target instrument30 Star6)
	(calibration_target instrument30 GroundStation13)
	(calibration_target instrument30 GroundStation4)
	(calibration_target instrument30 Star0)
	(supports instrument31 infrared4)
	(calibration_target instrument31 Star12)
	(calibration_target instrument31 Star10)
	(calibration_target instrument31 Star9)
	(calibration_target instrument31 Star15)
	(calibration_target instrument31 Star6)
	(supports instrument32 thermograph0)
	(supports instrument32 infrared4)
	(supports instrument32 infrared1)
	(calibration_target instrument32 Star12)
	(calibration_target instrument32 Star0)
	(supports instrument33 infrared2)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 GroundStation17)
	(calibration_target instrument33 Star6)
	(calibration_target instrument33 GroundStation8)
	(calibration_target instrument33 GroundStation13)
	(calibration_target instrument33 Star9)
	(calibration_target instrument33 Star1)
	(supports instrument34 infrared4)
	(supports instrument34 infrared1)
	(calibration_target instrument34 Star6)
	(supports instrument35 image3)
	(supports instrument35 infrared2)
	(supports instrument35 infrared1)
	(calibration_target instrument35 GroundStation4)
	(calibration_target instrument35 GroundStation7)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument36 infrared1)
	(calibration_target instrument36 Star12)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star15)
	(calibration_target instrument36 Star14)
	(calibration_target instrument36 GroundStation7)
	(calibration_target instrument36 GroundStation17)
	(supports instrument37 infrared2)
	(supports instrument37 thermograph0)
	(calibration_target instrument37 Star15)
	(supports instrument38 infrared4)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 Star10)
	(calibration_target instrument38 GroundStation7)
	(calibration_target instrument38 GroundStation11)
	(calibration_target instrument38 Star15)
	(supports instrument39 image3)
	(supports instrument39 infrared1)
	(supports instrument39 infrared4)
	(calibration_target instrument39 Star3)
	(supports instrument40 infrared2)
	(supports instrument40 infrared1)
	(calibration_target instrument40 Star5)
	(calibration_target instrument40 GroundStation18)
	(calibration_target instrument40 Star14)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 Star16)
	(calibration_target instrument40 Star6)
	(supports instrument41 image3)
	(calibration_target instrument41 Star0)
	(calibration_target instrument41 Star12)
	(calibration_target instrument41 GroundStation18)
	(calibration_target instrument41 Star5)
	(calibration_target instrument41 Star9)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation11)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 GroundStation13)
	(supports instrument43 infrared1)
	(supports instrument43 thermograph0)
	(supports instrument43 infrared4)
	(calibration_target instrument43 Star5)
	(calibration_target instrument43 Star6)
	(calibration_target instrument43 GroundStation13)
	(supports instrument44 image3)
	(supports instrument44 thermograph0)
	(calibration_target instrument44 GroundStation7)
	(supports instrument45 infrared4)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 Star5)
	(calibration_target instrument45 Star10)
	(calibration_target instrument45 Star6)
	(calibration_target instrument45 Star3)
	(calibration_target instrument45 GroundStation17)
	(calibration_target instrument45 GroundStation2)
	(supports instrument46 infrared1)
	(calibration_target instrument46 Star6)
	(calibration_target instrument46 Star5)
	(calibration_target instrument46 Star10)
	(calibration_target instrument46 Star14)
	(calibration_target instrument46 Star16)
	(calibration_target instrument46 GroundStation4)
	(supports instrument47 thermograph0)
	(calibration_target instrument47 Star15)
	(calibration_target instrument47 Star0)
	(calibration_target instrument47 Star16)
	(supports instrument48 infrared4)
	(calibration_target instrument48 Star9)
	(calibration_target instrument48 GroundStation4)
	(supports instrument49 thermograph0)
	(supports instrument49 infrared1)
	(supports instrument49 image3)
	(calibration_target instrument49 Star5)
	(calibration_target instrument49 Star9)
	(calibration_target instrument49 Star1)
	(calibration_target instrument49 GroundStation4)
	(supports instrument50 infrared1)
	(supports instrument50 thermograph0)
	(supports instrument50 infrared2)
	(calibration_target instrument50 GroundStation8)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star10)
	(supports instrument51 infrared2)
	(supports instrument51 image3)
	(calibration_target instrument51 GroundStation7)
	(on_board instrument51 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation18)
	(supports instrument52 infrared1)
	(supports instrument52 thermograph0)
	(calibration_target instrument52 GroundStation17)
	(calibration_target instrument52 GroundStation11)
	(supports instrument53 infrared4)
	(calibration_target instrument53 GroundStation11)
	(supports instrument54 infrared1)
	(supports instrument54 infrared2)
	(calibration_target instrument54 Star9)
	(calibration_target instrument54 GroundStation8)
	(calibration_target instrument54 Star12)
	(calibration_target instrument54 GroundStation18)
	(supports instrument55 infrared1)
	(calibration_target instrument55 GroundStation8)
	(supports instrument56 infrared4)
	(supports instrument56 image3)
	(calibration_target instrument56 GroundStation7)
	(calibration_target instrument56 Star16)
	(calibration_target instrument56 Star9)
	(calibration_target instrument56 GroundStation17)
	(calibration_target instrument56 Star12)
	(calibration_target instrument56 GroundStation8)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star9)
)
(:goal (and
	(pointing satellite0 GroundStation17)
	(pointing satellite3 GroundStation7)
	(pointing satellite5 GroundStation13)
	(pointing satellite7 GroundStation18)
	(pointing satellite8 GroundStation4)
	(have_image Star19 image3)
))
(:metric minimize (total-time))

)
