(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite6 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite7 - satellite
	instrument40 - instrument
	satellite8 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite9 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	thermograph4 - mode
	image2 - mode
	infrared0 - mode
	infrared1 - mode
	spectrograph3 - mode
	GroundStation15 - direction
	Star1 - direction
	Star8 - direction
	GroundStation17 - direction
	Star0 - direction
	GroundStation4 - direction
	Star7 - direction
	Star6 - direction
	GroundStation14 - direction
	Star13 - direction
	Star2 - direction
	GroundStation12 - direction
	Star3 - direction
	Star11 - direction
	Star18 - direction
	GroundStation16 - direction
	GroundStation10 - direction
	GroundStation9 - direction
	GroundStation5 - direction
	Star19 - direction
	Planet20 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 spectrograph3)
	(supports instrument0 image2)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 Star7)
	(supports instrument1 spectrograph3)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star18)
	(calibration_target instrument1 Star11)
	(calibration_target instrument1 Star6)
	(supports instrument2 infrared0)
	(supports instrument2 spectrograph3)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation17)
	(supports instrument3 infrared0)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 GroundStation12)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 GroundStation15)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 GroundStation12)
	(supports instrument5 thermograph4)
	(supports instrument5 infrared1)
	(supports instrument5 image2)
	(calibration_target instrument5 GroundStation5)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 GroundStation14)
	(calibration_target instrument6 Star6)
	(supports instrument7 infrared0)
	(supports instrument7 spectrograph3)
	(calibration_target instrument7 Star2)
	(calibration_target instrument7 GroundStation10)
	(calibration_target instrument7 Star11)
	(calibration_target instrument7 Star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star18)
	(supports instrument8 image2)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation15)
	(calibration_target instrument8 Star7)
	(supports instrument9 infrared1)
	(supports instrument9 infrared0)
	(supports instrument9 spectrograph3)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 Star3)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation10)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation12)
	(calibration_target instrument10 GroundStation9)
	(calibration_target instrument10 GroundStation17)
	(calibration_target instrument10 Star11)
	(supports instrument11 spectrograph3)
	(calibration_target instrument11 GroundStation4)
	(supports instrument12 thermograph4)
	(supports instrument12 spectrograph3)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 GroundStation9)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 GroundStation16)
	(calibration_target instrument12 Star13)
	(supports instrument13 spectrograph3)
	(calibration_target instrument13 Star11)
	(calibration_target instrument13 Star8)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation16)
	(supports instrument14 thermograph4)
	(supports instrument14 image2)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star18)
	(supports instrument15 infrared0)
	(supports instrument15 infrared1)
	(supports instrument15 spectrograph3)
	(calibration_target instrument15 GroundStation17)
	(calibration_target instrument15 Star18)
	(calibration_target instrument15 GroundStation10)
	(calibration_target instrument15 GroundStation14)
	(supports instrument16 image2)
	(supports instrument16 infrared1)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 GroundStation9)
	(calibration_target instrument16 GroundStation10)
	(supports instrument17 spectrograph3)
	(supports instrument17 infrared1)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star11)
	(calibration_target instrument17 Star1)
	(supports instrument18 image2)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation12)
	(calibration_target instrument18 GroundStation10)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 Star13)
	(supports instrument20 image2)
	(supports instrument20 spectrograph3)
	(calibration_target instrument20 GroundStation12)
	(calibration_target instrument20 Star7)
	(supports instrument21 thermograph4)
	(supports instrument21 image2)
	(calibration_target instrument21 Star2)
	(calibration_target instrument21 GroundStation14)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 GroundStation9)
	(calibration_target instrument21 Star8)
	(supports instrument22 thermograph4)
	(supports instrument22 image2)
	(supports instrument22 infrared0)
	(calibration_target instrument22 GroundStation4)
	(supports instrument23 infrared0)
	(supports instrument23 infrared1)
	(calibration_target instrument23 GroundStation17)
	(calibration_target instrument23 Star6)
	(supports instrument24 spectrograph3)
	(calibration_target instrument24 GroundStation12)
	(calibration_target instrument24 Star18)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star8)
	(supports instrument25 infrared0)
	(supports instrument25 image2)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 Star3)
	(calibration_target instrument25 GroundStation9)
	(calibration_target instrument25 Star13)
	(supports instrument26 infrared1)
	(supports instrument26 spectrograph3)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 Star8)
	(calibration_target instrument26 GroundStation16)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star11)
	(supports instrument27 spectrograph3)
	(supports instrument27 infrared1)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 Star11)
	(calibration_target instrument27 GroundStation15)
	(calibration_target instrument27 GroundStation9)
	(calibration_target instrument27 GroundStation5)
	(supports instrument28 infrared1)
	(supports instrument28 infrared0)
	(supports instrument28 image2)
	(calibration_target instrument28 Star13)
	(calibration_target instrument28 Star1)
	(calibration_target instrument28 GroundStation14)
	(calibration_target instrument28 Star11)
	(calibration_target instrument28 GroundStation17)
	(supports instrument29 infrared1)
	(calibration_target instrument29 Star11)
	(calibration_target instrument29 GroundStation15)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation12)
	(supports instrument30 thermograph4)
	(supports instrument30 infrared0)
	(supports instrument30 image2)
	(calibration_target instrument30 Star11)
	(calibration_target instrument30 Star18)
	(calibration_target instrument30 Star1)
	(supports instrument31 thermograph4)
	(supports instrument31 spectrograph3)
	(supports instrument31 image2)
	(calibration_target instrument31 GroundStation14)
	(supports instrument32 infrared1)
	(supports instrument32 image2)
	(supports instrument32 thermograph4)
	(calibration_target instrument32 GroundStation16)
	(supports instrument33 infrared1)
	(calibration_target instrument33 GroundStation12)
	(calibration_target instrument33 Star0)
	(supports instrument34 infrared1)
	(calibration_target instrument34 Star18)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 GroundStation15)
	(supports instrument35 infrared0)
	(calibration_target instrument35 GroundStation9)
	(supports instrument36 spectrograph3)
	(calibration_target instrument36 Star2)
	(supports instrument37 infrared0)
	(supports instrument37 image2)
	(calibration_target instrument37 Star3)
	(calibration_target instrument37 GroundStation14)
	(calibration_target instrument37 Star11)
	(calibration_target instrument37 Star1)
	(supports instrument38 image2)
	(calibration_target instrument38 GroundStation9)
	(supports instrument39 infrared1)
	(supports instrument39 thermograph4)
	(supports instrument39 image2)
	(calibration_target instrument39 Star8)
	(calibration_target instrument39 GroundStation14)
	(calibration_target instrument39 GroundStation9)
	(calibration_target instrument39 Star0)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument40 image2)
	(calibration_target instrument40 Star8)
	(calibration_target instrument40 Star13)
	(calibration_target instrument40 Star18)
	(calibration_target instrument40 GroundStation14)
	(calibration_target instrument40 Star6)
	(calibration_target instrument40 Star11)
	(on_board instrument40 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star6)
	(supports instrument41 infrared0)
	(supports instrument41 infrared1)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 GroundStation17)
	(calibration_target instrument41 Star7)
	(supports instrument42 spectrograph3)
	(supports instrument42 image2)
	(supports instrument42 thermograph4)
	(calibration_target instrument42 Star3)
	(calibration_target instrument42 GroundStation16)
	(calibration_target instrument42 Star0)
	(calibration_target instrument42 GroundStation5)
	(supports instrument43 thermograph4)
	(calibration_target instrument43 Star18)
	(calibration_target instrument43 GroundStation10)
	(calibration_target instrument43 Star13)
	(calibration_target instrument43 GroundStation4)
	(calibration_target instrument43 GroundStation14)
	(supports instrument44 image2)
	(supports instrument44 infrared1)
	(calibration_target instrument44 Star18)
	(calibration_target instrument44 GroundStation14)
	(calibration_target instrument44 GroundStation16)
	(calibration_target instrument44 Star11)
	(supports instrument45 image2)
	(supports instrument45 infrared1)
	(supports instrument45 spectrograph3)
	(calibration_target instrument45 Star13)
	(calibration_target instrument45 GroundStation14)
	(calibration_target instrument45 Star6)
	(calibration_target instrument45 GroundStation5)
	(calibration_target instrument45 Star7)
	(supports instrument46 infrared0)
	(calibration_target instrument46 Star2)
	(calibration_target instrument46 GroundStation10)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
	(supports instrument47 infrared0)
	(supports instrument47 image2)
	(supports instrument47 infrared1)
	(calibration_target instrument47 GroundStation16)
	(calibration_target instrument47 Star18)
	(calibration_target instrument47 Star11)
	(calibration_target instrument47 Star3)
	(calibration_target instrument47 GroundStation10)
	(calibration_target instrument47 GroundStation12)
	(supports instrument48 spectrograph3)
	(calibration_target instrument48 GroundStation9)
	(calibration_target instrument48 GroundStation10)
	(supports instrument49 spectrograph3)
	(supports instrument49 infrared1)
	(supports instrument49 infrared0)
	(calibration_target instrument49 GroundStation5)
	(calibration_target instrument49 GroundStation9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star13)
)
(:goal (and
	(pointing satellite0 GroundStation4)
	(pointing satellite1 Star8)
	(pointing satellite9 Star13)
	(have_image Star19 infrared1)
	(have_image Planet20 infrared1)
))

)
