(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite1 - satellite
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite4 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite6 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite7 - satellite
	instrument40 - instrument
	satellite8 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite9 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	infrared2 - mode
	thermograph3 - mode
	image1 - mode
	spectrograph4 - mode
	thermograph0 - mode
	GroundStation18 - direction
	GroundStation12 - direction
	Star17 - direction
	Star16 - direction
	Star7 - direction
	GroundStation1 - direction
	GroundStation13 - direction
	Star14 - direction
	GroundStation4 - direction
	GroundStation11 - direction
	GroundStation3 - direction
	Star5 - direction
	GroundStation15 - direction
	GroundStation10 - direction
	Star0 - direction
	GroundStation8 - direction
	Star2 - direction
	GroundStation9 - direction
	Star6 - direction
	Star19 - direction
	Planet20 - direction
)
(:init
	(supports instrument0 image1)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 Star16)
	(calibration_target instrument0 GroundStation9)
	(supports instrument1 spectrograph4)
	(calibration_target instrument1 Star6)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation15)
	(calibration_target instrument2 GroundStation10)
	(calibration_target instrument2 GroundStation18)
	(calibration_target instrument2 GroundStation9)
	(calibration_target instrument2 GroundStation8)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 GroundStation9)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star16)
	(supports instrument4 infrared2)
	(supports instrument4 spectrograph4)
	(supports instrument4 image1)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 GroundStation3)
	(calibration_target instrument4 GroundStation8)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star14)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star2)
	(supports instrument6 thermograph3)
	(supports instrument6 image1)
	(calibration_target instrument6 Star0)
	(supports instrument7 image1)
	(supports instrument7 infrared2)
	(supports instrument7 spectrograph4)
	(calibration_target instrument7 GroundStation9)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation18)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 Star16)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star17)
	(calibration_target instrument8 GroundStation13)
	(calibration_target instrument8 GroundStation9)
	(supports instrument9 infrared2)
	(supports instrument9 spectrograph4)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 Star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star17)
	(supports instrument10 image1)
	(supports instrument10 thermograph3)
	(calibration_target instrument10 GroundStation13)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 Star6)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 Star16)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star14)
	(calibration_target instrument11 GroundStation12)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation11)
	(calibration_target instrument12 Star5)
	(calibration_target instrument12 GroundStation12)
	(supports instrument13 thermograph3)
	(calibration_target instrument13 GroundStation12)
	(calibration_target instrument13 GroundStation3)
	(calibration_target instrument13 GroundStation4)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation15)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 Star16)
	(supports instrument15 thermograph3)
	(supports instrument15 image1)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star16)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 GroundStation18)
	(supports instrument16 infrared2)
	(supports instrument16 thermograph0)
	(supports instrument16 spectrograph4)
	(calibration_target instrument16 Star2)
	(calibration_target instrument16 GroundStation11)
	(calibration_target instrument16 Star7)
	(calibration_target instrument16 GroundStation18)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 thermograph3)
	(supports instrument17 image1)
	(calibration_target instrument17 Star16)
	(calibration_target instrument17 GroundStation18)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star6)
	(supports instrument18 thermograph0)
	(supports instrument18 thermograph3)
	(calibration_target instrument18 Star17)
	(calibration_target instrument18 Star14)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation12)
	(calibration_target instrument19 GroundStation11)
	(calibration_target instrument19 GroundStation13)
	(calibration_target instrument19 Star2)
	(calibration_target instrument19 Star0)
	(supports instrument20 spectrograph4)
	(supports instrument20 thermograph0)
	(supports instrument20 thermograph3)
	(calibration_target instrument20 Star6)
	(calibration_target instrument20 GroundStation9)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 spectrograph4)
	(supports instrument21 infrared2)
	(supports instrument21 thermograph0)
	(calibration_target instrument21 GroundStation15)
	(calibration_target instrument21 GroundStation3)
	(supports instrument22 infrared2)
	(supports instrument22 thermograph3)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 Star5)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument23 infrared2)
	(supports instrument23 spectrograph4)
	(calibration_target instrument23 GroundStation15)
	(calibration_target instrument23 GroundStation13)
	(calibration_target instrument23 GroundStation11)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 GroundStation9)
	(supports instrument24 thermograph0)
	(supports instrument24 infrared2)
	(calibration_target instrument24 GroundStation18)
	(supports instrument25 thermograph3)
	(supports instrument25 image1)
	(calibration_target instrument25 Star7)
	(calibration_target instrument25 Star17)
	(calibration_target instrument25 GroundStation18)
	(calibration_target instrument25 GroundStation4)
	(calibration_target instrument25 Star2)
	(calibration_target instrument25 GroundStation11)
	(supports instrument26 spectrograph4)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 Star6)
	(calibration_target instrument26 GroundStation3)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation8)
	(supports instrument27 spectrograph4)
	(supports instrument27 thermograph0)
	(calibration_target instrument27 GroundStation10)
	(calibration_target instrument27 Star14)
	(supports instrument28 infrared2)
	(supports instrument28 thermograph0)
	(calibration_target instrument28 Star17)
	(calibration_target instrument28 GroundStation11)
	(supports instrument29 infrared2)
	(calibration_target instrument29 GroundStation13)
	(calibration_target instrument29 Star2)
	(calibration_target instrument29 Star17)
	(calibration_target instrument29 GroundStation4)
	(supports instrument30 image1)
	(calibration_target instrument30 Star2)
	(calibration_target instrument30 GroundStation3)
	(calibration_target instrument30 GroundStation9)
	(supports instrument31 thermograph3)
	(supports instrument31 infrared2)
	(supports instrument31 spectrograph4)
	(calibration_target instrument31 Star16)
	(supports instrument32 spectrograph4)
	(supports instrument32 image1)
	(supports instrument32 thermograph0)
	(calibration_target instrument32 Star5)
	(calibration_target instrument32 GroundStation13)
	(calibration_target instrument32 GroundStation8)
	(calibration_target instrument32 GroundStation4)
	(supports instrument33 infrared2)
	(supports instrument33 image1)
	(supports instrument33 thermograph3)
	(calibration_target instrument33 Star17)
	(calibration_target instrument33 GroundStation9)
	(calibration_target instrument33 GroundStation13)
	(calibration_target instrument33 Star7)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation18)
	(supports instrument34 thermograph3)
	(calibration_target instrument34 GroundStation11)
	(supports instrument35 thermograph0)
	(calibration_target instrument35 Star5)
	(supports instrument36 infrared2)
	(supports instrument36 image1)
	(calibration_target instrument36 GroundStation4)
	(supports instrument37 spectrograph4)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star16)
	(calibration_target instrument37 Star6)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 GroundStation12)
	(calibration_target instrument37 GroundStation18)
	(calibration_target instrument37 GroundStation13)
	(supports instrument38 infrared2)
	(supports instrument38 thermograph0)
	(supports instrument38 thermograph3)
	(calibration_target instrument38 Star7)
	(calibration_target instrument38 GroundStation15)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation12)
	(calibration_target instrument38 Star17)
	(calibration_target instrument38 GroundStation3)
	(supports instrument39 image1)
	(calibration_target instrument39 GroundStation1)
	(calibration_target instrument39 GroundStation10)
	(calibration_target instrument39 Star6)
	(calibration_target instrument39 Star17)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation3)
	(supports instrument40 infrared2)
	(calibration_target instrument40 GroundStation4)
	(on_board instrument40 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star5)
	(supports instrument41 thermograph3)
	(supports instrument41 thermograph0)
	(calibration_target instrument41 Star6)
	(calibration_target instrument41 GroundStation18)
	(supports instrument42 thermograph3)
	(calibration_target instrument42 Star16)
	(calibration_target instrument42 GroundStation8)
	(supports instrument43 thermograph0)
	(calibration_target instrument43 GroundStation13)
	(calibration_target instrument43 GroundStation4)
	(calibration_target instrument43 Star7)
	(calibration_target instrument43 GroundStation12)
	(calibration_target instrument43 Star5)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
	(supports instrument44 image1)
	(supports instrument44 infrared2)
	(supports instrument44 thermograph3)
	(calibration_target instrument44 Star17)
	(calibration_target instrument44 GroundStation12)
	(calibration_target instrument44 Star7)
	(supports instrument45 spectrograph4)
	(supports instrument45 thermograph0)
	(supports instrument45 thermograph3)
	(calibration_target instrument45 Star5)
	(calibration_target instrument45 GroundStation8)
	(calibration_target instrument45 GroundStation3)
	(calibration_target instrument45 GroundStation13)
	(calibration_target instrument45 Star16)
	(calibration_target instrument45 GroundStation1)
	(supports instrument46 image1)
	(supports instrument46 spectrograph4)
	(calibration_target instrument46 Star7)
	(calibration_target instrument46 GroundStation10)
	(calibration_target instrument46 Star2)
	(calibration_target instrument46 Star5)
	(supports instrument47 infrared2)
	(supports instrument47 thermograph3)
	(calibration_target instrument47 Star6)
	(calibration_target instrument47 GroundStation4)
	(calibration_target instrument47 GroundStation1)
	(calibration_target instrument47 Star0)
	(supports instrument48 image1)
	(supports instrument48 thermograph3)
	(calibration_target instrument48 GroundStation4)
	(calibration_target instrument48 GroundStation11)
	(calibration_target instrument48 Star14)
	(calibration_target instrument48 Star5)
	(calibration_target instrument48 GroundStation13)
	(calibration_target instrument48 GroundStation1)
	(supports instrument49 image1)
	(supports instrument49 spectrograph4)
	(calibration_target instrument49 GroundStation9)
	(calibration_target instrument49 Star0)
	(calibration_target instrument49 GroundStation8)
	(calibration_target instrument49 GroundStation3)
	(calibration_target instrument49 GroundStation11)
	(supports instrument50 thermograph0)
	(supports instrument50 spectrograph4)
	(calibration_target instrument50 GroundStation15)
	(calibration_target instrument50 Star5)
	(supports instrument51 thermograph0)
	(calibration_target instrument51 Star6)
	(calibration_target instrument51 GroundStation9)
	(calibration_target instrument51 Star2)
	(calibration_target instrument51 GroundStation8)
	(calibration_target instrument51 Star0)
	(calibration_target instrument51 GroundStation10)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet20)
)
(:goal (and
	(pointing satellite0 GroundStation4)
	(pointing satellite3 GroundStation1)
	(pointing satellite4 Star0)
	(pointing satellite7 Star0)
	(pointing satellite9 Star6)
	(have_image Star19 thermograph0)
	(have_image Planet20 thermograph3)
))

)
