(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite5 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite6 - satellite
	instrument25 - instrument
	instrument26 - instrument
	satellite7 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite8 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite9 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	infrared2 - mode
	image3 - mode
	infrared1 - mode
	thermograph0 - mode
	infrared4 - mode
	GroundStation2 - direction
	GroundStation4 - direction
	Star6 - direction
	Star0 - direction
	GroundStation7 - direction
	Star10 - direction
	Star9 - direction
	Star1 - direction
	GroundStation8 - direction
	Star3 - direction
	Star5 - direction
	Planet11 - direction
	Phenomenon12 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 image3)
	(calibration_target instrument0 Star10)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 Star1)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star5)
	(supports instrument2 image3)
	(calibration_target instrument2 Star1)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star5)
	(supports instrument4 image3)
	(calibration_target instrument4 Star5)
	(supports instrument5 infrared4)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation7)
	(calibration_target instrument5 Star1)
	(supports instrument6 infrared2)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star0)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 GroundStation7)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument8 image3)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star9)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(supports instrument9 infrared1)
	(supports instrument9 infrared2)
	(supports instrument9 infrared4)
	(calibration_target instrument9 GroundStation8)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation7)
	(supports instrument11 infrared2)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 Star10)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 GroundStation4)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation8)
	(calibration_target instrument12 Star1)
	(supports instrument13 infrared1)
	(supports instrument13 infrared2)
	(supports instrument13 infrared4)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation7)
	(calibration_target instrument13 Star9)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star10)
	(supports instrument14 infrared1)
	(supports instrument14 thermograph0)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 Star10)
	(supports instrument15 infrared1)
	(supports instrument15 infrared4)
	(supports instrument15 image3)
	(calibration_target instrument15 Star9)
	(calibration_target instrument15 GroundStation8)
	(supports instrument16 image3)
	(supports instrument16 infrared2)
	(calibration_target instrument16 GroundStation8)
	(supports instrument17 infrared2)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 GroundStation8)
	(calibration_target instrument18 GroundStation2)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon12)
	(supports instrument19 image3)
	(supports instrument19 infrared4)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star5)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 image3)
	(supports instrument20 infrared4)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star1)
	(calibration_target instrument20 Star10)
	(supports instrument21 image3)
	(supports instrument21 infrared2)
	(calibration_target instrument21 Star1)
	(supports instrument22 thermograph0)
	(calibration_target instrument22 Star5)
	(supports instrument23 image3)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 Star1)
	(supports instrument24 infrared1)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 GroundStation7)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation8)
	(supports instrument25 infrared1)
	(supports instrument25 infrared2)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 GroundStation8)
	(supports instrument26 infrared4)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 Star6)
	(calibration_target instrument26 Star9)
	(calibration_target instrument26 Star0)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet11)
	(supports instrument27 image3)
	(supports instrument27 infrared4)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 Star3)
	(supports instrument28 thermograph0)
	(supports instrument28 image3)
	(calibration_target instrument28 Star10)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 Star5)
	(supports instrument29 infrared2)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 GroundStation4)
	(supports instrument30 infrared2)
	(calibration_target instrument30 Star9)
	(supports instrument31 infrared2)
	(supports instrument31 image3)
	(supports instrument31 thermograph0)
	(calibration_target instrument31 Star10)
	(calibration_target instrument31 GroundStation2)
	(supports instrument32 infrared2)
	(supports instrument32 infrared4)
	(calibration_target instrument32 Star10)
	(calibration_target instrument32 Star0)
	(supports instrument33 infrared2)
	(supports instrument33 infrared1)
	(calibration_target instrument33 Star6)
	(calibration_target instrument33 Star10)
	(supports instrument34 image3)
	(supports instrument34 thermograph0)
	(calibration_target instrument34 Star10)
	(calibration_target instrument34 Star0)
	(on_board instrument27 satellite7)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star10)
	(supports instrument35 infrared1)
	(calibration_target instrument35 Star3)
	(supports instrument36 infrared4)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 Star1)
	(supports instrument37 infrared4)
	(supports instrument37 thermograph0)
	(calibration_target instrument37 Star6)
	(calibration_target instrument37 Star10)
	(calibration_target instrument37 Star1)
	(supports instrument38 thermograph0)
	(supports instrument38 image3)
	(supports instrument38 infrared2)
	(calibration_target instrument38 Star5)
	(supports instrument39 infrared4)
	(supports instrument39 thermograph0)
	(calibration_target instrument39 Star6)
	(calibration_target instrument39 GroundStation7)
	(calibration_target instrument39 GroundStation4)
	(supports instrument40 infrared2)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 GroundStation7)
	(supports instrument41 infrared2)
	(supports instrument41 infrared1)
	(supports instrument41 thermograph0)
	(calibration_target instrument41 Star5)
	(calibration_target instrument41 GroundStation7)
	(calibration_target instrument41 Star10)
	(supports instrument42 thermograph0)
	(supports instrument42 infrared4)
	(calibration_target instrument42 Star10)
	(calibration_target instrument42 Star0)
	(calibration_target instrument42 Star6)
	(on_board instrument35 satellite8)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star9)
	(supports instrument43 image3)
	(supports instrument43 infrared2)
	(calibration_target instrument43 Star10)
	(supports instrument44 image3)
	(supports instrument44 infrared1)
	(supports instrument44 thermograph0)
	(calibration_target instrument44 GroundStation2)
	(calibration_target instrument44 Star0)
	(supports instrument45 infrared1)
	(calibration_target instrument45 GroundStation8)
	(calibration_target instrument45 Star9)
	(supports instrument46 infrared1)
	(supports instrument46 infrared4)
	(calibration_target instrument46 Star5)
	(calibration_target instrument46 Star10)
	(calibration_target instrument46 GroundStation4)
	(supports instrument47 infrared1)
	(supports instrument47 infrared4)
	(calibration_target instrument47 Star6)
	(calibration_target instrument47 GroundStation8)
	(supports instrument48 infrared1)
	(calibration_target instrument48 Star1)
	(calibration_target instrument48 Star9)
	(supports instrument49 image3)
	(calibration_target instrument49 Star0)
	(calibration_target instrument49 GroundStation8)
	(supports instrument50 infrared2)
	(supports instrument50 infrared4)
	(calibration_target instrument50 Star9)
	(calibration_target instrument50 Star10)
	(calibration_target instrument50 GroundStation7)
	(supports instrument51 thermograph0)
	(supports instrument51 infrared1)
	(supports instrument51 image3)
	(calibration_target instrument51 GroundStation8)
	(calibration_target instrument51 Star1)
	(calibration_target instrument51 Star3)
	(supports instrument52 infrared4)
	(calibration_target instrument52 Star5)
	(calibration_target instrument52 Star3)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star3)
)
(:goal (and
	(pointing satellite0 Star0)
	(pointing satellite2 GroundStation7)
	(pointing satellite3 Star5)
	(have_image Planet11 thermograph0)
))

)
