(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite1 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite3 - satellite
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	satellite6 - satellite
	instrument29 - instrument
	satellite7 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite8 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite9 - satellite
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	infrared2 - mode
	spectrograph0 - mode
	infrared1 - mode
	thermograph3 - mode
	thermograph4 - mode
	GroundStation1 - direction
	GroundStation7 - direction
	Star3 - direction
	Star2 - direction
	Star6 - direction
	Star8 - direction
	Star0 - direction
	Star4 - direction
	GroundStation9 - direction
	Star5 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 thermograph4)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 infrared1)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 Star8)
	(calibration_target instrument1 GroundStation7)
	(supports instrument2 spectrograph0)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation9)
	(supports instrument3 infrared1)
	(supports instrument3 spectrograph0)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 Star6)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 Star5)
	(supports instrument5 infrared1)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star3)
	(supports instrument6 spectrograph0)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star2)
	(supports instrument7 infrared2)
	(supports instrument7 thermograph3)
	(calibration_target instrument7 GroundStation7)
	(supports instrument8 spectrograph0)
	(supports instrument8 thermograph4)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 Star8)
	(supports instrument9 thermograph3)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation1)
	(calibration_target instrument9 Star4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon11)
	(= (data_capacity satellite0) 1000)
	(= (fuel satellite0) 179)
	(supports instrument10 infrared2)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star6)
	(supports instrument11 spectrograph0)
	(supports instrument11 thermograph4)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star6)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star8)
	(supports instrument12 thermograph3)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star5)
	(supports instrument13 spectrograph0)
	(supports instrument13 thermograph3)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 Star8)
	(supports instrument14 infrared1)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star2)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 GroundStation9)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star4)
	(= (data_capacity satellite1) 1000)
	(= (fuel satellite1) 175)
	(supports instrument16 infrared2)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star8)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star0)
	(supports instrument18 infrared2)
	(supports instrument18 thermograph3)
	(supports instrument18 infrared1)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 GroundStation7)
	(calibration_target instrument18 Star8)
	(supports instrument19 thermograph3)
	(supports instrument19 thermograph4)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star4)
	(supports instrument20 spectrograph0)
	(supports instrument20 infrared1)
	(calibration_target instrument20 Star6)
	(supports instrument21 infrared2)
	(calibration_target instrument21 Star5)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(= (data_capacity satellite2) 1000)
	(= (fuel satellite2) 128)
	(supports instrument22 thermograph3)
	(supports instrument22 thermograph4)
	(supports instrument22 infrared2)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 GroundStation7)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 GroundStation1)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star5)
	(= (data_capacity satellite3) 1000)
	(= (fuel satellite3) 113)
	(supports instrument24 thermograph4)
	(supports instrument24 thermograph3)
	(supports instrument24 infrared1)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 Star6)
	(supports instrument25 thermograph3)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 Star4)
	(supports instrument26 infrared1)
	(supports instrument26 infrared2)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 Star6)
	(calibration_target instrument26 GroundStation9)
	(calibration_target instrument26 Star5)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(= (data_capacity satellite4) 1000)
	(= (fuel satellite4) 131)
	(supports instrument27 infrared2)
	(calibration_target instrument27 GroundStation9)
	(calibration_target instrument27 Star4)
	(calibration_target instrument27 Star0)
	(supports instrument28 spectrograph0)
	(supports instrument28 infrared2)
	(calibration_target instrument28 GroundStation7)
	(calibration_target instrument28 Star8)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(= (data_capacity satellite5) 1000)
	(= (fuel satellite5) 159)
	(supports instrument29 infrared1)
	(calibration_target instrument29 GroundStation9)
	(calibration_target instrument29 GroundStation7)
	(calibration_target instrument29 Star5)
	(on_board instrument29 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(= (data_capacity satellite6) 1000)
	(= (fuel satellite6) 126)
	(supports instrument30 infrared1)
	(supports instrument30 thermograph3)
	(supports instrument30 infrared2)
	(calibration_target instrument30 Star8)
	(supports instrument31 infrared1)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 Star2)
	(supports instrument32 spectrograph0)
	(supports instrument32 thermograph4)
	(calibration_target instrument32 Star2)
	(supports instrument33 infrared1)
	(supports instrument33 thermograph3)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 Star3)
	(calibration_target instrument33 GroundStation9)
	(supports instrument34 infrared2)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 Star4)
	(supports instrument35 infrared2)
	(supports instrument35 thermograph4)
	(calibration_target instrument35 Star5)
	(calibration_target instrument35 GroundStation1)
	(supports instrument36 infrared2)
	(calibration_target instrument36 GroundStation7)
	(calibration_target instrument36 Star2)
	(calibration_target instrument36 Star0)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation7)
	(= (data_capacity satellite7) 1000)
	(= (fuel satellite7) 138)
	(supports instrument37 thermograph4)
	(supports instrument37 infrared2)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 Star6)
	(supports instrument38 thermograph4)
	(supports instrument38 infrared1)
	(supports instrument38 thermograph3)
	(calibration_target instrument38 Star3)
	(supports instrument39 thermograph3)
	(supports instrument39 spectrograph0)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 Star0)
	(supports instrument40 infrared1)
	(calibration_target instrument40 Star2)
	(calibration_target instrument40 Star8)
	(supports instrument41 thermograph4)
	(supports instrument41 thermograph3)
	(supports instrument41 infrared1)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 Star0)
	(supports instrument42 infrared2)
	(supports instrument42 thermograph3)
	(calibration_target instrument42 GroundStation7)
	(calibration_target instrument42 Star2)
	(calibration_target instrument42 Star8)
	(supports instrument43 spectrograph0)
	(supports instrument43 infrared1)
	(calibration_target instrument43 GroundStation9)
	(calibration_target instrument43 Star6)
	(supports instrument44 spectrograph0)
	(supports instrument44 infrared1)
	(supports instrument44 thermograph3)
	(calibration_target instrument44 Star3)
	(calibration_target instrument44 Star4)
	(calibration_target instrument44 Star2)
	(supports instrument45 spectrograph0)
	(supports instrument45 infrared1)
	(calibration_target instrument45 Star6)
	(calibration_target instrument45 Star2)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star5)
	(= (data_capacity satellite8) 1000)
	(= (fuel satellite8) 150)
	(supports instrument46 infrared1)
	(supports instrument46 thermograph3)
	(supports instrument46 spectrograph0)
	(calibration_target instrument46 Star8)
	(supports instrument47 infrared1)
	(calibration_target instrument47 Star4)
	(calibration_target instrument47 Star0)
	(supports instrument48 spectrograph0)
	(supports instrument48 infrared1)
	(calibration_target instrument48 GroundStation9)
	(supports instrument49 thermograph4)
	(supports instrument49 thermograph3)
	(supports instrument49 infrared1)
	(calibration_target instrument49 Star5)
	(calibration_target instrument49 GroundStation9)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
	(= (data_capacity satellite9) 1000)
	(= (fuel satellite9) 168)
	(= (data Phenomenon10 infrared2) 274)
	(= (data Phenomenon11 infrared2) 178)
	(= (data Phenomenon10 spectrograph0) 144)
	(= (data Phenomenon11 spectrograph0) 129)
	(= (data Phenomenon10 infrared1) 236)
	(= (data Phenomenon11 infrared1) 106)
	(= (data Phenomenon10 thermograph3) 254)
	(= (data Phenomenon11 thermograph3) 83)
	(= (data Phenomenon10 thermograph4) 21)
	(= (data Phenomenon11 thermograph4) 126)
	(= (slew_time GroundStation1 Star0) 37.82)
	(= (slew_time Star0 GroundStation1) 37.82)
	(= (slew_time GroundStation7 Star0) 7.381)
	(= (slew_time Star0 GroundStation7) 7.381)
	(= (slew_time GroundStation7 GroundStation1) 1.577)
	(= (slew_time GroundStation1 GroundStation7) 1.577)
	(= (slew_time GroundStation7 Star2) 72.03)
	(= (slew_time Star2 GroundStation7) 72.03)
	(= (slew_time GroundStation7 Star3) 19.76)
	(= (slew_time Star3 GroundStation7) 19.76)
	(= (slew_time GroundStation7 Star4) 3.509)
	(= (slew_time Star4 GroundStation7) 3.509)
	(= (slew_time GroundStation7 Star5) 55.59)
	(= (slew_time Star5 GroundStation7) 55.59)
	(= (slew_time GroundStation7 Star6) 32.78)
	(= (slew_time Star6 GroundStation7) 32.78)
	(= (slew_time Star3 Star0) 4.91)
	(= (slew_time Star0 Star3) 4.91)
	(= (slew_time Star3 GroundStation1) 9.686)
	(= (slew_time GroundStation1 Star3) 9.686)
	(= (slew_time Star3 Star2) 3.502)
	(= (slew_time Star2 Star3) 3.502)
	(= (slew_time Star2 Star0) 27.85)
	(= (slew_time Star0 Star2) 27.85)
	(= (slew_time Star2 GroundStation1) 6.537)
	(= (slew_time GroundStation1 Star2) 6.537)
	(= (slew_time Star6 Star0) 38.69)
	(= (slew_time Star0 Star6) 38.69)
	(= (slew_time Star6 GroundStation1) 21.62)
	(= (slew_time GroundStation1 Star6) 21.62)
	(= (slew_time Star6 Star2) 11.83)
	(= (slew_time Star2 Star6) 11.83)
	(= (slew_time Star6 Star3) 76.52)
	(= (slew_time Star3 Star6) 76.52)
	(= (slew_time Star6 Star4) 52.18)
	(= (slew_time Star4 Star6) 52.18)
	(= (slew_time Star6 Star5) 83.96)
	(= (slew_time Star5 Star6) 83.96)
	(= (slew_time Star8 Star0) 46.98)
	(= (slew_time Star0 Star8) 46.98)
	(= (slew_time Star8 GroundStation1) 32.22)
	(= (slew_time GroundStation1 Star8) 32.22)
	(= (slew_time Star8 Star2) 57.34)
	(= (slew_time Star2 Star8) 57.34)
	(= (slew_time Star8 Star3) 71.87)
	(= (slew_time Star3 Star8) 71.87)
	(= (slew_time Star8 Star4) 33.72)
	(= (slew_time Star4 Star8) 33.72)
	(= (slew_time Star8 Star5) 9.619)
	(= (slew_time Star5 Star8) 9.619)
	(= (slew_time Star8 Star6) 27.43)
	(= (slew_time Star6 Star8) 27.43)
	(= (slew_time Star8 GroundStation7) 52.05)
	(= (slew_time GroundStation7 Star8) 52.05)
	(= (slew_time Star4 Star0) 22.68)
	(= (slew_time Star0 Star4) 22.68)
	(= (slew_time Star4 GroundStation1) 8.661)
	(= (slew_time GroundStation1 Star4) 8.661)
	(= (slew_time Star4 Star2) 41.52)
	(= (slew_time Star2 Star4) 41.52)
	(= (slew_time Star4 Star3) 74.38)
	(= (slew_time Star3 Star4) 74.38)
	(= (slew_time GroundStation9 Star0) 1.547)
	(= (slew_time Star0 GroundStation9) 1.547)
	(= (slew_time GroundStation9 GroundStation1) 46.29)
	(= (slew_time GroundStation1 GroundStation9) 46.29)
	(= (slew_time GroundStation9 Star2) 38.27)
	(= (slew_time Star2 GroundStation9) 38.27)
	(= (slew_time GroundStation9 Star3) 24.01)
	(= (slew_time Star3 GroundStation9) 24.01)
	(= (slew_time GroundStation9 Star4) 60.99)
	(= (slew_time Star4 GroundStation9) 60.99)
	(= (slew_time GroundStation9 Star5) 17.36)
	(= (slew_time Star5 GroundStation9) 17.36)
	(= (slew_time GroundStation9 Star6) 49.21)
	(= (slew_time Star6 GroundStation9) 49.21)
	(= (slew_time GroundStation9 GroundStation7) 46.79)
	(= (slew_time GroundStation7 GroundStation9) 46.79)
	(= (slew_time GroundStation9 Star8) 9.177)
	(= (slew_time Star8 GroundStation9) 9.177)
	(= (slew_time Star5 Star0) 18.5)
	(= (slew_time Star0 Star5) 18.5)
	(= (slew_time Star5 GroundStation1) 24.81)
	(= (slew_time GroundStation1 Star5) 24.81)
	(= (slew_time Star5 Star2) 37.35)
	(= (slew_time Star2 Star5) 37.35)
	(= (slew_time Star5 Star3) 14.02)
	(= (slew_time Star3 Star5) 14.02)
	(= (slew_time Star5 Star4) 20.24)
	(= (slew_time Star4 Star5) 20.24)
	(= (slew_time Phenomenon10 Star0) 19.78)
	(= (slew_time Star0 Phenomenon10) 19.78)
	(= (slew_time Phenomenon10 GroundStation1) 17.89)
	(= (slew_time GroundStation1 Phenomenon10) 17.89)
	(= (slew_time Phenomenon10 Star2) 40.86)
	(= (slew_time Star2 Phenomenon10) 40.86)
	(= (slew_time Phenomenon10 Star3) 4.511)
	(= (slew_time Star3 Phenomenon10) 4.511)
	(= (slew_time Phenomenon10 Star4) 78.91)
	(= (slew_time Star4 Phenomenon10) 78.91)
	(= (slew_time Phenomenon10 Star5) 35.68)
	(= (slew_time Star5 Phenomenon10) 35.68)
	(= (slew_time Phenomenon10 Star6) 54.01)
	(= (slew_time Star6 Phenomenon10) 54.01)
	(= (slew_time Phenomenon10 GroundStation7) 39)
	(= (slew_time GroundStation7 Phenomenon10) 39)
	(= (slew_time Phenomenon10 Star8) 60.25)
	(= (slew_time Star8 Phenomenon10) 60.25)
	(= (slew_time Phenomenon10 GroundStation9) 40.48)
	(= (slew_time GroundStation9 Phenomenon10) 40.48)
	(= (slew_time Phenomenon11 Star0) 32.28)
	(= (slew_time Star0 Phenomenon11) 32.28)
	(= (slew_time Phenomenon11 GroundStation1) 41.73)
	(= (slew_time GroundStation1 Phenomenon11) 41.73)
	(= (slew_time Phenomenon11 Star2) 11.29)
	(= (slew_time Star2 Phenomenon11) 11.29)
	(= (slew_time Phenomenon11 Star3) 2.163)
	(= (slew_time Star3 Phenomenon11) 2.163)
	(= (slew_time Phenomenon11 Star4) 32.3)
	(= (slew_time Star4 Phenomenon11) 32.3)
	(= (slew_time Phenomenon11 Star5) 37.32)
	(= (slew_time Star5 Phenomenon11) 37.32)
	(= (slew_time Phenomenon11 Star6) 1.81)
	(= (slew_time Star6 Phenomenon11) 1.81)
	(= (slew_time Phenomenon11 GroundStation7) 61.23)
	(= (slew_time GroundStation7 Phenomenon11) 61.23)
	(= (slew_time Phenomenon11 Star8) 5.603)
	(= (slew_time Star8 Phenomenon11) 5.603)
	(= (slew_time Phenomenon11 GroundStation9) 43.04)
	(= (slew_time GroundStation9 Phenomenon11) 43.04)
	(= (slew_time Phenomenon11 Phenomenon10) 81.82)
	(= (slew_time Phenomenon10 Phenomenon11) 81.82)
	(= (data-stored) 0)
	(= (fuel-used) 0)
)
(:goal (and
	(pointing satellite0 Star6)
	(pointing satellite9 Star5)
))
(:metric minimize (fuel-used))

)
