(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite4 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite5 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite6 - satellite
	instrument43 - instrument
	instrument44 - instrument
	satellite7 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite8 - satellite
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	satellite9 - satellite
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	thermograph0 - mode
	image2 - mode
	thermograph4 - mode
	spectrograph1 - mode
	spectrograph3 - mode
	GroundStation4 - direction
	Star2 - direction
	GroundStation1 - direction
	Star7 - direction
	Star9 - direction
	Star0 - direction
	GroundStation8 - direction
	GroundStation5 - direction
	Star3 - direction
	Star6 - direction
	Star10 - direction
	Planet11 - direction
)
(:init
	(supports instrument0 spectrograph3)
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 Star9)
	(supports instrument1 image2)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 Star2)
	(supports instrument2 thermograph0)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star6)
	(supports instrument3 spectrograph3)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star6)
	(calibration_target instrument3 GroundStation8)
	(supports instrument4 image2)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star3)
	(supports instrument5 image2)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 Star2)
	(supports instrument6 image2)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 Star9)
	(supports instrument7 spectrograph3)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 Star7)
	(supports instrument8 image2)
	(supports instrument8 spectrograph3)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star10)
	(= (data_capacity satellite0) 1000)
	(= (fuel satellite0) 164)
	(supports instrument9 spectrograph1)
	(supports instrument9 thermograph4)
	(supports instrument9 spectrograph3)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 spectrograph3)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star3)
	(supports instrument11 image2)
	(supports instrument11 spectrograph3)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation8)
	(supports instrument12 spectrograph3)
	(supports instrument12 thermograph0)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 Star6)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star10)
	(= (data_capacity satellite1) 1000)
	(= (fuel satellite1) 143)
	(supports instrument13 spectrograph3)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star7)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 GroundStation8)
	(supports instrument15 spectrograph1)
	(supports instrument15 spectrograph3)
	(supports instrument15 image2)
	(calibration_target instrument15 Star2)
	(supports instrument16 spectrograph3)
	(supports instrument16 thermograph0)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 Star7)
	(calibration_target instrument16 Star9)
	(calibration_target instrument16 Star6)
	(supports instrument17 spectrograph3)
	(supports instrument17 spectrograph1)
	(supports instrument17 image2)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 GroundStation8)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 GroundStation4)
	(supports instrument19 thermograph4)
	(supports instrument19 image2)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star7)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(= (data_capacity satellite2) 1000)
	(= (fuel satellite2) 122)
	(supports instrument20 spectrograph1)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 Star9)
	(calibration_target instrument20 Star3)
	(supports instrument21 spectrograph3)
	(calibration_target instrument21 Star9)
	(supports instrument22 thermograph4)
	(supports instrument22 spectrograph3)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 GroundStation8)
	(supports instrument23 thermograph0)
	(supports instrument23 image2)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star9)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 spectrograph1)
	(supports instrument24 thermograph4)
	(calibration_target instrument24 Star6)
	(supports instrument25 thermograph0)
	(supports instrument25 spectrograph3)
	(supports instrument25 image2)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 Star6)
	(calibration_target instrument25 GroundStation8)
	(supports instrument26 thermograph4)
	(supports instrument26 image2)
	(calibration_target instrument26 Star9)
	(calibration_target instrument26 GroundStation8)
	(supports instrument27 thermograph0)
	(supports instrument27 image2)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 GroundStation4)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(= (data_capacity satellite3) 1000)
	(= (fuel satellite3) 116)
	(supports instrument28 spectrograph3)
	(supports instrument28 image2)
	(supports instrument28 spectrograph1)
	(calibration_target instrument28 GroundStation1)
	(calibration_target instrument28 Star6)
	(supports instrument29 image2)
	(supports instrument29 thermograph4)
	(supports instrument29 spectrograph3)
	(calibration_target instrument29 GroundStation4)
	(calibration_target instrument29 Star9)
	(supports instrument30 spectrograph1)
	(supports instrument30 thermograph0)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 Star3)
	(calibration_target instrument30 Star7)
	(supports instrument31 thermograph4)
	(supports instrument31 thermograph0)
	(supports instrument31 spectrograph3)
	(calibration_target instrument31 GroundStation4)
	(calibration_target instrument31 Star7)
	(supports instrument32 spectrograph3)
	(calibration_target instrument32 Star7)
	(calibration_target instrument32 Star0)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 GroundStation4)
	(calibration_target instrument33 Star6)
	(supports instrument34 image2)
	(supports instrument34 thermograph0)
	(calibration_target instrument34 GroundStation1)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star9)
	(= (data_capacity satellite4) 1000)
	(= (fuel satellite4) 119)
	(supports instrument35 image2)
	(calibration_target instrument35 Star3)
	(calibration_target instrument35 Star2)
	(calibration_target instrument35 GroundStation5)
	(supports instrument36 spectrograph1)
	(supports instrument36 thermograph0)
	(supports instrument36 spectrograph3)
	(calibration_target instrument36 Star0)
	(calibration_target instrument36 GroundStation5)
	(supports instrument37 thermograph0)
	(calibration_target instrument37 GroundStation4)
	(calibration_target instrument37 Star9)
	(supports instrument38 image2)
	(supports instrument38 thermograph4)
	(supports instrument38 spectrograph3)
	(calibration_target instrument38 GroundStation4)
	(supports instrument39 spectrograph3)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 Star0)
	(calibration_target instrument39 GroundStation5)
	(supports instrument40 image2)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 GroundStation8)
	(calibration_target instrument40 GroundStation4)
	(supports instrument41 thermograph0)
	(calibration_target instrument41 Star9)
	(calibration_target instrument41 Star0)
	(supports instrument42 image2)
	(calibration_target instrument42 Star3)
	(calibration_target instrument42 GroundStation4)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star6)
	(= (data_capacity satellite5) 1000)
	(= (fuel satellite5) 197)
	(supports instrument43 image2)
	(supports instrument43 thermograph0)
	(supports instrument43 spectrograph3)
	(calibration_target instrument43 GroundStation4)
	(calibration_target instrument43 GroundStation8)
	(calibration_target instrument43 Star2)
	(supports instrument44 spectrograph1)
	(calibration_target instrument44 GroundStation4)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star9)
	(= (data_capacity satellite6) 1000)
	(= (fuel satellite6) 179)
	(supports instrument45 thermograph4)
	(supports instrument45 spectrograph1)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 GroundStation1)
	(supports instrument46 spectrograph3)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 spectrograph3)
	(calibration_target instrument47 Star9)
	(calibration_target instrument47 Star3)
	(calibration_target instrument47 Star0)
	(supports instrument48 spectrograph1)
	(calibration_target instrument48 GroundStation4)
	(supports instrument49 thermograph4)
	(supports instrument49 image2)
	(calibration_target instrument49 GroundStation1)
	(calibration_target instrument49 Star6)
	(supports instrument50 spectrograph1)
	(supports instrument50 image2)
	(calibration_target instrument50 Star3)
	(calibration_target instrument50 GroundStation4)
	(calibration_target instrument50 GroundStation5)
	(supports instrument51 image2)
	(supports instrument51 thermograph4)
	(calibration_target instrument51 Star7)
	(calibration_target instrument51 GroundStation5)
	(calibration_target instrument51 Star6)
	(supports instrument52 spectrograph3)
	(supports instrument52 thermograph4)
	(supports instrument52 thermograph0)
	(calibration_target instrument52 GroundStation5)
	(calibration_target instrument52 GroundStation1)
	(calibration_target instrument52 Star9)
	(supports instrument53 thermograph0)
	(supports instrument53 image2)
	(calibration_target instrument53 Star2)
	(supports instrument54 image2)
	(supports instrument54 thermograph0)
	(calibration_target instrument54 GroundStation8)
	(calibration_target instrument54 Star7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation1)
	(= (data_capacity satellite7) 1000)
	(= (fuel satellite7) 192)
	(supports instrument55 thermograph4)
	(calibration_target instrument55 GroundStation8)
	(calibration_target instrument55 Star0)
	(calibration_target instrument55 Star9)
	(supports instrument56 spectrograph3)
	(calibration_target instrument56 GroundStation5)
	(calibration_target instrument56 Star2)
	(calibration_target instrument56 GroundStation8)
	(supports instrument57 image2)
	(supports instrument57 thermograph4)
	(calibration_target instrument57 GroundStation8)
	(calibration_target instrument57 Star9)
	(calibration_target instrument57 GroundStation1)
	(supports instrument58 thermograph4)
	(supports instrument58 thermograph0)
	(calibration_target instrument58 GroundStation8)
	(calibration_target instrument58 Star7)
	(supports instrument59 thermograph0)
	(supports instrument59 thermograph4)
	(supports instrument59 spectrograph1)
	(calibration_target instrument59 Star6)
	(calibration_target instrument59 Star3)
	(calibration_target instrument59 GroundStation5)
	(supports instrument60 thermograph4)
	(supports instrument60 image2)
	(supports instrument60 spectrograph3)
	(calibration_target instrument60 Star0)
	(supports instrument61 image2)
	(supports instrument61 spectrograph3)
	(supports instrument61 thermograph4)
	(calibration_target instrument61 Star0)
	(supports instrument62 thermograph0)
	(supports instrument62 spectrograph3)
	(supports instrument62 spectrograph1)
	(calibration_target instrument62 Star3)
	(calibration_target instrument62 Star0)
	(calibration_target instrument62 Star9)
	(supports instrument63 spectrograph1)
	(supports instrument63 thermograph0)
	(supports instrument63 spectrograph3)
	(calibration_target instrument63 Star6)
	(calibration_target instrument63 GroundStation8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(on_board instrument61 satellite8)
	(on_board instrument62 satellite8)
	(on_board instrument63 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation8)
	(= (data_capacity satellite8) 1000)
	(= (fuel satellite8) 158)
	(supports instrument64 thermograph4)
	(calibration_target instrument64 Star6)
	(supports instrument65 spectrograph1)
	(supports instrument65 thermograph4)
	(calibration_target instrument65 GroundStation5)
	(calibration_target instrument65 GroundStation8)
	(supports instrument66 image2)
	(calibration_target instrument66 Star3)
	(supports instrument67 spectrograph3)
	(supports instrument67 spectrograph1)
	(supports instrument67 thermograph4)
	(calibration_target instrument67 Star6)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star7)
	(= (data_capacity satellite9) 1000)
	(= (fuel satellite9) 182)
	(= (data Star10 thermograph0) 217)
	(= (data Planet11 thermograph0) 286)
	(= (data Star10 image2) 199)
	(= (data Planet11 image2) 251)
	(= (data Star10 thermograph4) 76)
	(= (data Planet11 thermograph4) 263)
	(= (data Star10 spectrograph1) 46)
	(= (data Planet11 spectrograph1) 188)
	(= (data Star10 spectrograph3) 34)
	(= (data Planet11 spectrograph3) 19)
	(= (slew_time GroundStation4 Star0) 61.72)
	(= (slew_time Star0 GroundStation4) 61.72)
	(= (slew_time GroundStation4 GroundStation1) 44.22)
	(= (slew_time GroundStation1 GroundStation4) 44.22)
	(= (slew_time GroundStation4 Star2) 2.528)
	(= (slew_time Star2 GroundStation4) 2.528)
	(= (slew_time GroundStation4 Star3) 36.6)
	(= (slew_time Star3 GroundStation4) 36.6)
	(= (slew_time Star2 Star0) 32.89)
	(= (slew_time Star0 Star2) 32.89)
	(= (slew_time Star2 GroundStation1) 13.35)
	(= (slew_time GroundStation1 Star2) 13.35)
	(= (slew_time GroundStation1 Star0) 22.76)
	(= (slew_time Star0 GroundStation1) 22.76)
	(= (slew_time Star7 Star0) 51.94)
	(= (slew_time Star0 Star7) 51.94)
	(= (slew_time Star7 GroundStation1) 65.57)
	(= (slew_time GroundStation1 Star7) 65.57)
	(= (slew_time Star7 Star2) 4.047)
	(= (slew_time Star2 Star7) 4.047)
	(= (slew_time Star7 Star3) 14.27)
	(= (slew_time Star3 Star7) 14.27)
	(= (slew_time Star7 GroundStation4) 10.19)
	(= (slew_time GroundStation4 Star7) 10.19)
	(= (slew_time Star7 GroundStation5) 51.69)
	(= (slew_time GroundStation5 Star7) 51.69)
	(= (slew_time Star7 Star6) 0.3192)
	(= (slew_time Star6 Star7) 0.3192)
	(= (slew_time Star9 Star0) 23.31)
	(= (slew_time Star0 Star9) 23.31)
	(= (slew_time Star9 GroundStation1) 14.44)
	(= (slew_time GroundStation1 Star9) 14.44)
	(= (slew_time Star9 Star2) 78.16)
	(= (slew_time Star2 Star9) 78.16)
	(= (slew_time Star9 Star3) 33.46)
	(= (slew_time Star3 Star9) 33.46)
	(= (slew_time Star9 GroundStation4) 46.6)
	(= (slew_time GroundStation4 Star9) 46.6)
	(= (slew_time Star9 GroundStation5) 30.3)
	(= (slew_time GroundStation5 Star9) 30.3)
	(= (slew_time Star9 Star6) 21.42)
	(= (slew_time Star6 Star9) 21.42)
	(= (slew_time Star9 Star7) 9.127)
	(= (slew_time Star7 Star9) 9.127)
	(= (slew_time Star9 GroundStation8) 26.28)
	(= (slew_time GroundStation8 Star9) 26.28)
	(= (slew_time GroundStation8 Star0) 37.16)
	(= (slew_time Star0 GroundStation8) 37.16)
	(= (slew_time GroundStation8 GroundStation1) 14.21)
	(= (slew_time GroundStation1 GroundStation8) 14.21)
	(= (slew_time GroundStation8 Star2) 4.502)
	(= (slew_time Star2 GroundStation8) 4.502)
	(= (slew_time GroundStation8 Star3) 21.23)
	(= (slew_time Star3 GroundStation8) 21.23)
	(= (slew_time GroundStation8 GroundStation4) 32.6)
	(= (slew_time GroundStation4 GroundStation8) 32.6)
	(= (slew_time GroundStation8 GroundStation5) 19.64)
	(= (slew_time GroundStation5 GroundStation8) 19.64)
	(= (slew_time GroundStation8 Star6) 14.65)
	(= (slew_time Star6 GroundStation8) 14.65)
	(= (slew_time GroundStation8 Star7) 36.05)
	(= (slew_time Star7 GroundStation8) 36.05)
	(= (slew_time GroundStation5 Star0) 18.25)
	(= (slew_time Star0 GroundStation5) 18.25)
	(= (slew_time GroundStation5 GroundStation1) 10.41)
	(= (slew_time GroundStation1 GroundStation5) 10.41)
	(= (slew_time GroundStation5 Star2) 72.53)
	(= (slew_time Star2 GroundStation5) 72.53)
	(= (slew_time GroundStation5 Star3) 58.26)
	(= (slew_time Star3 GroundStation5) 58.26)
	(= (slew_time GroundStation5 GroundStation4) 36.84)
	(= (slew_time GroundStation4 GroundStation5) 36.84)
	(= (slew_time Star3 Star0) 14.8)
	(= (slew_time Star0 Star3) 14.8)
	(= (slew_time Star3 GroundStation1) 59.64)
	(= (slew_time GroundStation1 Star3) 59.64)
	(= (slew_time Star3 Star2) 15.33)
	(= (slew_time Star2 Star3) 15.33)
	(= (slew_time Star6 Star0) 54.13)
	(= (slew_time Star0 Star6) 54.13)
	(= (slew_time Star6 GroundStation1) 37.18)
	(= (slew_time GroundStation1 Star6) 37.18)
	(= (slew_time Star6 Star2) 27.02)
	(= (slew_time Star2 Star6) 27.02)
	(= (slew_time Star6 Star3) 27.85)
	(= (slew_time Star3 Star6) 27.85)
	(= (slew_time Star6 GroundStation4) 3.464)
	(= (slew_time GroundStation4 Star6) 3.464)
	(= (slew_time Star6 GroundStation5) 3.841)
	(= (slew_time GroundStation5 Star6) 3.841)
	(= (slew_time Star10 Star0) 22.33)
	(= (slew_time Star0 Star10) 22.33)
	(= (slew_time Star10 GroundStation1) 6.894)
	(= (slew_time GroundStation1 Star10) 6.894)
	(= (slew_time Star10 Star2) 32.46)
	(= (slew_time Star2 Star10) 32.46)
	(= (slew_time Star10 Star3) 39.4)
	(= (slew_time Star3 Star10) 39.4)
	(= (slew_time Star10 GroundStation4) 28.55)
	(= (slew_time GroundStation4 Star10) 28.55)
	(= (slew_time Star10 GroundStation5) 1.282)
	(= (slew_time GroundStation5 Star10) 1.282)
	(= (slew_time Star10 Star6) 73.34)
	(= (slew_time Star6 Star10) 73.34)
	(= (slew_time Star10 Star7) 18.15)
	(= (slew_time Star7 Star10) 18.15)
	(= (slew_time Star10 GroundStation8) 62.91)
	(= (slew_time GroundStation8 Star10) 62.91)
	(= (slew_time Star10 Star9) 20.62)
	(= (slew_time Star9 Star10) 20.62)
	(= (slew_time Planet11 Star0) 27.01)
	(= (slew_time Star0 Planet11) 27.01)
	(= (slew_time Planet11 GroundStation1) 54.85)
	(= (slew_time GroundStation1 Planet11) 54.85)
	(= (slew_time Planet11 Star2) 3.744)
	(= (slew_time Star2 Planet11) 3.744)
	(= (slew_time Planet11 Star3) 55.47)
	(= (slew_time Star3 Planet11) 55.47)
	(= (slew_time Planet11 GroundStation4) 4.516)
	(= (slew_time GroundStation4 Planet11) 4.516)
	(= (slew_time Planet11 GroundStation5) 45.05)
	(= (slew_time GroundStation5 Planet11) 45.05)
	(= (slew_time Planet11 Star6) 9.645)
	(= (slew_time Star6 Planet11) 9.645)
	(= (slew_time Planet11 Star7) 34.53)
	(= (slew_time Star7 Planet11) 34.53)
	(= (slew_time Planet11 GroundStation8) 23.2)
	(= (slew_time GroundStation8 Planet11) 23.2)
	(= (slew_time Planet11 Star9) 61.99)
	(= (slew_time Star9 Planet11) 61.99)
	(= (slew_time Planet11 Star10) 59.84)
	(= (slew_time Star10 Planet11) 59.84)
	(= (data-stored) 0)
	(= (fuel-used) 0)
)
(:goal (and
	(pointing satellite4 Star6)
	(pointing satellite5 Star2)
	(pointing satellite9 Star3)
	(have_image Star10 thermograph0)
	(have_image Planet11 spectrograph1)
))
(:metric minimize (fuel-used))

)
