(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	satellite5 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite6 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite7 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite8 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	satellite9 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	image3 - mode
	spectrograph2 - mode
	infrared0 - mode
	spectrograph1 - mode
	spectrograph4 - mode
	GroundStation14 - direction
	GroundStation15 - direction
	GroundStation4 - direction
	GroundStation1 - direction
	GroundStation6 - direction
	Star8 - direction
	Star3 - direction
	Star7 - direction
	GroundStation13 - direction
	Star5 - direction
	Star0 - direction
	GroundStation9 - direction
	GroundStation12 - direction
	GroundStation2 - direction
	GroundStation10 - direction
	GroundStation11 - direction
	Star16 - direction
	GroundStation17 - direction
	Phenomenon18 - direction
	Phenomenon19 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 spectrograph4)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star16)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation14)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 GroundStation13)
	(supports instrument1 spectrograph4)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 GroundStation14)
	(calibration_target instrument1 Star8)
	(supports instrument2 spectrograph2)
	(supports instrument2 infrared0)
	(supports instrument2 image3)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation9)
	(calibration_target instrument2 GroundStation11)
	(supports instrument3 image3)
	(calibration_target instrument3 GroundStation9)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation6)
	(supports instrument4 image3)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star7)
	(supports instrument5 infrared0)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 GroundStation14)
	(calibration_target instrument5 GroundStation10)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 Star8)
	(supports instrument6 infrared0)
	(supports instrument6 spectrograph4)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 GroundStation17)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star7)
	(supports instrument8 spectrograph1)
	(supports instrument8 infrared0)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 GroundStation11)
	(supports instrument9 spectrograph1)
	(supports instrument9 spectrograph4)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 GroundStation10)
	(calibration_target instrument9 GroundStation1)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 GroundStation14)
	(calibration_target instrument9 Star7)
	(supports instrument10 image3)
	(calibration_target instrument10 GroundStation15)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star16)
	(supports instrument11 image3)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 spectrograph4)
	(supports instrument12 infrared0)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 GroundStation13)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 Star5)
	(calibration_target instrument12 GroundStation2)
	(supports instrument13 spectrograph2)
	(supports instrument13 spectrograph4)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 GroundStation9)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 Star7)
	(supports instrument14 image3)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 GroundStation17)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 GroundStation6)
	(calibration_target instrument15 Star16)
	(calibration_target instrument15 GroundStation17)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 spectrograph4)
	(supports instrument16 spectrograph1)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 GroundStation9)
	(calibration_target instrument16 GroundStation15)
	(calibration_target instrument16 Star16)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 GroundStation12)
	(calibration_target instrument16 GroundStation17)
	(supports instrument17 spectrograph1)
	(supports instrument17 spectrograph2)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation11)
	(calibration_target instrument17 GroundStation17)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 GroundStation13)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 GroundStation15)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation2)
	(supports instrument19 spectrograph4)
	(calibration_target instrument19 GroundStation11)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 GroundStation9)
	(calibration_target instrument19 GroundStation6)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation9)
	(supports instrument20 spectrograph1)
	(supports instrument20 spectrograph4)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation17)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 GroundStation15)
	(calibration_target instrument20 GroundStation14)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 GroundStation2)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star5)
	(supports instrument21 spectrograph1)
	(supports instrument21 spectrograph2)
	(supports instrument21 image3)
	(calibration_target instrument21 Star7)
	(calibration_target instrument21 GroundStation11)
	(calibration_target instrument21 Star5)
	(supports instrument22 spectrograph1)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star7)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation12)
	(supports instrument23 spectrograph2)
	(supports instrument23 spectrograph4)
	(supports instrument23 infrared0)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 GroundStation12)
	(supports instrument24 spectrograph4)
	(supports instrument24 spectrograph1)
	(calibration_target instrument24 GroundStation13)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 GroundStation17)
	(calibration_target instrument24 GroundStation10)
	(supports instrument25 image3)
	(calibration_target instrument25 GroundStation14)
	(calibration_target instrument25 GroundStation11)
	(calibration_target instrument25 GroundStation10)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation1)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star7)
	(supports instrument27 spectrograph2)
	(calibration_target instrument27 GroundStation11)
	(calibration_target instrument27 GroundStation13)
	(calibration_target instrument27 GroundStation6)
	(calibration_target instrument27 GroundStation17)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 GroundStation14)
	(supports instrument28 spectrograph4)
	(calibration_target instrument28 GroundStation14)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 Star7)
	(supports instrument29 spectrograph4)
	(supports instrument29 image3)
	(supports instrument29 spectrograph2)
	(calibration_target instrument29 Star7)
	(calibration_target instrument29 GroundStation6)
	(calibration_target instrument29 GroundStation9)
	(calibration_target instrument29 GroundStation14)
	(calibration_target instrument29 GroundStation17)
	(calibration_target instrument29 Star8)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation15)
	(supports instrument30 spectrograph1)
	(supports instrument30 image3)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 GroundStation14)
	(calibration_target instrument30 GroundStation12)
	(supports instrument31 infrared0)
	(calibration_target instrument31 Star0)
	(calibration_target instrument31 Star16)
	(calibration_target instrument31 GroundStation17)
	(calibration_target instrument31 Star3)
	(calibration_target instrument31 GroundStation12)
	(calibration_target instrument31 Star7)
	(supports instrument32 spectrograph2)
	(supports instrument32 spectrograph1)
	(supports instrument32 spectrograph4)
	(calibration_target instrument32 GroundStation11)
	(calibration_target instrument32 GroundStation13)
	(supports instrument33 image3)
	(supports instrument33 spectrograph1)
	(supports instrument33 spectrograph2)
	(calibration_target instrument33 Star16)
	(supports instrument34 image3)
	(calibration_target instrument34 GroundStation4)
	(calibration_target instrument34 GroundStation13)
	(calibration_target instrument34 GroundStation6)
	(calibration_target instrument34 GroundStation14)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 GroundStation10)
	(supports instrument35 spectrograph1)
	(supports instrument35 image3)
	(calibration_target instrument35 GroundStation1)
	(calibration_target instrument35 Star5)
	(calibration_target instrument35 GroundStation15)
	(calibration_target instrument35 GroundStation13)
	(calibration_target instrument35 GroundStation4)
	(supports instrument36 image3)
	(supports instrument36 infrared0)
	(calibration_target instrument36 Star16)
	(calibration_target instrument36 GroundStation17)
	(supports instrument37 image3)
	(supports instrument37 spectrograph4)
	(supports instrument37 spectrograph2)
	(calibration_target instrument37 GroundStation11)
	(calibration_target instrument37 Star16)
	(calibration_target instrument37 GroundStation17)
	(calibration_target instrument37 GroundStation6)
	(supports instrument38 spectrograph2)
	(supports instrument38 infrared0)
	(supports instrument38 spectrograph4)
	(calibration_target instrument38 Star8)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation2)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation1)
	(supports instrument39 spectrograph2)
	(supports instrument39 spectrograph4)
	(supports instrument39 infrared0)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 Star16)
	(calibration_target instrument39 GroundStation13)
	(supports instrument40 infrared0)
	(calibration_target instrument40 GroundStation11)
	(calibration_target instrument40 GroundStation13)
	(calibration_target instrument40 GroundStation1)
	(calibration_target instrument40 GroundStation12)
	(calibration_target instrument40 Star16)
	(calibration_target instrument40 GroundStation9)
	(supports instrument41 spectrograph4)
	(supports instrument41 infrared0)
	(calibration_target instrument41 Star0)
	(calibration_target instrument41 Star7)
	(calibration_target instrument41 Star8)
	(calibration_target instrument41 GroundStation12)
	(calibration_target instrument41 GroundStation6)
	(supports instrument42 spectrograph2)
	(supports instrument42 infrared0)
	(calibration_target instrument42 GroundStation9)
	(calibration_target instrument42 Star5)
	(calibration_target instrument42 GroundStation12)
	(calibration_target instrument42 Star0)
	(calibration_target instrument42 GroundStation2)
	(calibration_target instrument42 GroundStation11)
	(supports instrument43 spectrograph2)
	(supports instrument43 image3)
	(calibration_target instrument43 Star7)
	(calibration_target instrument43 Star16)
	(calibration_target instrument43 Star3)
	(calibration_target instrument43 GroundStation17)
	(supports instrument44 image3)
	(supports instrument44 spectrograph4)
	(calibration_target instrument44 GroundStation13)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star5)
	(supports instrument45 infrared0)
	(supports instrument45 spectrograph4)
	(supports instrument45 spectrograph1)
	(calibration_target instrument45 Star5)
	(calibration_target instrument45 GroundStation17)
	(calibration_target instrument45 Star0)
	(calibration_target instrument45 GroundStation13)
	(supports instrument46 spectrograph1)
	(supports instrument46 infrared0)
	(calibration_target instrument46 GroundStation11)
	(calibration_target instrument46 GroundStation12)
	(calibration_target instrument46 GroundStation9)
	(calibration_target instrument46 Star0)
	(calibration_target instrument46 GroundStation2)
	(supports instrument47 image3)
	(calibration_target instrument47 GroundStation2)
	(supports instrument48 infrared0)
	(supports instrument48 spectrograph2)
	(calibration_target instrument48 GroundStation10)
	(supports instrument49 spectrograph4)
	(supports instrument49 spectrograph1)
	(supports instrument49 infrared0)
	(calibration_target instrument49 GroundStation17)
	(calibration_target instrument49 Star16)
	(calibration_target instrument49 GroundStation11)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon19)
)
(:goal (and
	(pointing satellite2 GroundStation14)
	(pointing satellite5 Star0)
	(have_image Phenomenon18 spectrograph4)
	(have_image Phenomenon19 spectrograph1)
))

)
