(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite5 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite6 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite7 - satellite
	instrument41 - instrument
	instrument42 - instrument
	satellite8 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite9 - satellite
	instrument48 - instrument
	infrared0 - mode
	spectrograph3 - mode
	image2 - mode
	infrared1 - mode
	thermograph4 - mode
	GroundStation4 - direction
	GroundStation14 - direction
	Star11 - direction
	Star3 - direction
	GroundStation9 - direction
	GroundStation17 - direction
	Star6 - direction
	Star2 - direction
	GroundStation12 - direction
	Star7 - direction
	Star13 - direction
	GroundStation15 - direction
	GroundStation10 - direction
	Star0 - direction
	Star8 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation16 - direction
	Star18 - direction
	Star19 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 image2)
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation5)
	(supports instrument1 infrared1)
	(supports instrument1 spectrograph3)
	(calibration_target instrument1 GroundStation9)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 GroundStation16)
	(calibration_target instrument1 Star1)
	(supports instrument2 thermograph4)
	(supports instrument2 image2)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 Star7)
	(calibration_target instrument2 GroundStation5)
	(supports instrument3 image2)
	(supports instrument3 infrared1)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star11)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 GroundStation9)
	(supports instrument4 infrared1)
	(supports instrument4 spectrograph3)
	(supports instrument4 image2)
	(calibration_target instrument4 GroundStation17)
	(supports instrument5 thermograph4)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation15)
	(supports instrument6 infrared0)
	(calibration_target instrument6 Star13)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 GroundStation10)
	(supports instrument7 infrared0)
	(calibration_target instrument7 Star13)
	(calibration_target instrument7 Star2)
	(calibration_target instrument7 GroundStation17)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 Star13)
	(supports instrument9 infrared1)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 GroundStation14)
	(calibration_target instrument9 Star7)
	(supports instrument10 image2)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star11)
	(calibration_target instrument10 Star2)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 GroundStation9)
	(calibration_target instrument11 Star11)
	(calibration_target instrument11 GroundStation12)
	(calibration_target instrument11 GroundStation17)
	(supports instrument12 infrared0)
	(supports instrument12 infrared1)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 GroundStation9)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument13 image2)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 GroundStation12)
	(calibration_target instrument13 GroundStation15)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 Star8)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 GroundStation12)
	(calibration_target instrument14 GroundStation16)
	(calibration_target instrument14 GroundStation10)
	(calibration_target instrument14 Star6)
	(supports instrument15 infrared0)
	(supports instrument15 image2)
	(supports instrument15 spectrograph3)
	(calibration_target instrument15 Star13)
	(calibration_target instrument15 GroundStation9)
	(calibration_target instrument15 GroundStation16)
	(calibration_target instrument15 GroundStation15)
	(supports instrument16 spectrograph3)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 Star6)
	(calibration_target instrument16 GroundStation12)
	(calibration_target instrument16 Star1)
	(supports instrument17 spectrograph3)
	(supports instrument17 thermograph4)
	(supports instrument17 infrared1)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 spectrograph3)
	(supports instrument18 infrared0)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 Star1)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation12)
	(supports instrument19 image2)
	(supports instrument19 spectrograph3)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 GroundStation9)
	(calibration_target instrument19 GroundStation17)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star13)
	(supports instrument20 thermograph4)
	(supports instrument20 infrared0)
	(calibration_target instrument20 Star13)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 Star6)
	(calibration_target instrument20 GroundStation14)
	(calibration_target instrument20 GroundStation17)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation12)
	(calibration_target instrument21 Star0)
	(calibration_target instrument21 Star3)
	(calibration_target instrument21 GroundStation15)
	(supports instrument22 thermograph4)
	(supports instrument22 infrared0)
	(calibration_target instrument22 GroundStation10)
	(calibration_target instrument22 Star2)
	(supports instrument23 infrared1)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star11)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 GroundStation9)
	(calibration_target instrument23 Star13)
	(supports instrument24 infrared1)
	(supports instrument24 thermograph4)
	(supports instrument24 spectrograph3)
	(calibration_target instrument24 GroundStation16)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation14)
	(supports instrument25 image2)
	(calibration_target instrument25 GroundStation10)
	(calibration_target instrument25 GroundStation12)
	(supports instrument26 spectrograph3)
	(supports instrument26 image2)
	(calibration_target instrument26 GroundStation12)
	(calibration_target instrument26 GroundStation10)
	(calibration_target instrument26 Star13)
	(calibration_target instrument26 Star7)
	(calibration_target instrument26 GroundStation14)
	(calibration_target instrument26 Star0)
	(supports instrument27 image2)
	(supports instrument27 spectrograph3)
	(supports instrument27 infrared0)
	(calibration_target instrument27 GroundStation17)
	(supports instrument28 infrared0)
	(supports instrument28 spectrograph3)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation5)
	(supports instrument29 spectrograph3)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 Star11)
	(calibration_target instrument29 GroundStation9)
	(supports instrument30 spectrograph3)
	(supports instrument30 thermograph4)
	(supports instrument30 infrared1)
	(calibration_target instrument30 Star8)
	(supports instrument31 spectrograph3)
	(calibration_target instrument31 Star3)
	(calibration_target instrument31 GroundStation9)
	(calibration_target instrument31 Star11)
	(calibration_target instrument31 GroundStation12)
	(supports instrument32 infrared1)
	(supports instrument32 image2)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 Star0)
	(calibration_target instrument32 GroundStation16)
	(calibration_target instrument32 GroundStation12)
	(calibration_target instrument32 GroundStation15)
	(calibration_target instrument32 GroundStation5)
	(supports instrument33 image2)
	(supports instrument33 infrared0)
	(supports instrument33 spectrograph3)
	(calibration_target instrument33 Star0)
	(calibration_target instrument33 Star7)
	(calibration_target instrument33 Star6)
	(calibration_target instrument33 GroundStation5)
	(calibration_target instrument33 Star2)
	(supports instrument34 spectrograph3)
	(supports instrument34 infrared1)
	(supports instrument34 image2)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 GroundStation4)
	(calibration_target instrument34 GroundStation9)
	(calibration_target instrument34 GroundStation14)
	(calibration_target instrument34 Star2)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation12)
	(supports instrument35 infrared0)
	(calibration_target instrument35 Star11)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 GroundStation15)
	(calibration_target instrument35 Star7)
	(calibration_target instrument35 GroundStation4)
	(calibration_target instrument35 GroundStation5)
	(supports instrument36 infrared1)
	(supports instrument36 thermograph4)
	(calibration_target instrument36 Star1)
	(supports instrument37 spectrograph3)
	(calibration_target instrument37 GroundStation12)
	(calibration_target instrument37 GroundStation5)
	(calibration_target instrument37 Star8)
	(calibration_target instrument37 GroundStation9)
	(calibration_target instrument37 GroundStation14)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star11)
	(supports instrument38 spectrograph3)
	(calibration_target instrument38 GroundStation17)
	(calibration_target instrument38 Star8)
	(calibration_target instrument38 GroundStation12)
	(calibration_target instrument38 Star11)
	(supports instrument39 image2)
	(calibration_target instrument39 GroundStation15)
	(calibration_target instrument39 GroundStation9)
	(calibration_target instrument39 Star13)
	(calibration_target instrument39 GroundStation10)
	(calibration_target instrument39 Star2)
	(supports instrument40 infrared0)
	(supports instrument40 spectrograph3)
	(supports instrument40 image2)
	(calibration_target instrument40 Star11)
	(calibration_target instrument40 GroundStation15)
	(calibration_target instrument40 GroundStation10)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 GroundStation5)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation14)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 GroundStation12)
	(calibration_target instrument41 GroundStation9)
	(supports instrument42 infrared0)
	(calibration_target instrument42 Star6)
	(calibration_target instrument42 Star8)
	(calibration_target instrument42 GroundStation16)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation12)
	(supports instrument43 spectrograph3)
	(supports instrument43 infrared0)
	(supports instrument43 thermograph4)
	(calibration_target instrument43 Star13)
	(calibration_target instrument43 Star3)
	(supports instrument44 infrared0)
	(calibration_target instrument44 Star8)
	(calibration_target instrument44 GroundStation12)
	(calibration_target instrument44 Star2)
	(calibration_target instrument44 Star6)
	(calibration_target instrument44 GroundStation17)
	(calibration_target instrument44 GroundStation9)
	(supports instrument45 infrared0)
	(supports instrument45 image2)
	(supports instrument45 thermograph4)
	(calibration_target instrument45 GroundStation10)
	(calibration_target instrument45 Star8)
	(calibration_target instrument45 Star7)
	(supports instrument46 spectrograph3)
	(calibration_target instrument46 Star13)
	(supports instrument47 infrared1)
	(calibration_target instrument47 Star1)
	(calibration_target instrument47 Star8)
	(calibration_target instrument47 Star0)
	(calibration_target instrument47 GroundStation10)
	(calibration_target instrument47 GroundStation15)
	(calibration_target instrument47 Star13)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation17)
	(supports instrument48 thermograph4)
	(supports instrument48 infrared1)
	(supports instrument48 image2)
	(calibration_target instrument48 GroundStation16)
	(calibration_target instrument48 GroundStation5)
	(on_board instrument48 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star6)
)
(:goal (and
	(pointing satellite1 GroundStation16)
	(pointing satellite2 Star7)
	(pointing satellite4 Star7)
	(have_image Star19 thermograph4)
))

)
