(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite4 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite5 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite6 - satellite
	instrument28 - instrument
	instrument29 - instrument
	satellite7 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite8 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite9 - satellite
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	image3 - mode
	infrared4 - mode
	thermograph0 - mode
	infrared2 - mode
	infrared1 - mode
	Star6 - direction
	Star1 - direction
	GroundStation7 - direction
	GroundStation8 - direction
	Star3 - direction
	Star5 - direction
	Star9 - direction
	Star0 - direction
	GroundStation2 - direction
	GroundStation4 - direction
	Star10 - direction
	Planet11 - direction
)
(:init
	(supports instrument0 infrared2)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 Star5)
	(supports instrument1 infrared2)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 infrared1)
	(supports instrument2 infrared2)
	(supports instrument2 infrared4)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 Star1)
	(supports instrument3 infrared2)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star0)
	(supports instrument4 infrared2)
	(supports instrument4 thermograph0)
	(supports instrument4 infrared4)
	(calibration_target instrument4 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(supports instrument5 infrared4)
	(calibration_target instrument5 Star0)
	(supports instrument6 infrared2)
	(calibration_target instrument6 GroundStation8)
	(supports instrument7 infrared4)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 infrared1)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star0)
	(supports instrument9 image3)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 infrared2)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 GroundStation2)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument11 infrared4)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 GroundStation4)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation4)
	(supports instrument12 thermograph0)
	(supports instrument12 image3)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation7)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 image3)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 Star5)
	(supports instrument15 image3)
	(calibration_target instrument15 GroundStation7)
	(calibration_target instrument15 Star1)
	(supports instrument16 thermograph0)
	(supports instrument16 image3)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star6)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 GroundStation8)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star9)
	(supports instrument17 thermograph0)
	(supports instrument17 infrared2)
	(supports instrument17 infrared4)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 thermograph0)
	(supports instrument18 infrared1)
	(supports instrument18 infrared4)
	(calibration_target instrument18 GroundStation8)
	(calibration_target instrument18 GroundStation7)
	(supports instrument19 infrared4)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation7)
	(supports instrument20 image3)
	(calibration_target instrument20 Star6)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star0)
	(supports instrument21 infrared2)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 GroundStation8)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet11)
	(supports instrument22 infrared4)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 Star1)
	(calibration_target instrument22 GroundStation8)
	(supports instrument23 infrared4)
	(supports instrument23 infrared1)
	(supports instrument23 infrared2)
	(calibration_target instrument23 GroundStation8)
	(calibration_target instrument23 Star3)
	(calibration_target instrument23 GroundStation4)
	(supports instrument24 infrared4)
	(supports instrument24 image3)
	(calibration_target instrument24 Star3)
	(supports instrument25 infrared2)
	(calibration_target instrument25 Star1)
	(supports instrument26 infrared4)
	(supports instrument26 infrared2)
	(calibration_target instrument26 Star3)
	(supports instrument27 thermograph0)
	(calibration_target instrument27 Star9)
	(calibration_target instrument27 Star5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument28 thermograph0)
	(supports instrument28 image3)
	(calibration_target instrument28 Star3)
	(calibration_target instrument28 GroundStation7)
	(supports instrument29 infrared1)
	(supports instrument29 infrared2)
	(calibration_target instrument29 GroundStation7)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 GroundStation4)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star10)
	(supports instrument30 infrared4)
	(supports instrument30 infrared1)
	(calibration_target instrument30 Star6)
	(calibration_target instrument30 GroundStation2)
	(supports instrument31 infrared2)
	(supports instrument31 infrared4)
	(calibration_target instrument31 GroundStation8)
	(calibration_target instrument31 Star6)
	(calibration_target instrument31 Star5)
	(supports instrument32 image3)
	(calibration_target instrument32 GroundStation2)
	(calibration_target instrument32 Star6)
	(supports instrument33 image3)
	(calibration_target instrument33 Star0)
	(supports instrument34 image3)
	(supports instrument34 infrared4)
	(supports instrument34 infrared2)
	(calibration_target instrument34 GroundStation8)
	(calibration_target instrument34 Star1)
	(supports instrument35 image3)
	(supports instrument35 infrared1)
	(calibration_target instrument35 GroundStation8)
	(calibration_target instrument35 GroundStation4)
	(supports instrument36 image3)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 Star5)
	(calibration_target instrument36 GroundStation8)
	(supports instrument37 infrared4)
	(supports instrument37 infrared2)
	(calibration_target instrument37 GroundStation8)
	(calibration_target instrument37 GroundStation4)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation8)
	(supports instrument38 thermograph0)
	(calibration_target instrument38 Star0)
	(supports instrument39 infrared1)
	(supports instrument39 infrared2)
	(calibration_target instrument39 Star0)
	(calibration_target instrument39 Star1)
	(calibration_target instrument39 GroundStation7)
	(supports instrument40 infrared1)
	(supports instrument40 infrared2)
	(calibration_target instrument40 GroundStation4)
	(calibration_target instrument40 GroundStation7)
	(calibration_target instrument40 Star1)
	(supports instrument41 infrared2)
	(supports instrument41 infrared4)
	(supports instrument41 image3)
	(calibration_target instrument41 Star3)
	(supports instrument42 infrared1)
	(supports instrument42 infrared2)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 Star9)
	(calibration_target instrument42 GroundStation2)
	(supports instrument43 image3)
	(calibration_target instrument43 GroundStation7)
	(calibration_target instrument43 Star9)
	(supports instrument44 image3)
	(supports instrument44 thermograph0)
	(supports instrument44 infrared2)
	(calibration_target instrument44 Star3)
	(calibration_target instrument44 Star9)
	(calibration_target instrument44 Star1)
	(supports instrument45 infrared2)
	(supports instrument45 infrared1)
	(calibration_target instrument45 Star1)
	(calibration_target instrument45 GroundStation8)
	(calibration_target instrument45 GroundStation4)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
	(supports instrument46 infrared4)
	(supports instrument46 image3)
	(calibration_target instrument46 Star1)
	(supports instrument47 infrared4)
	(supports instrument47 thermograph0)
	(supports instrument47 infrared2)
	(calibration_target instrument47 Star0)
	(calibration_target instrument47 GroundStation8)
	(supports instrument48 thermograph0)
	(calibration_target instrument48 Star6)
	(calibration_target instrument48 Star5)
	(supports instrument49 thermograph0)
	(supports instrument49 infrared1)
	(calibration_target instrument49 Star3)
	(calibration_target instrument49 Star1)
	(calibration_target instrument49 GroundStation7)
	(supports instrument50 thermograph0)
	(supports instrument50 infrared1)
	(calibration_target instrument50 GroundStation4)
	(calibration_target instrument50 GroundStation7)
	(supports instrument51 thermograph0)
	(calibration_target instrument51 Star9)
	(calibration_target instrument51 Star5)
	(supports instrument52 infrared4)
	(calibration_target instrument52 Star0)
	(calibration_target instrument52 GroundStation7)
	(supports instrument53 image3)
	(supports instrument53 infrared1)
	(calibration_target instrument53 Star5)
	(calibration_target instrument53 Star3)
	(calibration_target instrument53 GroundStation8)
	(supports instrument54 infrared2)
	(supports instrument54 thermograph0)
	(supports instrument54 infrared4)
	(calibration_target instrument54 Star0)
	(calibration_target instrument54 Star9)
	(calibration_target instrument54 GroundStation2)
	(supports instrument55 infrared1)
	(calibration_target instrument55 GroundStation4)
	(calibration_target instrument55 GroundStation2)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation2)
)
(:goal (and
	(pointing satellite0 GroundStation2)
	(pointing satellite2 GroundStation2)
	(pointing satellite3 Star0)
	(have_image Star10 infrared4)
	(have_image Planet11 image3)
))

)
