(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite5 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite6 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	satellite7 - satellite
	instrument45 - instrument
	instrument46 - instrument
	satellite8 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	satellite9 - satellite
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	infrared3 - mode
	spectrograph0 - mode
	thermograph4 - mode
	spectrograph1 - mode
	spectrograph2 - mode
	Star0 - direction
	GroundStation9 - direction
	GroundStation5 - direction
	Star7 - direction
	GroundStation4 - direction
	GroundStation2 - direction
	Star8 - direction
	GroundStation3 - direction
	Star6 - direction
	Star1 - direction
	Star10 - direction
	Planet11 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 infrared3)
	(supports instrument1 spectrograph2)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 spectrograph2)
	(supports instrument2 spectrograph0)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star1)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 infrared3)
	(supports instrument3 spectrograph2)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 spectrograph0)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet11)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 GroundStation2)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet11)
	(supports instrument6 infrared3)
	(calibration_target instrument6 GroundStation2)
	(supports instrument7 thermograph4)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 Star8)
	(supports instrument8 thermograph4)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 GroundStation9)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 spectrograph2)
	(supports instrument9 infrared3)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 Star7)
	(supports instrument10 infrared3)
	(supports instrument10 thermograph4)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 Star6)
	(supports instrument11 spectrograph2)
	(supports instrument11 spectrograph0)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star7)
	(supports instrument12 infrared3)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 Star8)
	(supports instrument13 infrared3)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 GroundStation9)
	(calibration_target instrument13 Star6)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet11)
	(supports instrument14 spectrograph1)
	(supports instrument14 thermograph4)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 GroundStation5)
	(calibration_target instrument14 Star6)
	(supports instrument15 infrared3)
	(calibration_target instrument15 Star6)
	(supports instrument16 infrared3)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 spectrograph2)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 Star0)
	(supports instrument18 spectrograph1)
	(supports instrument18 spectrograph2)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation4)
	(supports instrument19 spectrograph0)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 GroundStation3)
	(supports instrument20 infrared3)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 GroundStation3)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 infrared3)
	(supports instrument22 spectrograph0)
	(supports instrument22 spectrograph1)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 GroundStation3)
	(calibration_target instrument22 Star1)
	(supports instrument23 infrared3)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star8)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star8)
	(supports instrument24 spectrograph0)
	(supports instrument24 thermograph4)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star1)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 GroundStation9)
	(supports instrument26 infrared3)
	(supports instrument26 spectrograph2)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 GroundStation9)
	(calibration_target instrument26 GroundStation2)
	(supports instrument27 infrared3)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 Star1)
	(supports instrument28 spectrograph1)
	(supports instrument28 spectrograph2)
	(calibration_target instrument28 Star6)
	(calibration_target instrument28 GroundStation3)
	(calibration_target instrument28 Star0)
	(supports instrument29 spectrograph2)
	(supports instrument29 infrared3)
	(calibration_target instrument29 GroundStation3)
	(calibration_target instrument29 Star7)
	(supports instrument30 thermograph4)
	(supports instrument30 spectrograph1)
	(calibration_target instrument30 GroundStation5)
	(calibration_target instrument30 Star1)
	(calibration_target instrument30 GroundStation4)
	(supports instrument31 spectrograph0)
	(supports instrument31 spectrograph1)
	(supports instrument31 infrared3)
	(calibration_target instrument31 GroundStation9)
	(calibration_target instrument31 Star8)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 Star1)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation3)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 GroundStation2)
	(calibration_target instrument33 Star0)
	(supports instrument34 thermograph4)
	(supports instrument34 spectrograph1)
	(calibration_target instrument34 GroundStation3)
	(calibration_target instrument34 Star6)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 Star6)
	(calibration_target instrument35 GroundStation3)
	(calibration_target instrument35 Star0)
	(supports instrument36 thermograph4)
	(supports instrument36 spectrograph2)
	(calibration_target instrument36 Star1)
	(supports instrument37 thermograph4)
	(supports instrument37 infrared3)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 Star7)
	(calibration_target instrument37 GroundStation4)
	(calibration_target instrument37 GroundStation9)
	(supports instrument38 spectrograph0)
	(calibration_target instrument38 Star1)
	(calibration_target instrument38 Star8)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 spectrograph0)
	(calibration_target instrument39 GroundStation2)
	(calibration_target instrument39 Star0)
	(calibration_target instrument39 GroundStation9)
	(supports instrument40 spectrograph2)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 GroundStation4)
	(supports instrument41 spectrograph0)
	(supports instrument41 spectrograph2)
	(calibration_target instrument41 Star0)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument42 spectrograph0)
	(supports instrument42 infrared3)
	(supports instrument42 spectrograph2)
	(calibration_target instrument42 Star6)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 GroundStation3)
	(supports instrument43 spectrograph2)
	(supports instrument43 spectrograph1)
	(supports instrument43 infrared3)
	(calibration_target instrument43 GroundStation4)
	(calibration_target instrument43 Star8)
	(calibration_target instrument43 Star7)
	(supports instrument44 spectrograph2)
	(supports instrument44 infrared3)
	(calibration_target instrument44 Star6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star1)
	(supports instrument45 spectrograph1)
	(calibration_target instrument45 GroundStation9)
	(calibration_target instrument45 GroundStation2)
	(calibration_target instrument45 GroundStation5)
	(supports instrument46 spectrograph2)
	(calibration_target instrument46 GroundStation2)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument47 spectrograph1)
	(supports instrument47 thermograph4)
	(supports instrument47 infrared3)
	(calibration_target instrument47 Star1)
	(supports instrument48 spectrograph2)
	(supports instrument48 spectrograph0)
	(calibration_target instrument48 GroundStation2)
	(calibration_target instrument48 GroundStation3)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 Star1)
	(supports instrument50 spectrograph0)
	(supports instrument50 spectrograph1)
	(supports instrument50 spectrograph2)
	(calibration_target instrument50 Star1)
	(calibration_target instrument50 GroundStation2)
	(supports instrument51 spectrograph0)
	(calibration_target instrument51 GroundStation2)
	(calibration_target instrument51 Star7)
	(calibration_target instrument51 Star6)
	(supports instrument52 spectrograph1)
	(supports instrument52 spectrograph2)
	(calibration_target instrument52 GroundStation9)
	(calibration_target instrument52 GroundStation2)
	(calibration_target instrument52 Star1)
	(supports instrument53 spectrograph1)
	(supports instrument53 spectrograph2)
	(supports instrument53 spectrograph0)
	(calibration_target instrument53 Star6)
	(calibration_target instrument53 GroundStation5)
	(calibration_target instrument53 GroundStation4)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star7)
	(supports instrument54 infrared3)
	(supports instrument54 spectrograph1)
	(calibration_target instrument54 GroundStation4)
	(calibration_target instrument54 GroundStation2)
	(calibration_target instrument54 Star6)
	(supports instrument55 spectrograph1)
	(supports instrument55 infrared3)
	(supports instrument55 spectrograph2)
	(calibration_target instrument55 GroundStation4)
	(calibration_target instrument55 Star7)
	(supports instrument56 infrared3)
	(supports instrument56 spectrograph1)
	(supports instrument56 thermograph4)
	(calibration_target instrument56 Star8)
	(calibration_target instrument56 GroundStation2)
	(supports instrument57 spectrograph0)
	(calibration_target instrument57 Star6)
	(calibration_target instrument57 GroundStation3)
	(supports instrument58 spectrograph2)
	(supports instrument58 spectrograph1)
	(supports instrument58 thermograph4)
	(calibration_target instrument58 Star1)
	(calibration_target instrument58 Star6)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite2 GroundStation9)
	(pointing satellite7 Star10)
	(pointing satellite9 Star0)
	(have_image Star10 thermograph4)
	(have_image Planet11 spectrograph2)
))

)
