(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite6 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite7 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	satellite9 - satellite
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	spectrograph0 - mode
	image4 - mode
	thermograph1 - mode
	infrared2 - mode
	infrared3 - mode
	GroundStation8 - direction
	Star7 - direction
	Star9 - direction
	GroundStation3 - direction
	Star0 - direction
	GroundStation1 - direction
	GroundStation6 - direction
	Star5 - direction
	Star4 - direction
	Star2 - direction
	Planet10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 infrared2)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 spectrograph0)
	(supports instrument2 infrared3)
	(calibration_target instrument2 Star7)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 Star5)
	(supports instrument3 infrared3)
	(calibration_target instrument3 GroundStation8)
	(supports instrument4 thermograph1)
	(supports instrument4 infrared3)
	(supports instrument4 image4)
	(calibration_target instrument4 GroundStation6)
	(supports instrument5 thermograph1)
	(supports instrument5 image4)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 Star7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument6 image4)
	(calibration_target instrument6 Star2)
	(supports instrument7 thermograph1)
	(supports instrument7 infrared2)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 Star7)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 Star7)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star5)
	(supports instrument10 image4)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 Star2)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star7)
	(supports instrument11 infrared2)
	(supports instrument11 thermograph1)
	(supports instrument11 image4)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star4)
	(supports instrument12 infrared3)
	(supports instrument12 image4)
	(calibration_target instrument12 GroundStation8)
	(calibration_target instrument12 Star5)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star2)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared2)
	(calibration_target instrument13 Star5)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star5)
	(supports instrument15 spectrograph0)
	(supports instrument15 infrared2)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 GroundStation3)
	(calibration_target instrument15 GroundStation8)
	(supports instrument16 thermograph1)
	(supports instrument16 infrared3)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star5)
	(supports instrument17 thermograph1)
	(supports instrument17 image4)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star0)
	(supports instrument18 thermograph1)
	(supports instrument18 spectrograph0)
	(supports instrument18 infrared3)
	(calibration_target instrument18 Star2)
	(calibration_target instrument18 Star7)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 Star7)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet10)
	(supports instrument20 infrared3)
	(supports instrument20 infrared2)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation8)
	(supports instrument21 infrared3)
	(supports instrument21 image4)
	(calibration_target instrument21 GroundStation6)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 GroundStation3)
	(supports instrument22 thermograph1)
	(supports instrument22 infrared3)
	(supports instrument22 infrared2)
	(calibration_target instrument22 GroundStation3)
	(calibration_target instrument22 Star9)
	(calibration_target instrument22 Star4)
	(supports instrument23 thermograph1)
	(supports instrument23 image4)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 GroundStation3)
	(supports instrument24 image4)
	(calibration_target instrument24 GroundStation3)
	(calibration_target instrument24 GroundStation6)
	(calibration_target instrument24 Star0)
	(supports instrument25 image4)
	(supports instrument25 spectrograph0)
	(supports instrument25 thermograph1)
	(calibration_target instrument25 GroundStation1)
	(supports instrument26 spectrograph0)
	(supports instrument26 infrared2)
	(supports instrument26 thermograph1)
	(calibration_target instrument26 GroundStation1)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 GroundStation8)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation1)
	(supports instrument27 thermograph1)
	(calibration_target instrument27 Star4)
	(supports instrument28 thermograph1)
	(supports instrument28 spectrograph0)
	(supports instrument28 infrared2)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 Star4)
	(calibration_target instrument28 Star2)
	(supports instrument29 infrared2)
	(supports instrument29 infrared3)
	(supports instrument29 thermograph1)
	(calibration_target instrument29 Star5)
	(calibration_target instrument29 Star9)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 infrared2)
	(supports instrument30 infrared3)
	(calibration_target instrument30 Star7)
	(calibration_target instrument30 Star2)
	(calibration_target instrument30 Star5)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 Star7)
	(calibration_target instrument31 GroundStation1)
	(calibration_target instrument31 Star5)
	(supports instrument32 image4)
	(supports instrument32 spectrograph0)
	(supports instrument32 thermograph1)
	(calibration_target instrument32 Star2)
	(calibration_target instrument32 Star7)
	(calibration_target instrument32 Star0)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star9)
	(supports instrument33 image4)
	(supports instrument33 infrared3)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 Star9)
	(supports instrument34 image4)
	(calibration_target instrument34 Star9)
	(supports instrument35 image4)
	(supports instrument35 thermograph1)
	(supports instrument35 infrared3)
	(calibration_target instrument35 GroundStation3)
	(calibration_target instrument35 GroundStation1)
	(calibration_target instrument35 Star9)
	(supports instrument36 image4)
	(calibration_target instrument36 Star7)
	(calibration_target instrument36 GroundStation8)
	(supports instrument37 infrared2)
	(supports instrument37 image4)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 Star7)
	(calibration_target instrument37 Star9)
	(calibration_target instrument37 Star4)
	(supports instrument38 image4)
	(calibration_target instrument38 Star9)
	(calibration_target instrument38 Star0)
	(supports instrument39 infrared2)
	(supports instrument39 spectrograph0)
	(calibration_target instrument39 Star2)
	(supports instrument40 infrared3)
	(calibration_target instrument40 Star7)
	(calibration_target instrument40 Star5)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star2)
	(supports instrument41 infrared2)
	(supports instrument41 image4)
	(supports instrument41 spectrograph0)
	(calibration_target instrument41 GroundStation3)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 Star0)
	(supports instrument42 image4)
	(calibration_target instrument42 GroundStation1)
	(supports instrument43 infrared3)
	(calibration_target instrument43 Star2)
	(calibration_target instrument43 GroundStation3)
	(calibration_target instrument43 GroundStation8)
	(supports instrument44 spectrograph0)
	(supports instrument44 image4)
	(calibration_target instrument44 GroundStation3)
	(calibration_target instrument44 Star0)
	(calibration_target instrument44 GroundStation1)
	(supports instrument45 infrared2)
	(calibration_target instrument45 GroundStation1)
	(calibration_target instrument45 Star2)
	(calibration_target instrument45 Star0)
	(supports instrument46 infrared2)
	(calibration_target instrument46 Star5)
	(calibration_target instrument46 Star4)
	(supports instrument47 image4)
	(calibration_target instrument47 Star2)
	(calibration_target instrument47 GroundStation1)
	(supports instrument48 infrared2)
	(supports instrument48 spectrograph0)
	(calibration_target instrument48 GroundStation3)
	(calibration_target instrument48 Star9)
	(calibration_target instrument48 Star2)
	(supports instrument49 thermograph1)
	(supports instrument49 infrared3)
	(calibration_target instrument49 Star7)
	(supports instrument50 spectrograph0)
	(supports instrument50 infrared3)
	(supports instrument50 image4)
	(calibration_target instrument50 GroundStation3)
	(calibration_target instrument50 Star4)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star5)
	(supports instrument51 infrared2)
	(supports instrument51 spectrograph0)
	(supports instrument51 thermograph1)
	(calibration_target instrument51 GroundStation3)
	(supports instrument52 image4)
	(supports instrument52 infrared3)
	(calibration_target instrument52 GroundStation8)
	(calibration_target instrument52 GroundStation1)
	(calibration_target instrument52 GroundStation3)
	(supports instrument53 thermograph1)
	(supports instrument53 image4)
	(supports instrument53 infrared2)
	(calibration_target instrument53 Star9)
	(calibration_target instrument53 Star7)
	(supports instrument54 thermograph1)
	(calibration_target instrument54 GroundStation3)
	(calibration_target instrument54 Star9)
	(supports instrument55 infrared2)
	(supports instrument55 thermograph1)
	(supports instrument55 image4)
	(calibration_target instrument55 GroundStation8)
	(supports instrument56 infrared3)
	(supports instrument56 spectrograph0)
	(calibration_target instrument56 Star0)
	(calibration_target instrument56 GroundStation6)
	(calibration_target instrument56 GroundStation3)
	(supports instrument57 thermograph1)
	(calibration_target instrument57 GroundStation8)
	(calibration_target instrument57 Star0)
	(supports instrument58 thermograph1)
	(calibration_target instrument58 Star9)
	(calibration_target instrument58 GroundStation6)
	(calibration_target instrument58 Star5)
	(supports instrument59 infrared2)
	(calibration_target instrument59 GroundStation6)
	(calibration_target instrument59 Star4)
	(calibration_target instrument59 GroundStation3)
	(supports instrument60 spectrograph0)
	(calibration_target instrument60 GroundStation3)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet10)
	(supports instrument61 infrared3)
	(supports instrument61 thermograph1)
	(supports instrument61 infrared2)
	(calibration_target instrument61 Star2)
	(calibration_target instrument61 Star5)
	(calibration_target instrument61 Star7)
	(supports instrument62 image4)
	(supports instrument62 infrared2)
	(supports instrument62 spectrograph0)
	(calibration_target instrument62 Star4)
	(calibration_target instrument62 Star9)
	(supports instrument63 infrared2)
	(supports instrument63 infrared3)
	(supports instrument63 image4)
	(calibration_target instrument63 GroundStation6)
	(calibration_target instrument63 Star0)
	(calibration_target instrument63 GroundStation3)
	(supports instrument64 infrared2)
	(supports instrument64 thermograph1)
	(calibration_target instrument64 GroundStation6)
	(calibration_target instrument64 GroundStation1)
	(calibration_target instrument64 Star2)
	(supports instrument65 infrared3)
	(supports instrument65 infrared2)
	(calibration_target instrument65 Star2)
	(calibration_target instrument65 Star4)
	(calibration_target instrument65 Star5)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation6)
)
(:goal (and
	(pointing satellite5 Phenomenon11)
	(pointing satellite8 Star2)
	(have_image Planet10 image4)
	(have_image Phenomenon11 thermograph1)
))

)
