(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite4 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite5 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite6 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite7 - satellite
	instrument44 - instrument
	instrument45 - instrument
	satellite8 - satellite
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite9 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	spectrograph3 - mode
	thermograph0 - mode
	thermograph4 - mode
	image2 - mode
	spectrograph1 - mode
	GroundStation5 - direction
	Star7 - direction
	Star2 - direction
	Star0 - direction
	Star9 - direction
	GroundStation1 - direction
	GroundStation8 - direction
	Star3 - direction
	Star6 - direction
	Star10 - direction
	GroundStation4 - direction
	Star11 - direction
	Phenomenon12 - direction
)
(:init
	(supports instrument0 thermograph0)
	(supports instrument0 spectrograph3)
	(supports instrument0 image2)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star0)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 GroundStation5)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 Star6)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 GroundStation8)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(= (data_capacity satellite0) 1000)
	(= (fuel satellite0) 114)
	(supports instrument4 spectrograph1)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star10)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star2)
	(supports instrument5 thermograph0)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star10)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(= (data_capacity satellite1) 1000)
	(= (fuel satellite1) 117)
	(supports instrument6 spectrograph3)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star7)
	(supports instrument7 image2)
	(supports instrument7 spectrograph3)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star10)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 spectrograph3)
	(supports instrument8 thermograph4)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 Star9)
	(supports instrument9 spectrograph3)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 Star2)
	(supports instrument10 image2)
	(supports instrument10 spectrograph1)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star7)
	(supports instrument11 spectrograph3)
	(supports instrument11 image2)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 GroundStation5)
	(supports instrument12 image2)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 Star7)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(= (data_capacity satellite2) 1000)
	(= (fuel satellite2) 196)
	(supports instrument13 spectrograph1)
	(supports instrument13 spectrograph3)
	(calibration_target instrument13 GroundStation5)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation1)
	(supports instrument14 thermograph4)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation8)
	(supports instrument15 thermograph0)
	(supports instrument15 spectrograph1)
	(calibration_target instrument15 GroundStation8)
	(supports instrument16 image2)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 thermograph0)
	(supports instrument17 spectrograph3)
	(supports instrument17 spectrograph1)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation5)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star9)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 Star10)
	(supports instrument20 spectrograph3)
	(supports instrument20 image2)
	(calibration_target instrument20 Star2)
	(calibration_target instrument20 Star9)
	(calibration_target instrument20 GroundStation4)
	(supports instrument21 thermograph0)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 GroundStation8)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation8)
	(= (data_capacity satellite3) 1000)
	(= (fuel satellite3) 170)
	(supports instrument22 image2)
	(supports instrument22 thermograph0)
	(calibration_target instrument22 Star7)
	(supports instrument23 spectrograph1)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 Star2)
	(calibration_target instrument23 Star10)
	(calibration_target instrument23 Star7)
	(supports instrument24 thermograph0)
	(supports instrument24 image2)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star7)
	(supports instrument25 spectrograph3)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 Star3)
	(supports instrument26 thermograph0)
	(supports instrument26 image2)
	(calibration_target instrument26 Star10)
	(supports instrument27 spectrograph1)
	(supports instrument27 image2)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 Star2)
	(supports instrument28 spectrograph3)
	(supports instrument28 thermograph4)
	(supports instrument28 image2)
	(calibration_target instrument28 GroundStation5)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 image2)
	(supports instrument29 thermograph4)
	(supports instrument29 thermograph0)
	(calibration_target instrument29 Star7)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 GroundStation1)
	(calibration_target instrument30 GroundStation8)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 GroundStation5)
	(calibration_target instrument31 Star3)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star11)
	(= (data_capacity satellite4) 1000)
	(= (fuel satellite4) 100)
	(supports instrument32 thermograph0)
	(supports instrument32 spectrograph1)
	(supports instrument32 image2)
	(calibration_target instrument32 GroundStation8)
	(calibration_target instrument32 GroundStation4)
	(calibration_target instrument32 Star3)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 Star7)
	(supports instrument34 image2)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 Star0)
	(supports instrument35 thermograph4)
	(supports instrument35 image2)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 Star9)
	(calibration_target instrument35 GroundStation4)
	(supports instrument36 spectrograph3)
	(calibration_target instrument36 Star2)
	(supports instrument37 thermograph0)
	(supports instrument37 thermograph4)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 GroundStation4)
	(calibration_target instrument37 Star0)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(= (data_capacity satellite5) 1000)
	(= (fuel satellite5) 197)
	(supports instrument38 thermograph0)
	(supports instrument38 image2)
	(supports instrument38 spectrograph3)
	(calibration_target instrument38 Star7)
	(calibration_target instrument38 GroundStation1)
	(supports instrument39 image2)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 Star0)
	(supports instrument40 thermograph0)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 Star9)
	(supports instrument41 thermograph0)
	(supports instrument41 image2)
	(supports instrument41 spectrograph3)
	(calibration_target instrument41 Star9)
	(calibration_target instrument41 GroundStation1)
	(calibration_target instrument41 GroundStation5)
	(supports instrument42 spectrograph1)
	(calibration_target instrument42 Star9)
	(supports instrument43 thermograph4)
	(supports instrument43 image2)
	(calibration_target instrument43 Star7)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(= (data_capacity satellite6) 1000)
	(= (fuel satellite6) 169)
	(supports instrument44 spectrograph3)
	(calibration_target instrument44 Star2)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 Star9)
	(calibration_target instrument45 Star3)
	(calibration_target instrument45 Star0)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon12)
	(= (data_capacity satellite7) 1000)
	(= (fuel satellite7) 101)
	(supports instrument46 spectrograph1)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 Star6)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 thermograph0)
	(supports instrument47 spectrograph1)
	(calibration_target instrument47 Star3)
	(calibration_target instrument47 GroundStation8)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 GroundStation1)
	(calibration_target instrument48 Star3)
	(supports instrument49 spectrograph1)
	(supports instrument49 thermograph4)
	(calibration_target instrument49 Star6)
	(supports instrument50 image2)
	(supports instrument50 spectrograph1)
	(supports instrument50 thermograph4)
	(calibration_target instrument50 Star0)
	(calibration_target instrument50 GroundStation1)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star10)
	(= (data_capacity satellite8) 1000)
	(= (fuel satellite8) 164)
	(supports instrument51 image2)
	(supports instrument51 thermograph4)
	(calibration_target instrument51 Star9)
	(supports instrument52 spectrograph1)
	(calibration_target instrument52 GroundStation8)
	(calibration_target instrument52 GroundStation4)
	(calibration_target instrument52 GroundStation1)
	(supports instrument53 spectrograph1)
	(calibration_target instrument53 Star10)
	(calibration_target instrument53 Star6)
	(calibration_target instrument53 Star3)
	(supports instrument54 spectrograph1)
	(calibration_target instrument54 GroundStation4)
	(calibration_target instrument54 Star10)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
	(= (data_capacity satellite9) 1000)
	(= (fuel satellite9) 101)
	(= (data Star11 spectrograph3) 204)
	(= (data Phenomenon12 spectrograph3) 102)
	(= (data Star11 thermograph0) 68)
	(= (data Phenomenon12 thermograph0) 33)
	(= (data Star11 thermograph4) 298)
	(= (data Phenomenon12 thermograph4) 191)
	(= (data Star11 image2) 25)
	(= (data Phenomenon12 image2) 136)
	(= (data Star11 spectrograph1) 254)
	(= (data Phenomenon12 spectrograph1) 49)
	(= (slew_time GroundStation5 Star0) 18.25)
	(= (slew_time Star0 GroundStation5) 18.25)
	(= (slew_time GroundStation5 GroundStation1) 10.41)
	(= (slew_time GroundStation1 GroundStation5) 10.41)
	(= (slew_time GroundStation5 Star2) 72.53)
	(= (slew_time Star2 GroundStation5) 72.53)
	(= (slew_time GroundStation5 Star3) 58.26)
	(= (slew_time Star3 GroundStation5) 58.26)
	(= (slew_time GroundStation5 GroundStation4) 36.84)
	(= (slew_time GroundStation4 GroundStation5) 36.84)
	(= (slew_time Star7 Star0) 51.94)
	(= (slew_time Star0 Star7) 51.94)
	(= (slew_time Star7 GroundStation1) 65.57)
	(= (slew_time GroundStation1 Star7) 65.57)
	(= (slew_time Star7 Star2) 4.047)
	(= (slew_time Star2 Star7) 4.047)
	(= (slew_time Star7 Star3) 14.27)
	(= (slew_time Star3 Star7) 14.27)
	(= (slew_time Star7 GroundStation4) 10.19)
	(= (slew_time GroundStation4 Star7) 10.19)
	(= (slew_time Star7 GroundStation5) 51.69)
	(= (slew_time GroundStation5 Star7) 51.69)
	(= (slew_time Star7 Star6) 0.3192)
	(= (slew_time Star6 Star7) 0.3192)
	(= (slew_time Star2 Star0) 32.89)
	(= (slew_time Star0 Star2) 32.89)
	(= (slew_time Star2 GroundStation1) 13.35)
	(= (slew_time GroundStation1 Star2) 13.35)
	(= (slew_time Star9 Star0) 23.31)
	(= (slew_time Star0 Star9) 23.31)
	(= (slew_time Star9 GroundStation1) 14.44)
	(= (slew_time GroundStation1 Star9) 14.44)
	(= (slew_time Star9 Star2) 78.16)
	(= (slew_time Star2 Star9) 78.16)
	(= (slew_time Star9 Star3) 33.46)
	(= (slew_time Star3 Star9) 33.46)
	(= (slew_time Star9 GroundStation4) 46.6)
	(= (slew_time GroundStation4 Star9) 46.6)
	(= (slew_time Star9 GroundStation5) 30.3)
	(= (slew_time GroundStation5 Star9) 30.3)
	(= (slew_time Star9 Star6) 21.42)
	(= (slew_time Star6 Star9) 21.42)
	(= (slew_time Star9 Star7) 9.127)
	(= (slew_time Star7 Star9) 9.127)
	(= (slew_time Star9 GroundStation8) 26.28)
	(= (slew_time GroundStation8 Star9) 26.28)
	(= (slew_time GroundStation1 Star0) 22.76)
	(= (slew_time Star0 GroundStation1) 22.76)
	(= (slew_time GroundStation8 Star0) 37.16)
	(= (slew_time Star0 GroundStation8) 37.16)
	(= (slew_time GroundStation8 GroundStation1) 14.21)
	(= (slew_time GroundStation1 GroundStation8) 14.21)
	(= (slew_time GroundStation8 Star2) 4.502)
	(= (slew_time Star2 GroundStation8) 4.502)
	(= (slew_time GroundStation8 Star3) 21.23)
	(= (slew_time Star3 GroundStation8) 21.23)
	(= (slew_time GroundStation8 GroundStation4) 32.6)
	(= (slew_time GroundStation4 GroundStation8) 32.6)
	(= (slew_time GroundStation8 GroundStation5) 19.64)
	(= (slew_time GroundStation5 GroundStation8) 19.64)
	(= (slew_time GroundStation8 Star6) 14.65)
	(= (slew_time Star6 GroundStation8) 14.65)
	(= (slew_time GroundStation8 Star7) 36.05)
	(= (slew_time Star7 GroundStation8) 36.05)
	(= (slew_time Star3 Star0) 14.8)
	(= (slew_time Star0 Star3) 14.8)
	(= (slew_time Star3 GroundStation1) 59.64)
	(= (slew_time GroundStation1 Star3) 59.64)
	(= (slew_time Star3 Star2) 15.33)
	(= (slew_time Star2 Star3) 15.33)
	(= (slew_time Star6 Star0) 54.13)
	(= (slew_time Star0 Star6) 54.13)
	(= (slew_time Star6 GroundStation1) 37.18)
	(= (slew_time GroundStation1 Star6) 37.18)
	(= (slew_time Star6 Star2) 27.02)
	(= (slew_time Star2 Star6) 27.02)
	(= (slew_time Star6 Star3) 27.85)
	(= (slew_time Star3 Star6) 27.85)
	(= (slew_time Star6 GroundStation4) 3.464)
	(= (slew_time GroundStation4 Star6) 3.464)
	(= (slew_time Star6 GroundStation5) 3.841)
	(= (slew_time GroundStation5 Star6) 3.841)
	(= (slew_time Star10 Star0) 22.33)
	(= (slew_time Star0 Star10) 22.33)
	(= (slew_time Star10 GroundStation1) 6.894)
	(= (slew_time GroundStation1 Star10) 6.894)
	(= (slew_time Star10 Star2) 32.46)
	(= (slew_time Star2 Star10) 32.46)
	(= (slew_time Star10 Star3) 39.4)
	(= (slew_time Star3 Star10) 39.4)
	(= (slew_time Star10 GroundStation4) 28.55)
	(= (slew_time GroundStation4 Star10) 28.55)
	(= (slew_time Star10 GroundStation5) 1.282)
	(= (slew_time GroundStation5 Star10) 1.282)
	(= (slew_time Star10 Star6) 73.34)
	(= (slew_time Star6 Star10) 73.34)
	(= (slew_time Star10 Star7) 18.15)
	(= (slew_time Star7 Star10) 18.15)
	(= (slew_time Star10 GroundStation8) 62.91)
	(= (slew_time GroundStation8 Star10) 62.91)
	(= (slew_time Star10 Star9) 20.62)
	(= (slew_time Star9 Star10) 20.62)
	(= (slew_time GroundStation4 Star0) 61.72)
	(= (slew_time Star0 GroundStation4) 61.72)
	(= (slew_time GroundStation4 GroundStation1) 44.22)
	(= (slew_time GroundStation1 GroundStation4) 44.22)
	(= (slew_time GroundStation4 Star2) 2.528)
	(= (slew_time Star2 GroundStation4) 2.528)
	(= (slew_time GroundStation4 Star3) 36.6)
	(= (slew_time Star3 GroundStation4) 36.6)
	(= (slew_time Star11 Star0) 64.53)
	(= (slew_time Star0 Star11) 64.53)
	(= (slew_time Star11 GroundStation1) 53.97)
	(= (slew_time GroundStation1 Star11) 53.97)
	(= (slew_time Star11 Star2) 50.9)
	(= (slew_time Star2 Star11) 50.9)
	(= (slew_time Star11 Star3) 13.99)
	(= (slew_time Star3 Star11) 13.99)
	(= (slew_time Star11 GroundStation4) 27.01)
	(= (slew_time GroundStation4 Star11) 27.01)
	(= (slew_time Star11 GroundStation5) 54.85)
	(= (slew_time GroundStation5 Star11) 54.85)
	(= (slew_time Star11 Star6) 3.744)
	(= (slew_time Star6 Star11) 3.744)
	(= (slew_time Star11 Star7) 55.47)
	(= (slew_time Star7 Star11) 55.47)
	(= (slew_time Star11 GroundStation8) 4.516)
	(= (slew_time GroundStation8 Star11) 4.516)
	(= (slew_time Star11 Star9) 45.05)
	(= (slew_time Star9 Star11) 45.05)
	(= (slew_time Star11 Star10) 9.645)
	(= (slew_time Star10 Star11) 9.645)
	(= (slew_time Phenomenon12 Star0) 24.37)
	(= (slew_time Star0 Phenomenon12) 24.37)
	(= (slew_time Phenomenon12 GroundStation1) 77.9)
	(= (slew_time GroundStation1 Phenomenon12) 77.9)
	(= (slew_time Phenomenon12 Star2) 20.83)
	(= (slew_time Star2 Phenomenon12) 20.83)
	(= (slew_time Phenomenon12 Star3) 81.47)
	(= (slew_time Star3 Phenomenon12) 81.47)
	(= (slew_time Phenomenon12 GroundStation4) 50.25)
	(= (slew_time GroundStation4 Phenomenon12) 50.25)
	(= (slew_time Phenomenon12 GroundStation5) 52.85)
	(= (slew_time GroundStation5 Phenomenon12) 52.85)
	(= (slew_time Phenomenon12 Star6) 32.91)
	(= (slew_time Star6 Phenomenon12) 32.91)
	(= (slew_time Phenomenon12 Star7) 6.841)
	(= (slew_time Star7 Phenomenon12) 6.841)
	(= (slew_time Phenomenon12 GroundStation8) 22.48)
	(= (slew_time GroundStation8 Phenomenon12) 22.48)
	(= (slew_time Phenomenon12 Star9) 5.55)
	(= (slew_time Star9 Phenomenon12) 5.55)
	(= (slew_time Phenomenon12 Star10) 11.17)
	(= (slew_time Star10 Phenomenon12) 11.17)
	(= (slew_time Phenomenon12 Star11) 35.12)
	(= (slew_time Star11 Phenomenon12) 35.12)
	(= (data-stored) 0)
	(= (fuel-used) 0)
)
(:goal (and
	(pointing satellite0 GroundStation5)
	(pointing satellite3 GroundStation1)
	(pointing satellite5 Star11)
	(pointing satellite6 Phenomenon12)
	(pointing satellite9 GroundStation5)
	(have_image Star11 image2)
	(have_image Phenomenon12 spectrograph3)
))
(:metric minimize (fuel-used))

)
