(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite5 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite6 - satellite
	instrument32 - instrument
	instrument33 - instrument
	satellite7 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite8 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite9 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	thermograph1 - mode
	image3 - mode
	infrared4 - mode
	thermograph2 - mode
	infrared0 - mode
	GroundStation11 - direction
	Star7 - direction
	Star6 - direction
	Star5 - direction
	Star1 - direction
	GroundStation13 - direction
	GroundStation8 - direction
	GroundStation0 - direction
	Star9 - direction
	GroundStation4 - direction
	Star10 - direction
	Star3 - direction
	GroundStation2 - direction
	Star12 - direction
	Star14 - direction
	Phenomenon15 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 image3)
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star10)
	(calibration_target instrument0 GroundStation13)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star10)
	(calibration_target instrument1 GroundStation8)
	(supports instrument2 image3)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star6)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star6)
	(calibration_target instrument3 GroundStation2)
	(supports instrument4 infrared4)
	(supports instrument4 infrared0)
	(supports instrument4 image3)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 GroundStation13)
	(calibration_target instrument5 Star10)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 Star5)
	(supports instrument6 thermograph2)
	(supports instrument6 infrared4)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star10)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument7 infrared0)
	(supports instrument7 image3)
	(supports instrument7 infrared4)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 Star12)
	(supports instrument8 thermograph1)
	(supports instrument8 image3)
	(supports instrument8 infrared4)
	(calibration_target instrument8 Star5)
	(supports instrument9 infrared0)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 GroundStation13)
	(supports instrument10 image3)
	(supports instrument10 thermograph1)
	(supports instrument10 infrared4)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 GroundStation11)
	(supports instrument11 image3)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation11)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 Star9)
	(supports instrument12 image3)
	(supports instrument12 infrared4)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 Star7)
	(supports instrument13 thermograph1)
	(calibration_target instrument13 Star9)
	(calibration_target instrument13 GroundStation0)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument14 infrared0)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 GroundStation4)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 GroundStation11)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 GroundStation13)
	(calibration_target instrument15 Star3)
	(supports instrument16 image3)
	(supports instrument16 infrared0)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 GroundStation0)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(supports instrument17 image3)
	(supports instrument17 thermograph2)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star12)
	(calibration_target instrument17 GroundStation0)
	(supports instrument18 image3)
	(supports instrument18 infrared4)
	(calibration_target instrument18 Star6)
	(calibration_target instrument18 GroundStation13)
	(calibration_target instrument18 Star10)
	(supports instrument19 image3)
	(calibration_target instrument19 Star9)
	(supports instrument20 infrared4)
	(supports instrument20 image3)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star9)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation8)
	(supports instrument21 infrared0)
	(supports instrument21 infrared4)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 GroundStation4)
	(supports instrument22 infrared0)
	(supports instrument22 infrared4)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 Star6)
	(supports instrument23 thermograph2)
	(supports instrument23 infrared0)
	(supports instrument23 infrared4)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 Star5)
	(calibration_target instrument23 GroundStation11)
	(supports instrument24 infrared0)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star9)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 GroundStation13)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon15)
	(supports instrument25 infrared0)
	(calibration_target instrument25 GroundStation4)
	(calibration_target instrument25 GroundStation13)
	(calibration_target instrument25 GroundStation11)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 Star7)
	(calibration_target instrument26 GroundStation8)
	(supports instrument27 image3)
	(calibration_target instrument27 Star1)
	(calibration_target instrument27 GroundStation0)
	(supports instrument28 infrared0)
	(supports instrument28 thermograph1)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 Star10)
	(supports instrument30 thermograph1)
	(supports instrument30 infrared4)
	(supports instrument30 infrared0)
	(calibration_target instrument30 GroundStation0)
	(supports instrument31 thermograph2)
	(supports instrument31 infrared0)
	(calibration_target instrument31 GroundStation13)
	(calibration_target instrument31 GroundStation8)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star10)
	(supports instrument32 infrared0)
	(calibration_target instrument32 GroundStation11)
	(calibration_target instrument32 Star5)
	(supports instrument33 infrared0)
	(calibration_target instrument33 Star10)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star5)
	(supports instrument34 thermograph1)
	(calibration_target instrument34 GroundStation11)
	(supports instrument35 thermograph1)
	(supports instrument35 infrared4)
	(calibration_target instrument35 GroundStation0)
	(calibration_target instrument35 Star9)
	(supports instrument36 image3)
	(supports instrument36 thermograph1)
	(supports instrument36 infrared4)
	(calibration_target instrument36 GroundStation2)
	(supports instrument37 infrared4)
	(calibration_target instrument37 Star7)
	(calibration_target instrument37 Star1)
	(calibration_target instrument37 GroundStation4)
	(supports instrument38 thermograph2)
	(supports instrument38 thermograph1)
	(supports instrument38 image3)
	(calibration_target instrument38 Star5)
	(supports instrument39 infrared4)
	(supports instrument39 thermograph1)
	(calibration_target instrument39 Star5)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument40 thermograph2)
	(supports instrument40 infrared0)
	(supports instrument40 thermograph1)
	(calibration_target instrument40 GroundStation8)
	(supports instrument41 infrared4)
	(supports instrument41 image3)
	(calibration_target instrument41 GroundStation13)
	(calibration_target instrument41 Star10)
	(calibration_target instrument41 Star12)
	(supports instrument42 thermograph1)
	(supports instrument42 infrared4)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 Star5)
	(supports instrument43 image3)
	(supports instrument43 thermograph1)
	(supports instrument43 thermograph2)
	(calibration_target instrument43 GroundStation0)
	(calibration_target instrument43 GroundStation2)
	(calibration_target instrument43 Star7)
	(supports instrument44 thermograph2)
	(supports instrument44 thermograph1)
	(supports instrument44 infrared4)
	(calibration_target instrument44 Star7)
	(calibration_target instrument44 GroundStation2)
	(calibration_target instrument44 Star6)
	(calibration_target instrument44 Star3)
	(supports instrument45 infrared4)
	(supports instrument45 infrared0)
	(calibration_target instrument45 Star5)
	(calibration_target instrument45 Star6)
	(calibration_target instrument45 Star9)
	(calibration_target instrument45 GroundStation8)
	(supports instrument46 image3)
	(calibration_target instrument46 GroundStation4)
	(supports instrument47 thermograph1)
	(calibration_target instrument47 Star9)
	(supports instrument48 infrared4)
	(supports instrument48 infrared0)
	(supports instrument48 thermograph1)
	(calibration_target instrument48 GroundStation13)
	(calibration_target instrument48 GroundStation2)
	(calibration_target instrument48 Star1)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star9)
	(supports instrument49 image3)
	(supports instrument49 thermograph1)
	(supports instrument49 thermograph2)
	(calibration_target instrument49 GroundStation8)
	(calibration_target instrument49 GroundStation0)
	(supports instrument50 image3)
	(supports instrument50 infrared4)
	(calibration_target instrument50 GroundStation2)
	(calibration_target instrument50 GroundStation0)
	(calibration_target instrument50 Star3)
	(calibration_target instrument50 GroundStation4)
	(supports instrument51 infrared0)
	(calibration_target instrument51 GroundStation2)
	(supports instrument52 infrared4)
	(supports instrument52 infrared0)
	(calibration_target instrument52 Star12)
	(calibration_target instrument52 GroundStation4)
	(calibration_target instrument52 Star10)
	(calibration_target instrument52 Star9)
	(supports instrument53 image3)
	(supports instrument53 infrared0)
	(calibration_target instrument53 Star10)
	(calibration_target instrument53 Star3)
	(supports instrument54 infrared0)
	(supports instrument54 thermograph2)
	(supports instrument54 infrared4)
	(calibration_target instrument54 Star12)
	(calibration_target instrument54 GroundStation2)
	(calibration_target instrument54 Star3)
	(calibration_target instrument54 Star10)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite0 GroundStation13)
	(pointing satellite4 Star12)
	(have_image Star14 infrared0)
	(have_image Phenomenon15 thermograph1)
))

)
