(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite1 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite4 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite5 - satellite
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	satellite7 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite8 - satellite
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	satellite9 - satellite
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	instrument68 - instrument
	instrument69 - instrument
	instrument70 - instrument
	image1 - mode
	infrared3 - mode
	image0 - mode
	infrared4 - mode
	infrared2 - mode
	GroundStation0 - direction
	GroundStation5 - direction
	Star8 - direction
	Star12 - direction
	GroundStation6 - direction
	GroundStation4 - direction
	Star1 - direction
	GroundStation13 - direction
	Star3 - direction
	GroundStation2 - direction
	Star11 - direction
	GroundStation10 - direction
	Star7 - direction
	Star9 - direction
	Phenomenon14 - direction
	Star15 - direction
)
(:init
	(supports instrument0 infrared4)
	(supports instrument0 image1)
	(calibration_target instrument0 Star7)
	(supports instrument1 infrared2)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 Star1)
	(supports instrument2 image1)
	(calibration_target instrument2 Star9)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 infrared2)
	(supports instrument3 image0)
	(supports instrument3 image1)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation13)
	(supports instrument4 infrared4)
	(supports instrument4 image0)
	(supports instrument4 image1)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 Star3)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation6)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 GroundStation5)
	(calibration_target instrument6 Star7)
	(supports instrument7 infrared4)
	(supports instrument7 infrared2)
	(supports instrument7 infrared3)
	(calibration_target instrument7 GroundStation13)
	(supports instrument8 infrared3)
	(supports instrument8 image0)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 image1)
	(supports instrument9 image0)
	(supports instrument9 infrared4)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 Star7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon14)
	(supports instrument10 infrared3)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star12)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 GroundStation10)
	(calibration_target instrument10 Star1)
	(supports instrument11 infrared4)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 GroundStation10)
	(supports instrument12 image1)
	(calibration_target instrument12 GroundStation10)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 Star11)
	(supports instrument13 image1)
	(supports instrument13 infrared4)
	(supports instrument13 image0)
	(calibration_target instrument13 GroundStation5)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 Star9)
	(supports instrument15 image1)
	(calibration_target instrument15 Star11)
	(calibration_target instrument15 GroundStation10)
	(calibration_target instrument15 GroundStation5)
	(supports instrument16 infrared2)
	(supports instrument16 image1)
	(supports instrument16 infrared3)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 infrared3)
	(supports instrument17 image0)
	(supports instrument17 infrared4)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 Star11)
	(supports instrument18 infrared4)
	(supports instrument18 image1)
	(supports instrument18 infrared2)
	(calibration_target instrument18 Star11)
	(calibration_target instrument18 GroundStation0)
	(calibration_target instrument18 Star12)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation10)
	(supports instrument19 image1)
	(supports instrument19 infrared2)
	(calibration_target instrument19 Star9)
	(calibration_target instrument19 Star8)
	(calibration_target instrument19 GroundStation10)
	(calibration_target instrument19 GroundStation13)
	(supports instrument20 image0)
	(supports instrument20 infrared2)
	(supports instrument20 image1)
	(calibration_target instrument20 Star1)
	(calibration_target instrument20 GroundStation10)
	(supports instrument21 infrared2)
	(calibration_target instrument21 Star1)
	(supports instrument22 image0)
	(supports instrument22 infrared3)
	(calibration_target instrument22 Star11)
	(calibration_target instrument22 Star12)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 Star7)
	(supports instrument23 infrared3)
	(supports instrument23 infrared2)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 GroundStation0)
	(calibration_target instrument23 Star3)
	(calibration_target instrument23 Star9)
	(supports instrument24 image0)
	(supports instrument24 image1)
	(supports instrument24 infrared2)
	(calibration_target instrument24 GroundStation10)
	(calibration_target instrument24 Star1)
	(calibration_target instrument24 GroundStation6)
	(supports instrument25 image0)
	(supports instrument25 infrared3)
	(supports instrument25 infrared4)
	(calibration_target instrument25 Star12)
	(calibration_target instrument25 Star9)
	(supports instrument26 infrared2)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation0)
	(calibration_target instrument26 Star1)
	(supports instrument27 infrared2)
	(calibration_target instrument27 Star1)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 Star11)
	(calibration_target instrument27 GroundStation5)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation6)
	(supports instrument28 infrared3)
	(calibration_target instrument28 Star11)
	(supports instrument29 image0)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 Star7)
	(calibration_target instrument29 GroundStation6)
	(calibration_target instrument29 GroundStation0)
	(supports instrument30 image0)
	(supports instrument30 infrared3)
	(calibration_target instrument30 GroundStation0)
	(calibration_target instrument30 Star1)
	(calibration_target instrument30 Star9)
	(calibration_target instrument30 GroundStation6)
	(supports instrument31 infrared3)
	(calibration_target instrument31 Star12)
	(calibration_target instrument31 GroundStation10)
	(calibration_target instrument31 Star9)
	(supports instrument32 image0)
	(supports instrument32 infrared3)
	(supports instrument32 image1)
	(calibration_target instrument32 Star7)
	(supports instrument33 infrared4)
	(supports instrument33 infrared2)
	(supports instrument33 image1)
	(calibration_target instrument33 Star12)
	(calibration_target instrument33 GroundStation4)
	(calibration_target instrument33 GroundStation0)
	(calibration_target instrument33 GroundStation6)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation6)
	(supports instrument34 infrared4)
	(supports instrument34 infrared3)
	(supports instrument34 image0)
	(calibration_target instrument34 GroundStation0)
	(calibration_target instrument34 GroundStation4)
	(calibration_target instrument34 Star9)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star9)
	(supports instrument35 infrared3)
	(supports instrument35 infrared2)
	(supports instrument35 image0)
	(calibration_target instrument35 Star11)
	(calibration_target instrument35 Star7)
	(supports instrument36 image1)
	(supports instrument36 image0)
	(calibration_target instrument36 GroundStation13)
	(calibration_target instrument36 Star3)
	(supports instrument37 infrared2)
	(supports instrument37 image1)
	(supports instrument37 infrared3)
	(calibration_target instrument37 GroundStation5)
	(calibration_target instrument37 GroundStation0)
	(supports instrument38 infrared2)
	(supports instrument38 image1)
	(supports instrument38 infrared4)
	(calibration_target instrument38 Star3)
	(calibration_target instrument38 GroundStation0)
	(calibration_target instrument38 Star8)
	(calibration_target instrument38 GroundStation10)
	(supports instrument39 infrared3)
	(calibration_target instrument39 Star11)
	(supports instrument40 infrared2)
	(calibration_target instrument40 GroundStation6)
	(supports instrument41 image0)
	(supports instrument41 infrared4)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 GroundStation0)
	(calibration_target instrument41 GroundStation6)
	(calibration_target instrument41 Star3)
	(supports instrument42 infrared3)
	(supports instrument42 infrared4)
	(calibration_target instrument42 Star8)
	(calibration_target instrument42 GroundStation0)
	(calibration_target instrument42 GroundStation2)
	(supports instrument43 image1)
	(supports instrument43 infrared4)
	(calibration_target instrument43 Star7)
	(calibration_target instrument43 Star11)
	(supports instrument44 image0)
	(calibration_target instrument44 Star12)
	(calibration_target instrument44 Star9)
	(calibration_target instrument44 Star7)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star11)
	(supports instrument45 infrared3)
	(calibration_target instrument45 GroundStation13)
	(calibration_target instrument45 Star7)
	(calibration_target instrument45 Star11)
	(calibration_target instrument45 Star3)
	(supports instrument46 image1)
	(calibration_target instrument46 Star12)
	(calibration_target instrument46 GroundStation0)
	(supports instrument47 infrared3)
	(supports instrument47 infrared2)
	(calibration_target instrument47 Star7)
	(calibration_target instrument47 Star1)
	(supports instrument48 image0)
	(supports instrument48 infrared4)
	(calibration_target instrument48 GroundStation4)
	(supports instrument49 image1)
	(supports instrument49 infrared2)
	(calibration_target instrument49 GroundStation4)
	(calibration_target instrument49 Star3)
	(supports instrument50 image0)
	(supports instrument50 infrared3)
	(calibration_target instrument50 Star7)
	(calibration_target instrument50 Star12)
	(calibration_target instrument50 Star9)
	(calibration_target instrument50 GroundStation2)
	(supports instrument51 infrared3)
	(supports instrument51 infrared2)
	(calibration_target instrument51 Star11)
	(calibration_target instrument51 GroundStation2)
	(calibration_target instrument51 Star12)
	(supports instrument52 image0)
	(supports instrument52 image1)
	(calibration_target instrument52 Star11)
	(calibration_target instrument52 GroundStation6)
	(calibration_target instrument52 GroundStation5)
	(supports instrument53 infrared4)
	(calibration_target instrument53 Star8)
	(calibration_target instrument53 GroundStation6)
	(supports instrument54 infrared2)
	(supports instrument54 image1)
	(supports instrument54 infrared3)
	(calibration_target instrument54 GroundStation0)
	(calibration_target instrument54 Star12)
	(calibration_target instrument54 Star3)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star9)
	(supports instrument55 infrared2)
	(supports instrument55 image1)
	(supports instrument55 infrared4)
	(calibration_target instrument55 Star9)
	(calibration_target instrument55 Star12)
	(calibration_target instrument55 GroundStation0)
	(calibration_target instrument55 GroundStation6)
	(supports instrument56 infrared2)
	(supports instrument56 image1)
	(supports instrument56 image0)
	(calibration_target instrument56 GroundStation10)
	(calibration_target instrument56 GroundStation6)
	(supports instrument57 infrared2)
	(calibration_target instrument57 GroundStation5)
	(calibration_target instrument57 GroundStation4)
	(supports instrument58 infrared4)
	(supports instrument58 infrared3)
	(supports instrument58 image1)
	(calibration_target instrument58 GroundStation10)
	(supports instrument59 infrared3)
	(supports instrument59 infrared2)
	(calibration_target instrument59 Star9)
	(supports instrument60 image0)
	(supports instrument60 image1)
	(supports instrument60 infrared3)
	(calibration_target instrument60 GroundStation2)
	(calibration_target instrument60 Star7)
	(calibration_target instrument60 Star9)
	(calibration_target instrument60 GroundStation10)
	(supports instrument61 infrared3)
	(supports instrument61 image0)
	(supports instrument61 infrared4)
	(calibration_target instrument61 GroundStation10)
	(calibration_target instrument61 Star12)
	(calibration_target instrument61 GroundStation2)
	(calibration_target instrument61 Star8)
	(supports instrument62 image1)
	(supports instrument62 infrared2)
	(calibration_target instrument62 Star9)
	(calibration_target instrument62 Star12)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(on_board instrument61 satellite8)
	(on_board instrument62 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star9)
	(supports instrument63 infrared4)
	(supports instrument63 infrared2)
	(calibration_target instrument63 GroundStation4)
	(calibration_target instrument63 Star7)
	(supports instrument64 image0)
	(calibration_target instrument64 GroundStation10)
	(supports instrument65 infrared2)
	(calibration_target instrument65 Star12)
	(calibration_target instrument65 Star9)
	(supports instrument66 infrared4)
	(calibration_target instrument66 GroundStation13)
	(supports instrument67 infrared3)
	(supports instrument67 infrared4)
	(calibration_target instrument67 Star1)
	(calibration_target instrument67 GroundStation4)
	(calibration_target instrument67 GroundStation6)
	(supports instrument68 infrared4)
	(supports instrument68 image0)
	(calibration_target instrument68 Star11)
	(calibration_target instrument68 GroundStation2)
	(calibration_target instrument68 Star3)
	(calibration_target instrument68 GroundStation13)
	(supports instrument69 infrared4)
	(supports instrument69 image0)
	(supports instrument69 infrared3)
	(calibration_target instrument69 GroundStation10)
	(supports instrument70 infrared2)
	(calibration_target instrument70 Star9)
	(calibration_target instrument70 Star7)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(on_board instrument68 satellite9)
	(on_board instrument69 satellite9)
	(on_board instrument70 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star3)
)
(:goal (and
	(pointing satellite2 GroundStation2)
	(pointing satellite3 Star12)
	(pointing satellite5 GroundStation0)
	(pointing satellite6 GroundStation4)
	(pointing satellite9 GroundStation10)
	(have_image Star15 image1)
))

)
