(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite4 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite5 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite7 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	satellite9 - satellite
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	thermograph2 - mode
	thermograph3 - mode
	thermograph0 - mode
	image1 - mode
	thermograph4 - mode
	GroundStation10 - direction
	GroundStation12 - direction
	Star3 - direction
	Star4 - direction
	Star8 - direction
	GroundStation15 - direction
	GroundStation13 - direction
	Star0 - direction
	GroundStation6 - direction
	GroundStation11 - direction
	GroundStation2 - direction
	Star9 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation14 - direction
	GroundStation7 - direction
	Planet16 - direction
	Phenomenon17 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 GroundStation14)
	(supports instrument1 thermograph3)
	(supports instrument1 thermograph2)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 Star3)
	(supports instrument2 image1)
	(supports instrument2 thermograph3)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation15)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument3 thermograph4)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 GroundStation15)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 GroundStation12)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 GroundStation6)
	(calibration_target instrument5 GroundStation15)
	(calibration_target instrument5 GroundStation14)
	(supports instrument6 thermograph0)
	(supports instrument6 image1)
	(supports instrument6 thermograph3)
	(calibration_target instrument6 Star0)
	(supports instrument7 thermograph4)
	(supports instrument7 thermograph3)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation15)
	(calibration_target instrument7 GroundStation2)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star8)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 GroundStation11)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 Star9)
	(supports instrument10 thermograph3)
	(calibration_target instrument10 GroundStation15)
	(calibration_target instrument10 Star0)
	(supports instrument11 thermograph0)
	(supports instrument11 image1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 image1)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 GroundStation14)
	(calibration_target instrument12 Star0)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 Star8)
	(supports instrument14 thermograph2)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation15)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation13)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 GroundStation15)
	(calibration_target instrument15 GroundStation7)
	(calibration_target instrument15 GroundStation11)
	(calibration_target instrument15 GroundStation14)
	(supports instrument16 thermograph3)
	(supports instrument16 thermograph4)
	(supports instrument16 image1)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation14)
	(calibration_target instrument16 GroundStation11)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument17 thermograph2)
	(supports instrument17 thermograph4)
	(supports instrument17 image1)
	(calibration_target instrument17 GroundStation15)
	(supports instrument18 thermograph4)
	(supports instrument18 thermograph3)
	(supports instrument18 image1)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation12)
	(calibration_target instrument18 GroundStation10)
	(supports instrument19 thermograph4)
	(supports instrument19 image1)
	(calibration_target instrument19 Star8)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 GroundStation12)
	(supports instrument22 image1)
	(supports instrument22 thermograph2)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 Star1)
	(calibration_target instrument22 GroundStation13)
	(calibration_target instrument22 GroundStation10)
	(calibration_target instrument22 GroundStation15)
	(calibration_target instrument22 GroundStation5)
	(supports instrument23 image1)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 GroundStation13)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 GroundStation11)
	(calibration_target instrument23 Star8)
	(calibration_target instrument23 Star9)
	(supports instrument24 thermograph4)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 GroundStation5)
	(calibration_target instrument24 GroundStation14)
	(calibration_target instrument24 Star1)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet16)
	(supports instrument25 image1)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 GroundStation12)
	(calibration_target instrument25 Star3)
	(calibration_target instrument25 GroundStation13)
	(calibration_target instrument25 GroundStation11)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 Star4)
	(calibration_target instrument26 GroundStation12)
	(supports instrument27 thermograph0)
	(supports instrument27 thermograph3)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 Star8)
	(calibration_target instrument27 Star4)
	(supports instrument28 thermograph0)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation10)
	(calibration_target instrument28 Star3)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 thermograph2)
	(supports instrument29 thermograph3)
	(supports instrument29 image1)
	(calibration_target instrument29 GroundStation12)
	(calibration_target instrument29 GroundStation15)
	(supports instrument30 thermograph4)
	(supports instrument30 thermograph0)
	(supports instrument30 image1)
	(calibration_target instrument30 Star8)
	(calibration_target instrument30 GroundStation15)
	(calibration_target instrument30 Star0)
	(supports instrument31 image1)
	(supports instrument31 thermograph2)
	(calibration_target instrument31 GroundStation15)
	(calibration_target instrument31 Star4)
	(supports instrument32 image1)
	(supports instrument32 thermograph2)
	(calibration_target instrument32 GroundStation15)
	(calibration_target instrument32 GroundStation7)
	(supports instrument33 thermograph2)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 GroundStation12)
	(calibration_target instrument33 GroundStation13)
	(calibration_target instrument33 Star9)
	(calibration_target instrument33 Star8)
	(calibration_target instrument33 Star4)
	(supports instrument34 thermograph2)
	(calibration_target instrument34 GroundStation7)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star9)
	(supports instrument35 thermograph3)
	(supports instrument35 thermograph2)
	(supports instrument35 image1)
	(calibration_target instrument35 GroundStation15)
	(calibration_target instrument35 GroundStation5)
	(supports instrument36 thermograph3)
	(supports instrument36 image1)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 GroundStation6)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 Star9)
	(calibration_target instrument36 Star4)
	(supports instrument37 thermograph0)
	(supports instrument37 thermograph2)
	(calibration_target instrument37 GroundStation5)
	(calibration_target instrument37 Star8)
	(calibration_target instrument37 Star3)
	(calibration_target instrument37 Star4)
	(supports instrument38 thermograph4)
	(supports instrument38 thermograph0)
	(supports instrument38 thermograph2)
	(calibration_target instrument38 GroundStation13)
	(calibration_target instrument38 GroundStation6)
	(calibration_target instrument38 GroundStation15)
	(calibration_target instrument38 Star8)
	(supports instrument39 thermograph0)
	(supports instrument39 thermograph2)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 GroundStation5)
	(calibration_target instrument39 GroundStation12)
	(calibration_target instrument39 GroundStation7)
	(calibration_target instrument39 Star1)
	(calibration_target instrument39 GroundStation14)
	(supports instrument40 thermograph4)
	(supports instrument40 image1)
	(calibration_target instrument40 Star8)
	(supports instrument41 thermograph3)
	(calibration_target instrument41 Star1)
	(calibration_target instrument41 GroundStation13)
	(supports instrument42 thermograph2)
	(supports instrument42 image1)
	(supports instrument42 thermograph3)
	(calibration_target instrument42 GroundStation11)
	(calibration_target instrument42 GroundStation14)
	(calibration_target instrument42 GroundStation5)
	(calibration_target instrument42 GroundStation12)
	(supports instrument43 thermograph4)
	(calibration_target instrument43 GroundStation12)
	(calibration_target instrument43 Star0)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation5)
	(supports instrument44 image1)
	(supports instrument44 thermograph3)
	(supports instrument44 thermograph2)
	(calibration_target instrument44 GroundStation13)
	(calibration_target instrument44 Star9)
	(supports instrument45 thermograph3)
	(calibration_target instrument45 Star9)
	(supports instrument46 image1)
	(calibration_target instrument46 GroundStation15)
	(calibration_target instrument46 Star9)
	(calibration_target instrument46 GroundStation11)
	(supports instrument47 thermograph4)
	(supports instrument47 thermograph2)
	(calibration_target instrument47 GroundStation6)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation12)
	(supports instrument48 thermograph4)
	(supports instrument48 thermograph2)
	(supports instrument48 thermograph0)
	(calibration_target instrument48 GroundStation14)
	(supports instrument49 thermograph3)
	(supports instrument49 thermograph0)
	(supports instrument49 thermograph2)
	(calibration_target instrument49 GroundStation11)
	(calibration_target instrument49 Star0)
	(calibration_target instrument49 Star8)
	(calibration_target instrument49 GroundStation15)
	(supports instrument50 thermograph4)
	(supports instrument50 image1)
	(calibration_target instrument50 GroundStation5)
	(calibration_target instrument50 GroundStation15)
	(calibration_target instrument50 GroundStation11)
	(calibration_target instrument50 Star8)
	(calibration_target instrument50 GroundStation6)
	(supports instrument51 image1)
	(supports instrument51 thermograph2)
	(calibration_target instrument51 GroundStation14)
	(calibration_target instrument51 Star4)
	(calibration_target instrument51 Star3)
	(calibration_target instrument51 GroundStation7)
	(supports instrument52 thermograph3)
	(supports instrument52 thermograph0)
	(supports instrument52 image1)
	(calibration_target instrument52 GroundStation6)
	(supports instrument53 thermograph2)
	(calibration_target instrument53 GroundStation6)
	(calibration_target instrument53 GroundStation12)
	(calibration_target instrument53 GroundStation11)
	(calibration_target instrument53 Star3)
	(supports instrument54 thermograph2)
	(supports instrument54 thermograph4)
	(calibration_target instrument54 Star4)
	(calibration_target instrument54 GroundStation11)
	(calibration_target instrument54 Star3)
	(calibration_target instrument54 GroundStation14)
	(supports instrument55 thermograph0)
	(supports instrument55 image1)
	(supports instrument55 thermograph2)
	(calibration_target instrument55 Star1)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation12)
	(supports instrument56 thermograph0)
	(calibration_target instrument56 GroundStation15)
	(calibration_target instrument56 Star8)
	(calibration_target instrument56 GroundStation5)
	(calibration_target instrument56 Star9)
	(supports instrument57 image1)
	(supports instrument57 thermograph4)
	(supports instrument57 thermograph2)
	(calibration_target instrument57 Star0)
	(calibration_target instrument57 GroundStation7)
	(supports instrument58 thermograph4)
	(calibration_target instrument58 GroundStation11)
	(calibration_target instrument58 GroundStation13)
	(calibration_target instrument58 GroundStation7)
	(supports instrument59 thermograph4)
	(calibration_target instrument59 Star0)
	(calibration_target instrument59 GroundStation5)
	(supports instrument60 thermograph4)
	(calibration_target instrument60 GroundStation2)
	(calibration_target instrument60 GroundStation11)
	(calibration_target instrument60 GroundStation6)
	(calibration_target instrument60 Star0)
	(supports instrument61 image1)
	(supports instrument61 thermograph0)
	(supports instrument61 thermograph3)
	(calibration_target instrument61 GroundStation14)
	(calibration_target instrument61 GroundStation5)
	(calibration_target instrument61 Star1)
	(calibration_target instrument61 Star9)
	(calibration_target instrument61 GroundStation7)
	(supports instrument62 thermograph4)
	(calibration_target instrument62 GroundStation7)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation15)
)
(:goal (and
	(pointing satellite2 GroundStation10)
	(pointing satellite3 Star0)
	(pointing satellite5 GroundStation15)
	(pointing satellite8 GroundStation5)
	(pointing satellite9 GroundStation2)
	(have_image Phenomenon17 image1)
))

)
