(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite1 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite2 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite3 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite4 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite5 - satellite
	instrument37 - instrument
	instrument38 - instrument
	satellite6 - satellite
	instrument39 - instrument
	instrument40 - instrument
	satellite7 - satellite
	instrument41 - instrument
	instrument42 - instrument
	satellite8 - satellite
	instrument43 - instrument
	instrument44 - instrument
	satellite9 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	image2 - mode
	infrared1 - mode
	spectrograph0 - mode
	image3 - mode
	image4 - mode
	Star6 - direction
	Star7 - direction
	Star3 - direction
	Star8 - direction
	GroundStation10 - direction
	GroundStation9 - direction
	Star15 - direction
	GroundStation11 - direction
	Star12 - direction
	Star0 - direction
	Star14 - direction
	GroundStation4 - direction
	Star13 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star5 - direction
	Planet16 - direction
	Phenomenon17 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 image4)
	(supports instrument0 image2)
	(calibration_target instrument0 GroundStation11)
	(calibration_target instrument0 GroundStation10)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 Star15)
	(supports instrument1 spectrograph0)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 image2)
	(supports instrument2 image4)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 Star13)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star15)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 image2)
	(supports instrument4 spectrograph0)
	(supports instrument4 image4)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star14)
	(calibration_target instrument4 Star7)
	(supports instrument5 image4)
	(supports instrument5 image2)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 Star8)
	(supports instrument6 image3)
	(supports instrument6 infrared1)
	(supports instrument6 image2)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 GroundStation11)
	(supports instrument7 image3)
	(calibration_target instrument7 Star6)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 image4)
	(supports instrument9 image2)
	(supports instrument9 image3)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 GroundStation10)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet16)
	(supports instrument10 image3)
	(calibration_target instrument10 Star13)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 GroundStation9)
	(calibration_target instrument10 Star14)
	(calibration_target instrument10 Star8)
	(supports instrument11 image4)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 Star3)
	(supports instrument12 image2)
	(supports instrument12 image4)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 Star7)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 Star5)
	(supports instrument13 image4)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 image2)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation11)
	(calibration_target instrument14 Star15)
	(supports instrument15 infrared1)
	(supports instrument15 image3)
	(supports instrument15 image4)
	(calibration_target instrument15 GroundStation4)
	(calibration_target instrument15 GroundStation10)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 GroundStation9)
	(calibration_target instrument15 Star15)
	(supports instrument16 image4)
	(supports instrument16 infrared1)
	(supports instrument16 image2)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 spectrograph0)
	(supports instrument17 image4)
	(supports instrument17 image3)
	(calibration_target instrument17 Star6)
	(calibration_target instrument17 GroundStation1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star13)
	(supports instrument18 image2)
	(supports instrument18 image3)
	(supports instrument18 image4)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 Star6)
	(calibration_target instrument18 GroundStation11)
	(supports instrument19 image4)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star13)
	(calibration_target instrument19 GroundStation11)
	(calibration_target instrument19 GroundStation4)
	(supports instrument20 image2)
	(supports instrument20 infrared1)
	(supports instrument20 image4)
	(calibration_target instrument20 Star7)
	(calibration_target instrument20 Star15)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 Star12)
	(calibration_target instrument20 GroundStation9)
	(supports instrument21 image2)
	(supports instrument21 infrared1)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 GroundStation2)
	(calibration_target instrument21 GroundStation1)
	(supports instrument22 image2)
	(calibration_target instrument22 Star6)
	(supports instrument23 spectrograph0)
	(supports instrument23 infrared1)
	(supports instrument23 image4)
	(calibration_target instrument23 GroundStation11)
	(calibration_target instrument23 Star13)
	(calibration_target instrument23 Star5)
	(calibration_target instrument23 GroundStation2)
	(supports instrument24 image3)
	(supports instrument24 image2)
	(calibration_target instrument24 GroundStation11)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 GroundStation9)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(on_board instrument24 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation1)
	(supports instrument25 image3)
	(supports instrument25 infrared1)
	(calibration_target instrument25 Star8)
	(calibration_target instrument25 GroundStation4)
	(calibration_target instrument25 GroundStation11)
	(calibration_target instrument25 Star14)
	(calibration_target instrument25 Star6)
	(supports instrument26 image4)
	(supports instrument26 image2)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 Star12)
	(calibration_target instrument26 Star15)
	(calibration_target instrument26 Star8)
	(supports instrument27 image4)
	(calibration_target instrument27 Star12)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 GroundStation9)
	(supports instrument28 image2)
	(calibration_target instrument28 GroundStation1)
	(calibration_target instrument28 GroundStation9)
	(calibration_target instrument28 Star6)
	(calibration_target instrument28 Star12)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 image2)
	(calibration_target instrument29 Star14)
	(calibration_target instrument29 GroundStation10)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 Star8)
	(supports instrument30 spectrograph0)
	(supports instrument30 image3)
	(calibration_target instrument30 GroundStation10)
	(calibration_target instrument30 Star0)
	(calibration_target instrument30 Star6)
	(calibration_target instrument30 Star5)
	(calibration_target instrument30 Star7)
	(supports instrument31 infrared1)
	(calibration_target instrument31 Star15)
	(calibration_target instrument31 Star13)
	(supports instrument32 infrared1)
	(supports instrument32 spectrograph0)
	(supports instrument32 image3)
	(calibration_target instrument32 GroundStation9)
	(calibration_target instrument32 GroundStation1)
	(calibration_target instrument32 Star7)
	(supports instrument33 infrared1)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 Star12)
	(calibration_target instrument33 Star6)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(on_board instrument32 satellite3)
	(on_board instrument33 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star14)
	(supports instrument34 image3)
	(calibration_target instrument34 GroundStation10)
	(calibration_target instrument34 Star12)
	(supports instrument35 image4)
	(supports instrument35 image2)
	(supports instrument35 spectrograph0)
	(calibration_target instrument35 Star13)
	(calibration_target instrument35 Star12)
	(supports instrument36 image4)
	(calibration_target instrument36 GroundStation1)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star12)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation1)
	(supports instrument37 image2)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 Star12)
	(calibration_target instrument37 GroundStation2)
	(supports instrument38 infrared1)
	(calibration_target instrument38 Star13)
	(calibration_target instrument38 GroundStation11)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet16)
	(supports instrument39 spectrograph0)
	(supports instrument39 image3)
	(calibration_target instrument39 GroundStation10)
	(supports instrument40 spectrograph0)
	(supports instrument40 image4)
	(supports instrument40 image2)
	(calibration_target instrument40 Star12)
	(calibration_target instrument40 GroundStation4)
	(calibration_target instrument40 Star7)
	(calibration_target instrument40 Star13)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star14)
	(supports instrument41 image3)
	(supports instrument41 image2)
	(supports instrument41 infrared1)
	(calibration_target instrument41 Star3)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 GroundStation1)
	(supports instrument42 infrared1)
	(calibration_target instrument42 Star15)
	(calibration_target instrument42 Star8)
	(calibration_target instrument42 GroundStation2)
	(calibration_target instrument42 Star3)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star13)
	(supports instrument43 image4)
	(supports instrument43 infrared1)
	(supports instrument43 image3)
	(calibration_target instrument43 GroundStation9)
	(calibration_target instrument43 GroundStation10)
	(calibration_target instrument43 Star12)
	(supports instrument44 image3)
	(supports instrument44 infrared1)
	(calibration_target instrument44 Star5)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star12)
	(supports instrument45 image2)
	(calibration_target instrument45 GroundStation11)
	(calibration_target instrument45 Star15)
	(supports instrument46 image4)
	(supports instrument46 spectrograph0)
	(calibration_target instrument46 Star12)
	(calibration_target instrument46 GroundStation4)
	(supports instrument47 spectrograph0)
	(supports instrument47 image4)
	(calibration_target instrument47 Star0)
	(supports instrument48 infrared1)
	(calibration_target instrument48 Star13)
	(calibration_target instrument48 Star5)
	(calibration_target instrument48 GroundStation2)
	(supports instrument49 image4)
	(supports instrument49 image3)
	(calibration_target instrument49 GroundStation4)
	(calibration_target instrument49 Star5)
	(calibration_target instrument49 Star13)
	(calibration_target instrument49 Star14)
	(supports instrument50 image3)
	(supports instrument50 spectrograph0)
	(supports instrument50 image4)
	(calibration_target instrument50 GroundStation1)
	(calibration_target instrument50 Star13)
	(supports instrument51 image4)
	(calibration_target instrument51 Star5)
	(calibration_target instrument51 GroundStation2)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite1 GroundStation1)
	(pointing satellite6 Star8)
	(pointing satellite7 Planet16)
	(have_image Planet16 image4)
))

)
