(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite4 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite5 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite6 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	satellite7 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	satellite8 - satellite
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	satellite9 - satellite
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	spectrograph4 - mode
	thermograph0 - mode
	infrared2 - mode
	thermograph3 - mode
	image1 - mode
	GroundStation4 - direction
	Star14 - direction
	Star6 - direction
	GroundStation3 - direction
	GroundStation8 - direction
	Star0 - direction
	Star5 - direction
	GroundStation12 - direction
	GroundStation1 - direction
	GroundStation13 - direction
	GroundStation15 - direction
	GroundStation10 - direction
	GroundStation9 - direction
	Star2 - direction
	GroundStation11 - direction
	Star7 - direction
	Phenomenon16 - direction
	Planet17 - direction
)
(:init
	(supports instrument0 spectrograph4)
	(supports instrument0 image1)
	(calibration_target instrument0 Star7)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation11)
	(supports instrument1 thermograph3)
	(supports instrument1 image1)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 GroundStation10)
	(supports instrument2 infrared2)
	(supports instrument2 thermograph0)
	(supports instrument2 image1)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 Star14)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 GroundStation15)
	(supports instrument3 thermograph0)
	(supports instrument3 spectrograph4)
	(supports instrument3 image1)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 GroundStation8)
	(supports instrument4 thermograph0)
	(supports instrument4 spectrograph4)
	(calibration_target instrument4 GroundStation11)
	(supports instrument5 thermograph3)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 GroundStation3)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 Star14)
	(supports instrument6 spectrograph4)
	(supports instrument6 infrared2)
	(calibration_target instrument6 GroundStation8)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 Star0)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation10)
	(supports instrument8 thermograph3)
	(supports instrument8 infrared2)
	(supports instrument8 spectrograph4)
	(calibration_target instrument8 GroundStation3)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 GroundStation13)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 Star6)
	(supports instrument9 image1)
	(calibration_target instrument9 GroundStation12)
	(supports instrument10 image1)
	(calibration_target instrument10 GroundStation15)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 GroundStation12)
	(supports instrument11 image1)
	(supports instrument11 infrared2)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation9)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star14)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation13)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 GroundStation8)
	(supports instrument13 thermograph0)
	(supports instrument13 spectrograph4)
	(supports instrument13 infrared2)
	(calibration_target instrument13 Star14)
	(supports instrument14 spectrograph4)
	(calibration_target instrument14 GroundStation15)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation10)
	(supports instrument15 thermograph3)
	(supports instrument15 infrared2)
	(supports instrument15 image1)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star14)
	(supports instrument16 spectrograph4)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 GroundStation3)
	(calibration_target instrument16 GroundStation12)
	(supports instrument17 spectrograph4)
	(supports instrument17 infrared2)
	(calibration_target instrument17 GroundStation3)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 Star0)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation12)
	(supports instrument18 image1)
	(supports instrument18 infrared2)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 image1)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation15)
	(calibration_target instrument19 GroundStation9)
	(calibration_target instrument19 Star5)
	(calibration_target instrument19 Star0)
	(supports instrument20 thermograph0)
	(supports instrument20 spectrograph4)
	(supports instrument20 infrared2)
	(calibration_target instrument20 GroundStation13)
	(calibration_target instrument20 Star2)
	(supports instrument21 thermograph3)
	(supports instrument21 image1)
	(supports instrument21 infrared2)
	(calibration_target instrument21 GroundStation9)
	(calibration_target instrument21 Star7)
	(calibration_target instrument21 GroundStation11)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 GroundStation12)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument22 image1)
	(supports instrument22 thermograph0)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star2)
	(supports instrument23 thermograph3)
	(calibration_target instrument23 GroundStation3)
	(supports instrument24 spectrograph4)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 Star5)
	(supports instrument25 infrared2)
	(supports instrument25 image1)
	(supports instrument25 thermograph0)
	(calibration_target instrument25 GroundStation4)
	(supports instrument26 spectrograph4)
	(supports instrument26 thermograph0)
	(supports instrument26 infrared2)
	(calibration_target instrument26 GroundStation15)
	(calibration_target instrument26 Star7)
	(supports instrument27 thermograph3)
	(supports instrument27 spectrograph4)
	(supports instrument27 thermograph0)
	(calibration_target instrument27 GroundStation15)
	(calibration_target instrument27 GroundStation10)
	(supports instrument28 thermograph3)
	(supports instrument28 infrared2)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 GroundStation15)
	(calibration_target instrument28 GroundStation9)
	(calibration_target instrument28 Star6)
	(supports instrument29 infrared2)
	(supports instrument29 thermograph3)
	(supports instrument29 thermograph0)
	(calibration_target instrument29 GroundStation8)
	(calibration_target instrument29 GroundStation10)
	(calibration_target instrument29 Star14)
	(supports instrument30 spectrograph4)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 GroundStation1)
	(calibration_target instrument30 GroundStation15)
	(calibration_target instrument30 Star7)
	(calibration_target instrument30 Star2)
	(calibration_target instrument30 Star0)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon16)
	(supports instrument31 image1)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 GroundStation11)
	(supports instrument32 infrared2)
	(supports instrument32 spectrograph4)
	(supports instrument32 thermograph0)
	(calibration_target instrument32 GroundStation12)
	(calibration_target instrument32 GroundStation3)
	(calibration_target instrument32 GroundStation1)
	(supports instrument33 thermograph3)
	(supports instrument33 infrared2)
	(supports instrument33 spectrograph4)
	(calibration_target instrument33 GroundStation8)
	(calibration_target instrument33 GroundStation13)
	(supports instrument34 thermograph3)
	(calibration_target instrument34 GroundStation13)
	(calibration_target instrument34 Star5)
	(calibration_target instrument34 GroundStation12)
	(calibration_target instrument34 Star14)
	(supports instrument35 infrared2)
	(supports instrument35 thermograph0)
	(supports instrument35 thermograph3)
	(calibration_target instrument35 Star2)
	(supports instrument36 spectrograph4)
	(calibration_target instrument36 GroundStation9)
	(calibration_target instrument36 Star6)
	(calibration_target instrument36 Star2)
	(calibration_target instrument36 GroundStation4)
	(supports instrument37 spectrograph4)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star14)
	(calibration_target instrument37 GroundStation4)
	(calibration_target instrument37 GroundStation13)
	(supports instrument38 thermograph3)
	(supports instrument38 infrared2)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation10)
	(supports instrument39 thermograph0)
	(supports instrument39 image1)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 GroundStation3)
	(calibration_target instrument39 GroundStation4)
	(calibration_target instrument39 GroundStation15)
	(calibration_target instrument39 GroundStation8)
	(supports instrument40 thermograph3)
	(supports instrument40 image1)
	(calibration_target instrument40 Star2)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation15)
	(supports instrument41 thermograph3)
	(supports instrument41 thermograph0)
	(calibration_target instrument41 GroundStation9)
	(calibration_target instrument41 Star7)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 GroundStation12)
	(supports instrument42 spectrograph4)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 Star2)
	(calibration_target instrument42 GroundStation10)
	(supports instrument43 spectrograph4)
	(calibration_target instrument43 Star14)
	(calibration_target instrument43 GroundStation15)
	(calibration_target instrument43 Star2)
	(calibration_target instrument43 GroundStation8)
	(supports instrument44 infrared2)
	(calibration_target instrument44 Star14)
	(calibration_target instrument44 GroundStation4)
	(calibration_target instrument44 GroundStation13)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation9)
	(supports instrument45 thermograph0)
	(supports instrument45 thermograph3)
	(supports instrument45 image1)
	(calibration_target instrument45 Star5)
	(calibration_target instrument45 Star2)
	(calibration_target instrument45 Star0)
	(calibration_target instrument45 GroundStation8)
	(supports instrument46 spectrograph4)
	(supports instrument46 thermograph3)
	(supports instrument46 infrared2)
	(calibration_target instrument46 GroundStation13)
	(calibration_target instrument46 GroundStation15)
	(calibration_target instrument46 Star2)
	(supports instrument47 infrared2)
	(calibration_target instrument47 GroundStation10)
	(calibration_target instrument47 GroundStation8)
	(calibration_target instrument47 GroundStation15)
	(calibration_target instrument47 GroundStation13)
	(calibration_target instrument47 Star7)
	(supports instrument48 image1)
	(calibration_target instrument48 GroundStation11)
	(supports instrument49 spectrograph4)
	(supports instrument49 infrared2)
	(calibration_target instrument49 GroundStation1)
	(calibration_target instrument49 Star2)
	(calibration_target instrument49 Star6)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation11)
	(supports instrument50 thermograph0)
	(supports instrument50 infrared2)
	(calibration_target instrument50 GroundStation15)
	(supports instrument51 infrared2)
	(supports instrument51 image1)
	(supports instrument51 thermograph3)
	(calibration_target instrument51 Star5)
	(calibration_target instrument51 GroundStation12)
	(calibration_target instrument51 GroundStation10)
	(calibration_target instrument51 Star2)
	(calibration_target instrument51 Star7)
	(supports instrument52 infrared2)
	(calibration_target instrument52 GroundStation3)
	(calibration_target instrument52 Star6)
	(supports instrument53 image1)
	(supports instrument53 thermograph3)
	(calibration_target instrument53 GroundStation12)
	(supports instrument54 thermograph0)
	(calibration_target instrument54 GroundStation9)
	(supports instrument55 spectrograph4)
	(calibration_target instrument55 Star5)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet17)
	(supports instrument56 thermograph3)
	(calibration_target instrument56 GroundStation8)
	(calibration_target instrument56 GroundStation11)
	(calibration_target instrument56 Star0)
	(calibration_target instrument56 GroundStation12)
	(supports instrument57 image1)
	(supports instrument57 thermograph0)
	(supports instrument57 infrared2)
	(calibration_target instrument57 GroundStation10)
	(calibration_target instrument57 GroundStation1)
	(calibration_target instrument57 GroundStation12)
	(calibration_target instrument57 Star0)
	(supports instrument58 spectrograph4)
	(supports instrument58 thermograph3)
	(calibration_target instrument58 GroundStation12)
	(calibration_target instrument58 GroundStation15)
	(supports instrument59 thermograph3)
	(supports instrument59 infrared2)
	(calibration_target instrument59 GroundStation1)
	(calibration_target instrument59 GroundStation12)
	(calibration_target instrument59 Star7)
	(calibration_target instrument59 GroundStation9)
	(calibration_target instrument59 Star5)
	(supports instrument60 image1)
	(supports instrument60 thermograph3)
	(calibration_target instrument60 GroundStation13)
	(supports instrument61 thermograph3)
	(supports instrument61 infrared2)
	(supports instrument61 thermograph0)
	(calibration_target instrument61 GroundStation9)
	(calibration_target instrument61 GroundStation10)
	(calibration_target instrument61 GroundStation15)
	(calibration_target instrument61 GroundStation13)
	(supports instrument62 image1)
	(supports instrument62 thermograph3)
	(calibration_target instrument62 Star7)
	(calibration_target instrument62 GroundStation11)
	(calibration_target instrument62 Star2)
	(calibration_target instrument62 GroundStation9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star7)
)
(:goal (and
	(pointing satellite0 GroundStation12)
	(pointing satellite2 GroundStation9)
	(pointing satellite4 GroundStation10)
	(pointing satellite7 Star6)
	(pointing satellite8 GroundStation12)
	(have_image Phenomenon16 thermograph3)
	(have_image Planet17 thermograph3)
))

)
