(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite5 - satellite
	instrument25 - instrument
	instrument26 - instrument
	satellite6 - satellite
	instrument27 - instrument
	instrument28 - instrument
	satellite7 - satellite
	instrument29 - instrument
	instrument30 - instrument
	satellite8 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite9 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	thermograph4 - mode
	image3 - mode
	infrared2 - mode
	infrared0 - mode
	spectrograph1 - mode
	Star11 - direction
	GroundStation14 - direction
	Star8 - direction
	GroundStation1 - direction
	GroundStation6 - direction
	GroundStation13 - direction
	Star9 - direction
	GroundStation12 - direction
	GroundStation7 - direction
	Star4 - direction
	Star3 - direction
	Star10 - direction
	GroundStation5 - direction
	Star0 - direction
	GroundStation2 - direction
	GroundStation15 - direction
	Star16 - direction
	Star17 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 Star11)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 spectrograph1)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star10)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 GroundStation12)
	(supports instrument2 infrared2)
	(supports instrument2 infrared0)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation5)
	(supports instrument3 infrared0)
	(supports instrument3 image3)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star10)
	(supports instrument4 thermograph4)
	(supports instrument4 infrared0)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation12)
	(calibration_target instrument4 Star10)
	(calibration_target instrument4 GroundStation14)
	(calibration_target instrument4 Star3)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 GroundStation7)
	(supports instrument6 spectrograph1)
	(supports instrument6 infrared2)
	(supports instrument6 image3)
	(calibration_target instrument6 Star11)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star10)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation13)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation14)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation7)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 GroundStation6)
	(supports instrument8 infrared2)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 GroundStation15)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation12)
	(supports instrument9 infrared0)
	(supports instrument9 image3)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation13)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star17)
	(supports instrument10 infrared0)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 Star8)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 Star3)
	(supports instrument11 infrared2)
	(supports instrument11 image3)
	(calibration_target instrument11 Star4)
	(supports instrument12 infrared0)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 Star9)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 Star10)
	(calibration_target instrument13 Star3)
	(supports instrument14 image3)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation5)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 Star11)
	(supports instrument15 thermograph4)
	(supports instrument15 infrared2)
	(supports instrument15 spectrograph1)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 Star4)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star10)
	(supports instrument16 infrared2)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 Star10)
	(calibration_target instrument16 GroundStation12)
	(calibration_target instrument16 Star9)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 spectrograph1)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 infrared2)
	(calibration_target instrument18 GroundStation7)
	(supports instrument19 infrared2)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 spectrograph1)
	(supports instrument20 infrared2)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star9)
	(calibration_target instrument20 GroundStation15)
	(calibration_target instrument20 Star4)
	(supports instrument21 infrared2)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 thermograph4)
	(supports instrument22 spectrograph1)
	(supports instrument22 infrared2)
	(calibration_target instrument22 GroundStation6)
	(supports instrument23 spectrograph1)
	(supports instrument23 image3)
	(calibration_target instrument23 Star11)
	(calibration_target instrument23 Star0)
	(supports instrument24 spectrograph1)
	(supports instrument24 thermograph4)
	(supports instrument24 infrared0)
	(calibration_target instrument24 GroundStation15)
	(calibration_target instrument24 GroundStation12)
	(calibration_target instrument24 GroundStation2)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star11)
	(supports instrument25 image3)
	(supports instrument25 infrared0)
	(calibration_target instrument25 GroundStation2)
	(calibration_target instrument25 Star0)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 Star0)
	(calibration_target instrument26 Star10)
	(calibration_target instrument26 Star3)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star11)
	(supports instrument27 thermograph4)
	(supports instrument27 image3)
	(supports instrument27 infrared0)
	(calibration_target instrument27 GroundStation7)
	(calibration_target instrument27 Star10)
	(calibration_target instrument27 Star0)
	(supports instrument28 thermograph4)
	(supports instrument28 spectrograph1)
	(calibration_target instrument28 GroundStation14)
	(calibration_target instrument28 GroundStation12)
	(calibration_target instrument28 Star8)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation5)
	(supports instrument29 spectrograph1)
	(supports instrument29 infrared0)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 Star9)
	(calibration_target instrument29 Star4)
	(supports instrument30 infrared2)
	(calibration_target instrument30 GroundStation15)
	(calibration_target instrument30 GroundStation2)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star10)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 Star8)
	(supports instrument32 infrared2)
	(supports instrument32 thermograph4)
	(calibration_target instrument32 GroundStation1)
	(calibration_target instrument32 Star0)
	(supports instrument33 image3)
	(supports instrument33 thermograph4)
	(supports instrument33 infrared0)
	(calibration_target instrument33 GroundStation2)
	(calibration_target instrument33 GroundStation12)
	(supports instrument34 infrared2)
	(supports instrument34 spectrograph1)
	(supports instrument34 infrared0)
	(calibration_target instrument34 GroundStation6)
	(calibration_target instrument34 Star4)
	(calibration_target instrument34 Star9)
	(supports instrument35 image3)
	(supports instrument35 thermograph4)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 GroundStation15)
	(calibration_target instrument35 GroundStation2)
	(calibration_target instrument35 GroundStation13)
	(calibration_target instrument35 Star3)
	(calibration_target instrument35 GroundStation12)
	(supports instrument36 thermograph4)
	(calibration_target instrument36 GroundStation15)
	(calibration_target instrument36 GroundStation12)
	(calibration_target instrument36 Star4)
	(calibration_target instrument36 GroundStation7)
	(calibration_target instrument36 GroundStation13)
	(supports instrument37 infrared0)
	(supports instrument37 image3)
	(supports instrument37 spectrograph1)
	(calibration_target instrument37 GroundStation2)
	(calibration_target instrument37 GroundStation5)
	(on_board instrument31 satellite8)
	(on_board instrument32 satellite8)
	(on_board instrument33 satellite8)
	(on_board instrument34 satellite8)
	(on_board instrument35 satellite8)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star16)
	(supports instrument38 infrared0)
	(supports instrument38 spectrograph1)
	(calibration_target instrument38 Star4)
	(calibration_target instrument38 GroundStation13)
	(supports instrument39 infrared0)
	(supports instrument39 infrared2)
	(supports instrument39 spectrograph1)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 GroundStation7)
	(calibration_target instrument39 GroundStation12)
	(calibration_target instrument39 Star9)
	(supports instrument40 infrared0)
	(calibration_target instrument40 GroundStation2)
	(calibration_target instrument40 GroundStation15)
	(calibration_target instrument40 GroundStation5)
	(calibration_target instrument40 Star10)
	(calibration_target instrument40 Star3)
	(supports instrument41 spectrograph1)
	(calibration_target instrument41 Star0)
	(supports instrument42 spectrograph1)
	(calibration_target instrument42 GroundStation15)
	(calibration_target instrument42 GroundStation2)
	(on_board instrument38 satellite9)
	(on_board instrument39 satellite9)
	(on_board instrument40 satellite9)
	(on_board instrument41 satellite9)
	(on_board instrument42 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star9)
)
(:goal (and
	(pointing satellite0 GroundStation12)
	(pointing satellite3 GroundStation14)
	(pointing satellite4 GroundStation13)
	(pointing satellite7 Star4)
	(pointing satellite8 GroundStation1)
))

)
