(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite4 - satellite
	instrument17 - instrument
	satellite5 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite6 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite7 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite8 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite9 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	thermograph3 - mode
	infrared2 - mode
	thermograph4 - mode
	spectrograph0 - mode
	infrared1 - mode
	Star2 - direction
	GroundStation15 - direction
	GroundStation11 - direction
	Star5 - direction
	GroundStation13 - direction
	Star0 - direction
	Star12 - direction
	GroundStation10 - direction
	Star8 - direction
	Star4 - direction
	GroundStation7 - direction
	Star6 - direction
	Star3 - direction
	Star14 - direction
	GroundStation1 - direction
	GroundStation9 - direction
	Planet16 - direction
	Planet17 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 spectrograph0)
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star5)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star12)
	(calibration_target instrument1 Star5)
	(supports instrument2 infrared2)
	(supports instrument2 thermograph3)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 GroundStation15)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star4)
	(supports instrument3 infrared2)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 Star6)
	(calibration_target instrument3 Star5)
	(supports instrument4 thermograph3)
	(supports instrument4 infrared2)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 GroundStation13)
	(supports instrument5 thermograph4)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 Star8)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 Star3)
	(supports instrument6 spectrograph0)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star12)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star8)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared1)
	(calibration_target instrument7 GroundStation9)
	(calibration_target instrument7 GroundStation15)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star6)
	(supports instrument9 thermograph3)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 GroundStation9)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation15)
	(calibration_target instrument10 GroundStation10)
	(calibration_target instrument10 GroundStation13)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star8)
	(supports instrument11 infrared1)
	(supports instrument11 spectrograph0)
	(supports instrument11 thermograph3)
	(calibration_target instrument11 Star14)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument12 thermograph3)
	(supports instrument12 infrared2)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 GroundStation11)
	(calibration_target instrument12 Star5)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared2)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 GroundStation9)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 Star2)
	(calibration_target instrument14 GroundStation7)
	(supports instrument15 thermograph4)
	(supports instrument15 infrared1)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 Star14)
	(calibration_target instrument15 GroundStation11)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 Star12)
	(supports instrument16 thermograph4)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star12)
	(calibration_target instrument16 Star8)
	(calibration_target instrument16 GroundStation10)
	(calibration_target instrument16 Star4)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation11)
	(supports instrument17 infrared1)
	(supports instrument17 spectrograph0)
	(supports instrument17 thermograph3)
	(calibration_target instrument17 GroundStation10)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation13)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation7)
	(calibration_target instrument18 Star12)
	(calibration_target instrument18 GroundStation11)
	(calibration_target instrument18 Star14)
	(supports instrument19 thermograph4)
	(supports instrument19 spectrograph0)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 Star4)
	(calibration_target instrument19 GroundStation9)
	(calibration_target instrument19 GroundStation13)
	(calibration_target instrument19 Star6)
	(supports instrument20 thermograph4)
	(supports instrument20 spectrograph0)
	(supports instrument20 thermograph3)
	(calibration_target instrument20 Star2)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 GroundStation11)
	(calibration_target instrument20 GroundStation13)
	(calibration_target instrument20 Star0)
	(supports instrument21 spectrograph0)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 GroundStation9)
	(calibration_target instrument21 GroundStation11)
	(calibration_target instrument21 Star12)
	(supports instrument22 spectrograph0)
	(supports instrument22 thermograph3)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 GroundStation10)
	(calibration_target instrument22 Star14)
	(calibration_target instrument22 Star5)
	(supports instrument23 infrared2)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 GroundStation7)
	(supports instrument24 thermograph3)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 GroundStation13)
	(calibration_target instrument24 Star12)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 Star8)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 GroundStation15)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 GroundStation1)
	(calibration_target instrument25 Star12)
	(supports instrument26 infrared2)
	(calibration_target instrument26 Star12)
	(calibration_target instrument26 GroundStation15)
	(calibration_target instrument26 Star8)
	(calibration_target instrument26 Star4)
	(supports instrument27 thermograph3)
	(supports instrument27 infrared2)
	(calibration_target instrument27 GroundStation10)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 Star6)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument28 thermograph4)
	(supports instrument28 infrared1)
	(calibration_target instrument28 GroundStation9)
	(calibration_target instrument28 GroundStation10)
	(calibration_target instrument28 Star8)
	(calibration_target instrument28 GroundStation11)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 spectrograph0)
	(supports instrument29 infrared1)
	(supports instrument29 thermograph3)
	(calibration_target instrument29 GroundStation7)
	(calibration_target instrument29 Star6)
	(calibration_target instrument29 Star3)
	(supports instrument30 thermograph4)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 Star12)
	(supports instrument31 thermograph4)
	(supports instrument31 infrared1)
	(calibration_target instrument31 Star14)
	(calibration_target instrument31 Star0)
	(calibration_target instrument31 GroundStation13)
	(supports instrument32 thermograph3)
	(supports instrument32 infrared1)
	(calibration_target instrument32 GroundStation10)
	(calibration_target instrument32 GroundStation13)
	(calibration_target instrument32 Star8)
	(calibration_target instrument32 Star14)
	(calibration_target instrument32 GroundStation15)
	(supports instrument33 infrared2)
	(calibration_target instrument33 Star12)
	(calibration_target instrument33 Star5)
	(calibration_target instrument33 GroundStation10)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 GroundStation7)
	(calibration_target instrument34 Star6)
	(calibration_target instrument34 Star12)
	(calibration_target instrument34 GroundStation9)
	(calibration_target instrument34 Star3)
	(supports instrument35 infrared2)
	(supports instrument35 infrared1)
	(supports instrument35 spectrograph0)
	(calibration_target instrument35 GroundStation9)
	(calibration_target instrument35 Star5)
	(calibration_target instrument35 Star4)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument36 thermograph3)
	(supports instrument36 infrared1)
	(calibration_target instrument36 GroundStation10)
	(calibration_target instrument36 GroundStation13)
	(calibration_target instrument36 GroundStation11)
	(calibration_target instrument36 Star5)
	(calibration_target instrument36 Star4)
	(supports instrument37 infrared1)
	(supports instrument37 thermograph3)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 Star12)
	(calibration_target instrument37 GroundStation7)
	(supports instrument38 infrared1)
	(calibration_target instrument38 Star14)
	(supports instrument39 thermograph3)
	(supports instrument39 infrared1)
	(supports instrument39 infrared2)
	(calibration_target instrument39 GroundStation9)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 GroundStation13)
	(supports instrument40 thermograph3)
	(supports instrument40 thermograph4)
	(calibration_target instrument40 Star14)
	(calibration_target instrument40 GroundStation7)
	(supports instrument41 thermograph3)
	(calibration_target instrument41 GroundStation13)
	(calibration_target instrument41 Star5)
	(calibration_target instrument41 Star8)
	(calibration_target instrument41 GroundStation1)
	(supports instrument42 spectrograph0)
	(supports instrument42 thermograph4)
	(supports instrument42 thermograph3)
	(calibration_target instrument42 Star2)
	(calibration_target instrument42 Star12)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation13)
	(supports instrument43 infrared1)
	(supports instrument43 thermograph4)
	(calibration_target instrument43 GroundStation10)
	(calibration_target instrument43 GroundStation9)
	(calibration_target instrument43 Star14)
	(calibration_target instrument43 Star0)
	(calibration_target instrument43 Star2)
	(supports instrument44 infrared2)
	(calibration_target instrument44 Star14)
	(calibration_target instrument44 GroundStation10)
	(supports instrument45 infrared2)
	(supports instrument45 thermograph4)
	(calibration_target instrument45 Star14)
	(calibration_target instrument45 GroundStation10)
	(supports instrument46 thermograph4)
	(supports instrument46 spectrograph0)
	(calibration_target instrument46 GroundStation7)
	(calibration_target instrument46 GroundStation11)
	(calibration_target instrument46 GroundStation15)
	(calibration_target instrument46 GroundStation9)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star2)
	(supports instrument47 thermograph4)
	(supports instrument47 infrared2)
	(calibration_target instrument47 GroundStation1)
	(calibration_target instrument47 Star14)
	(supports instrument48 infrared2)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 Star5)
	(calibration_target instrument48 GroundStation10)
	(supports instrument49 thermograph3)
	(supports instrument49 infrared1)
	(supports instrument49 infrared2)
	(calibration_target instrument49 Star6)
	(calibration_target instrument49 Star0)
	(calibration_target instrument49 GroundStation9)
	(calibration_target instrument49 GroundStation13)
	(calibration_target instrument49 Star14)
	(supports instrument50 thermograph3)
	(supports instrument50 thermograph4)
	(supports instrument50 infrared1)
	(calibration_target instrument50 Star8)
	(supports instrument51 thermograph4)
	(supports instrument51 infrared1)
	(calibration_target instrument51 Star12)
	(calibration_target instrument51 GroundStation9)
	(supports instrument52 infrared1)
	(supports instrument52 thermograph4)
	(supports instrument52 thermograph3)
	(calibration_target instrument52 Star6)
	(calibration_target instrument52 Star12)
	(supports instrument53 thermograph3)
	(calibration_target instrument53 Star4)
	(calibration_target instrument53 Star8)
	(calibration_target instrument53 GroundStation10)
	(supports instrument54 infrared2)
	(supports instrument54 thermograph4)
	(calibration_target instrument54 Star3)
	(calibration_target instrument54 Star6)
	(calibration_target instrument54 GroundStation7)
	(supports instrument55 thermograph4)
	(supports instrument55 infrared1)
	(calibration_target instrument55 Star14)
	(supports instrument56 infrared1)
	(supports instrument56 spectrograph0)
	(supports instrument56 thermograph4)
	(calibration_target instrument56 GroundStation9)
	(calibration_target instrument56 GroundStation1)
	(calibration_target instrument56 Star14)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation1)
)
(:goal (and
	(pointing satellite0 Star0)
	(pointing satellite2 Star3)
	(pointing satellite3 Star0)
	(pointing satellite7 GroundStation7)
	(have_image Planet16 spectrograph0)
	(have_image Planet17 infrared1)
))

)
