(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite2 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite6 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite7 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	satellite8 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite9 - satellite
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	infrared2 - mode
	thermograph0 - mode
	infrared4 - mode
	image1 - mode
	image3 - mode
	GroundStation5 - direction
	Star2 - direction
	Star11 - direction
	Star10 - direction
	GroundStation0 - direction
	GroundStation3 - direction
	GroundStation6 - direction
	GroundStation4 - direction
	Star7 - direction
	Star9 - direction
	GroundStation1 - direction
	GroundStation8 - direction
	Star12 - direction
	Star13 - direction
)
(:init
	(supports instrument0 infrared4)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 GroundStation0)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 Star2)
	(supports instrument2 thermograph0)
	(supports instrument2 image1)
	(supports instrument2 infrared4)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 GroundStation8)
	(supports instrument3 infrared4)
	(supports instrument3 image3)
	(calibration_target instrument3 Star7)
	(supports instrument4 thermograph0)
	(supports instrument4 infrared2)
	(supports instrument4 image3)
	(calibration_target instrument4 GroundStation3)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 thermograph0)
	(supports instrument5 infrared2)
	(supports instrument5 image3)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 Star2)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 Star10)
	(supports instrument7 infrared2)
	(supports instrument7 infrared4)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument8 infrared2)
	(supports instrument8 image1)
	(calibration_target instrument8 Star2)
	(supports instrument9 infrared2)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 thermograph0)
	(supports instrument10 image1)
	(calibration_target instrument10 Star7)
	(supports instrument11 image1)
	(supports instrument11 infrared2)
	(supports instrument11 image3)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 infrared2)
	(supports instrument12 image3)
	(calibration_target instrument12 Star10)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 GroundStation0)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation8)
	(calibration_target instrument13 Star11)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 thermograph0)
	(supports instrument14 image1)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation5)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star9)
	(supports instrument15 infrared4)
	(supports instrument15 image3)
	(supports instrument15 image1)
	(calibration_target instrument15 Star11)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 Star10)
	(supports instrument16 thermograph0)
	(supports instrument16 infrared2)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star11)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star10)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 Star10)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star11)
	(supports instrument18 image1)
	(calibration_target instrument18 Star7)
	(calibration_target instrument18 GroundStation3)
	(calibration_target instrument18 Star2)
	(supports instrument19 thermograph0)
	(supports instrument19 image3)
	(supports instrument19 infrared2)
	(calibration_target instrument19 GroundStation8)
	(supports instrument20 thermograph0)
	(supports instrument20 infrared4)
	(calibration_target instrument20 Star7)
	(calibration_target instrument20 GroundStation0)
	(calibration_target instrument20 Star10)
	(calibration_target instrument20 GroundStation4)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation8)
	(supports instrument21 image1)
	(supports instrument21 infrared2)
	(supports instrument21 image3)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 image3)
	(calibration_target instrument22 GroundStation0)
	(calibration_target instrument22 Star10)
	(calibration_target instrument22 Star9)
	(calibration_target instrument22 GroundStation4)
	(supports instrument23 image3)
	(supports instrument23 infrared2)
	(calibration_target instrument23 Star9)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 image3)
	(calibration_target instrument24 GroundStation5)
	(calibration_target instrument24 Star9)
	(supports instrument25 image1)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 Star11)
	(calibration_target instrument25 GroundStation1)
	(calibration_target instrument25 GroundStation8)
	(supports instrument26 infrared2)
	(calibration_target instrument26 Star11)
	(calibration_target instrument26 Star10)
	(calibration_target instrument26 Star7)
	(supports instrument27 image1)
	(supports instrument27 image3)
	(calibration_target instrument27 GroundStation6)
	(supports instrument28 image3)
	(supports instrument28 thermograph0)
	(calibration_target instrument28 GroundStation8)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation8)
	(supports instrument29 infrared2)
	(calibration_target instrument29 GroundStation5)
	(supports instrument30 image1)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 GroundStation8)
	(calibration_target instrument30 Star7)
	(calibration_target instrument30 GroundStation0)
	(calibration_target instrument30 Star9)
	(supports instrument31 infrared4)
	(supports instrument31 infrared2)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 GroundStation3)
	(calibration_target instrument31 Star9)
	(calibration_target instrument31 GroundStation5)
	(supports instrument32 infrared2)
	(calibration_target instrument32 GroundStation6)
	(calibration_target instrument32 GroundStation8)
	(calibration_target instrument32 Star10)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star9)
	(supports instrument33 thermograph0)
	(supports instrument33 image3)
	(calibration_target instrument33 Star7)
	(calibration_target instrument33 Star2)
	(calibration_target instrument33 GroundStation8)
	(calibration_target instrument33 GroundStation0)
	(supports instrument34 infrared4)
	(calibration_target instrument34 Star11)
	(calibration_target instrument34 Star2)
	(calibration_target instrument34 Star9)
	(supports instrument35 infrared4)
	(supports instrument35 image1)
	(supports instrument35 image3)
	(calibration_target instrument35 GroundStation8)
	(calibration_target instrument35 Star2)
	(calibration_target instrument35 Star10)
	(calibration_target instrument35 GroundStation3)
	(supports instrument36 infrared2)
	(supports instrument36 thermograph0)
	(supports instrument36 infrared4)
	(calibration_target instrument36 Star2)
	(calibration_target instrument36 GroundStation1)
	(calibration_target instrument36 Star11)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star11)
	(supports instrument37 image3)
	(calibration_target instrument37 Star11)
	(calibration_target instrument37 GroundStation5)
	(calibration_target instrument37 GroundStation3)
	(calibration_target instrument37 Star10)
	(supports instrument38 infrared4)
	(supports instrument38 thermograph0)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation8)
	(supports instrument39 infrared2)
	(calibration_target instrument39 GroundStation4)
	(calibration_target instrument39 GroundStation0)
	(calibration_target instrument39 GroundStation6)
	(supports instrument40 image1)
	(calibration_target instrument40 GroundStation1)
	(calibration_target instrument40 GroundStation4)
	(supports instrument41 infrared2)
	(supports instrument41 image3)
	(calibration_target instrument41 Star11)
	(calibration_target instrument41 GroundStation8)
	(supports instrument42 thermograph0)
	(supports instrument42 infrared4)
	(supports instrument42 infrared2)
	(calibration_target instrument42 GroundStation3)
	(calibration_target instrument42 Star7)
	(calibration_target instrument42 GroundStation0)
	(supports instrument43 infrared4)
	(supports instrument43 image1)
	(supports instrument43 image3)
	(calibration_target instrument43 GroundStation5)
	(calibration_target instrument43 Star2)
	(calibration_target instrument43 GroundStation6)
	(calibration_target instrument43 GroundStation8)
	(supports instrument44 infrared4)
	(calibration_target instrument44 GroundStation6)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation3)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 Star2)
	(calibration_target instrument45 GroundStation5)
	(calibration_target instrument45 Star9)
	(supports instrument46 image3)
	(supports instrument46 image1)
	(supports instrument46 thermograph0)
	(calibration_target instrument46 Star10)
	(calibration_target instrument46 Star2)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 image1)
	(supports instrument47 infrared2)
	(supports instrument47 infrared4)
	(calibration_target instrument47 GroundStation5)
	(calibration_target instrument47 Star9)
	(calibration_target instrument47 GroundStation3)
	(calibration_target instrument47 Star7)
	(supports instrument48 thermograph0)
	(calibration_target instrument48 GroundStation4)
	(supports instrument49 infrared4)
	(supports instrument49 infrared2)
	(calibration_target instrument49 GroundStation3)
	(calibration_target instrument49 GroundStation6)
	(calibration_target instrument49 Star7)
	(calibration_target instrument49 Star9)
	(supports instrument50 thermograph0)
	(calibration_target instrument50 Star2)
	(calibration_target instrument50 Star7)
	(supports instrument51 thermograph0)
	(supports instrument51 image1)
	(calibration_target instrument51 Star10)
	(calibration_target instrument51 GroundStation3)
	(supports instrument52 image1)
	(supports instrument52 infrared2)
	(supports instrument52 thermograph0)
	(calibration_target instrument52 Star7)
	(calibration_target instrument52 GroundStation0)
	(supports instrument53 image3)
	(supports instrument53 infrared4)
	(calibration_target instrument53 GroundStation0)
	(calibration_target instrument53 GroundStation3)
	(calibration_target instrument53 Star9)
	(calibration_target instrument53 Star11)
	(supports instrument54 image1)
	(supports instrument54 infrared2)
	(calibration_target instrument54 GroundStation3)
	(calibration_target instrument54 Star9)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star7)
	(supports instrument55 infrared4)
	(supports instrument55 thermograph0)
	(calibration_target instrument55 Star9)
	(calibration_target instrument55 GroundStation8)
	(calibration_target instrument55 GroundStation3)
	(calibration_target instrument55 Star10)
	(supports instrument56 infrared2)
	(supports instrument56 image1)
	(supports instrument56 image3)
	(calibration_target instrument56 GroundStation3)
	(calibration_target instrument56 Star7)
	(calibration_target instrument56 GroundStation6)
	(calibration_target instrument56 GroundStation0)
	(supports instrument57 image1)
	(supports instrument57 thermograph0)
	(calibration_target instrument57 GroundStation3)
	(calibration_target instrument57 GroundStation6)
	(supports instrument58 infrared2)
	(supports instrument58 infrared4)
	(supports instrument58 image1)
	(calibration_target instrument58 Star7)
	(calibration_target instrument58 GroundStation6)
	(supports instrument59 image3)
	(supports instrument59 image1)
	(supports instrument59 thermograph0)
	(calibration_target instrument59 GroundStation4)
	(supports instrument60 thermograph0)
	(supports instrument60 image1)
	(calibration_target instrument60 Star7)
	(supports instrument61 image3)
	(supports instrument61 image1)
	(supports instrument61 infrared4)
	(calibration_target instrument61 GroundStation8)
	(calibration_target instrument61 GroundStation1)
	(calibration_target instrument61 Star9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(on_board instrument61 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite3 Star12)
	(pointing satellite5 Star7)
	(pointing satellite7 GroundStation5)
	(have_image Star12 image1)
	(have_image Star13 thermograph0)
))

)
