(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite5 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite6 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite7 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	satellite8 - satellite
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite9 - satellite
	instrument55 - instrument
	instrument56 - instrument
	infrared0 - mode
	spectrograph3 - mode
	infrared1 - mode
	image2 - mode
	thermograph4 - mode
	Star8 - direction
	Star1 - direction
	Star0 - direction
	Star7 - direction
	GroundStation9 - direction
	GroundStation4 - direction
	Star3 - direction
	Star6 - direction
	GroundStation10 - direction
	GroundStation5 - direction
	Star2 - direction
	Star11 - direction
	Phenomenon12 - direction
	Planet13 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 thermograph4)
	(calibration_target instrument0 Star8)
	(supports instrument1 image2)
	(calibration_target instrument1 Star8)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star3)
	(supports instrument3 infrared0)
	(supports instrument3 spectrograph3)
	(calibration_target instrument3 Star2)
	(supports instrument4 thermograph4)
	(supports instrument4 spectrograph3)
	(supports instrument4 image2)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 Star2)
	(supports instrument5 image2)
	(supports instrument5 thermograph4)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star2)
	(supports instrument6 thermograph4)
	(supports instrument6 infrared0)
	(supports instrument6 image2)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 Star6)
	(supports instrument7 image2)
	(calibration_target instrument7 Star2)
	(calibration_target instrument7 GroundStation10)
	(calibration_target instrument7 Star11)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument9 spectrograph3)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star6)
	(supports instrument10 spectrograph3)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 Star6)
	(calibration_target instrument10 GroundStation9)
	(supports instrument11 spectrograph3)
	(calibration_target instrument11 Star11)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star11)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 Star6)
	(supports instrument13 infrared0)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 GroundStation10)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 Star1)
	(supports instrument14 infrared1)
	(supports instrument14 spectrograph3)
	(supports instrument14 infrared0)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 Star3)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star6)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star8)
	(supports instrument16 infrared1)
	(supports instrument16 spectrograph3)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 Star7)
	(supports instrument17 thermograph4)
	(supports instrument17 image2)
	(calibration_target instrument17 Star6)
	(supports instrument18 thermograph4)
	(supports instrument18 spectrograph3)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation10)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 Star2)
	(supports instrument19 thermograph4)
	(supports instrument19 infrared0)
	(supports instrument19 spectrograph3)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 GroundStation10)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation5)
	(supports instrument20 infrared1)
	(calibration_target instrument20 Star3)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument21 thermograph4)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 GroundStation9)
	(supports instrument22 image2)
	(supports instrument22 spectrograph3)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 GroundStation9)
	(supports instrument23 infrared1)
	(calibration_target instrument23 Star7)
	(calibration_target instrument23 GroundStation4)
	(supports instrument24 infrared0)
	(supports instrument24 image2)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star2)
	(supports instrument25 thermograph4)
	(supports instrument25 infrared0)
	(calibration_target instrument25 Star11)
	(calibration_target instrument25 Star6)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star7)
	(calibration_target instrument26 GroundStation5)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 Star0)
	(supports instrument27 infrared1)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 GroundStation5)
	(calibration_target instrument27 Star1)
	(calibration_target instrument27 GroundStation10)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument28 image2)
	(supports instrument28 spectrograph3)
	(calibration_target instrument28 Star3)
	(supports instrument29 image2)
	(supports instrument29 infrared0)
	(calibration_target instrument29 Star1)
	(supports instrument30 image2)
	(calibration_target instrument30 GroundStation9)
	(calibration_target instrument30 GroundStation5)
	(calibration_target instrument30 Star2)
	(supports instrument31 thermograph4)
	(supports instrument31 infrared1)
	(calibration_target instrument31 Star2)
	(supports instrument32 thermograph4)
	(supports instrument32 infrared1)
	(supports instrument32 image2)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 Star8)
	(supports instrument33 thermograph4)
	(supports instrument33 spectrograph3)
	(supports instrument33 infrared0)
	(calibration_target instrument33 Star8)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 Star0)
	(supports instrument35 spectrograph3)
	(supports instrument35 infrared0)
	(supports instrument35 infrared1)
	(calibration_target instrument35 GroundStation9)
	(supports instrument36 infrared1)
	(calibration_target instrument36 GroundStation10)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 Star8)
	(calibration_target instrument36 Star11)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation10)
	(supports instrument37 infrared0)
	(supports instrument37 image2)
	(supports instrument37 infrared1)
	(calibration_target instrument37 Star11)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 Star6)
	(calibration_target instrument37 Star1)
	(supports instrument38 spectrograph3)
	(supports instrument38 infrared1)
	(supports instrument38 thermograph4)
	(calibration_target instrument38 Star7)
	(calibration_target instrument38 GroundStation9)
	(calibration_target instrument38 Star2)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 Star0)
	(calibration_target instrument39 Star1)
	(calibration_target instrument39 GroundStation9)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument40 infrared0)
	(supports instrument40 thermograph4)
	(supports instrument40 image2)
	(calibration_target instrument40 Star8)
	(supports instrument41 thermograph4)
	(supports instrument41 image2)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 Star7)
	(calibration_target instrument41 GroundStation10)
	(supports instrument42 infrared0)
	(calibration_target instrument42 GroundStation5)
	(supports instrument43 image2)
	(supports instrument43 spectrograph3)
	(calibration_target instrument43 Star8)
	(calibration_target instrument43 Star6)
	(calibration_target instrument43 Star2)
	(supports instrument44 image2)
	(supports instrument44 infrared1)
	(supports instrument44 thermograph4)
	(calibration_target instrument44 GroundStation4)
	(supports instrument45 spectrograph3)
	(supports instrument45 infrared0)
	(supports instrument45 image2)
	(calibration_target instrument45 GroundStation10)
	(calibration_target instrument45 Star7)
	(calibration_target instrument45 Star6)
	(calibration_target instrument45 Star11)
	(supports instrument46 spectrograph3)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 Star2)
	(calibration_target instrument46 Star7)
	(calibration_target instrument46 GroundStation9)
	(calibration_target instrument46 Star11)
	(supports instrument47 spectrograph3)
	(calibration_target instrument47 Star8)
	(supports instrument48 image2)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 GroundStation5)
	(calibration_target instrument48 Star11)
	(calibration_target instrument48 Star1)
	(supports instrument49 spectrograph3)
	(supports instrument49 image2)
	(calibration_target instrument49 Star3)
	(calibration_target instrument49 Star2)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
	(supports instrument50 image2)
	(supports instrument50 infrared1)
	(calibration_target instrument50 Star0)
	(calibration_target instrument50 Star11)
	(calibration_target instrument50 GroundStation10)
	(supports instrument51 infrared0)
	(supports instrument51 thermograph4)
	(supports instrument51 infrared1)
	(calibration_target instrument51 GroundStation5)
	(calibration_target instrument51 GroundStation4)
	(supports instrument52 infrared0)
	(supports instrument52 thermograph4)
	(calibration_target instrument52 GroundStation4)
	(calibration_target instrument52 Star6)
	(calibration_target instrument52 GroundStation9)
	(calibration_target instrument52 Star7)
	(supports instrument53 image2)
	(calibration_target instrument53 Star6)
	(calibration_target instrument53 Star3)
	(supports instrument54 thermograph4)
	(supports instrument54 spectrograph3)
	(calibration_target instrument54 GroundStation5)
	(calibration_target instrument54 GroundStation10)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
	(supports instrument55 image2)
	(calibration_target instrument55 Star2)
	(supports instrument56 thermograph4)
	(supports instrument56 image2)
	(supports instrument56 infrared1)
	(calibration_target instrument56 Star11)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet13)
)
(:goal (and
	(pointing satellite1 Star8)
	(pointing satellite4 GroundStation10)
	(pointing satellite5 GroundStation10)
	(pointing satellite6 Star2)
	(pointing satellite9 Star2)
	(have_image Phenomenon12 infrared1)
	(have_image Planet13 spectrograph3)
))

)
