(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite3 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite4 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite6 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite7 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite8 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite9 - satellite
	instrument55 - instrument
	instrument56 - instrument
	image0 - mode
	spectrograph2 - mode
	infrared4 - mode
	infrared3 - mode
	thermograph1 - mode
	Star4 - direction
	GroundStation1 - direction
	Star3 - direction
	GroundStation9 - direction
	GroundStation0 - direction
	GroundStation11 - direction
	GroundStation5 - direction
	Star7 - direction
	GroundStation6 - direction
	GroundStation8 - direction
	GroundStation2 - direction
	GroundStation10 - direction
	Phenomenon12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation8)
	(supports instrument1 thermograph1)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation6)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 infrared3)
	(supports instrument3 infrared4)
	(calibration_target instrument3 GroundStation2)
	(supports instrument4 image0)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 GroundStation8)
	(calibration_target instrument4 GroundStation0)
	(supports instrument5 thermograph1)
	(supports instrument5 spectrograph2)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation9)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 Star7)
	(supports instrument6 spectrograph2)
	(supports instrument6 infrared3)
	(supports instrument6 image0)
	(calibration_target instrument6 GroundStation0)
	(supports instrument7 image0)
	(supports instrument7 spectrograph2)
	(supports instrument7 infrared4)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 infrared4)
	(supports instrument8 infrared3)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation8)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon13)
	(supports instrument10 infrared4)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation6)
	(supports instrument11 spectrograph2)
	(supports instrument11 image0)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 GroundStation10)
	(supports instrument12 image0)
	(supports instrument12 infrared3)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 GroundStation9)
	(calibration_target instrument12 Star7)
	(supports instrument13 infrared3)
	(calibration_target instrument13 GroundStation9)
	(supports instrument14 image0)
	(calibration_target instrument14 GroundStation9)
	(supports instrument15 image0)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 Star7)
	(calibration_target instrument15 GroundStation0)
	(calibration_target instrument15 GroundStation1)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation10)
	(supports instrument16 spectrograph2)
	(supports instrument16 infrared4)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 GroundStation8)
	(calibration_target instrument16 Star7)
	(supports instrument17 thermograph1)
	(supports instrument17 image0)
	(calibration_target instrument17 Star7)
	(supports instrument18 infrared3)
	(calibration_target instrument18 GroundStation0)
	(calibration_target instrument18 GroundStation11)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 GroundStation1)
	(supports instrument19 thermograph1)
	(supports instrument19 infrared4)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 GroundStation0)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 GroundStation8)
	(calibration_target instrument20 GroundStation0)
	(supports instrument21 thermograph1)
	(supports instrument21 infrared4)
	(calibration_target instrument21 Star3)
	(supports instrument22 infrared3)
	(supports instrument22 thermograph1)
	(supports instrument22 image0)
	(calibration_target instrument22 GroundStation8)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation0)
	(supports instrument23 infrared4)
	(supports instrument23 spectrograph2)
	(supports instrument23 image0)
	(calibration_target instrument23 GroundStation0)
	(calibration_target instrument23 GroundStation9)
	(calibration_target instrument23 GroundStation2)
	(supports instrument24 infrared4)
	(supports instrument24 spectrograph2)
	(calibration_target instrument24 GroundStation9)
	(calibration_target instrument24 GroundStation5)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 GroundStation6)
	(supports instrument25 spectrograph2)
	(supports instrument25 infrared3)
	(calibration_target instrument25 GroundStation9)
	(calibration_target instrument25 Star7)
	(supports instrument26 image0)
	(supports instrument26 infrared4)
	(supports instrument26 thermograph1)
	(calibration_target instrument26 GroundStation11)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation9)
	(calibration_target instrument26 GroundStation10)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument27 thermograph1)
	(supports instrument27 infrared3)
	(supports instrument27 infrared4)
	(calibration_target instrument27 Star3)
	(supports instrument28 infrared4)
	(calibration_target instrument28 Star7)
	(calibration_target instrument28 GroundStation5)
	(calibration_target instrument28 GroundStation11)
	(supports instrument29 spectrograph2)
	(calibration_target instrument29 GroundStation8)
	(calibration_target instrument29 GroundStation10)
	(calibration_target instrument29 GroundStation9)
	(supports instrument30 infrared4)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 GroundStation10)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 GroundStation5)
	(supports instrument31 infrared4)
	(supports instrument31 thermograph1)
	(supports instrument31 spectrograph2)
	(calibration_target instrument31 Star3)
	(calibration_target instrument31 GroundStation11)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 spectrograph2)
	(supports instrument32 infrared4)
	(supports instrument32 infrared3)
	(calibration_target instrument32 GroundStation6)
	(calibration_target instrument32 Star3)
	(calibration_target instrument32 GroundStation5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star7)
	(supports instrument33 infrared3)
	(supports instrument33 infrared4)
	(supports instrument33 spectrograph2)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 image0)
	(supports instrument34 spectrograph2)
	(calibration_target instrument34 GroundStation2)
	(calibration_target instrument34 GroundStation0)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 GroundStation6)
	(supports instrument35 image0)
	(calibration_target instrument35 GroundStation9)
	(calibration_target instrument35 GroundStation2)
	(calibration_target instrument35 GroundStation11)
	(calibration_target instrument35 Star4)
	(supports instrument36 infrared4)
	(supports instrument36 spectrograph2)
	(supports instrument36 infrared3)
	(calibration_target instrument36 GroundStation9)
	(supports instrument37 infrared3)
	(supports instrument37 thermograph1)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 GroundStation9)
	(calibration_target instrument37 Star7)
	(supports instrument38 spectrograph2)
	(supports instrument38 infrared3)
	(supports instrument38 thermograph1)
	(calibration_target instrument38 Star4)
	(calibration_target instrument38 GroundStation6)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 image0)
	(supports instrument39 thermograph1)
	(supports instrument39 infrared3)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 GroundStation9)
	(calibration_target instrument39 GroundStation2)
	(supports instrument40 infrared3)
	(supports instrument40 thermograph1)
	(calibration_target instrument40 GroundStation1)
	(calibration_target instrument40 GroundStation8)
	(supports instrument41 infrared4)
	(supports instrument41 spectrograph2)
	(supports instrument41 infrared3)
	(calibration_target instrument41 Star3)
	(calibration_target instrument41 GroundStation2)
	(calibration_target instrument41 GroundStation0)
	(calibration_target instrument41 Star7)
	(supports instrument42 spectrograph2)
	(supports instrument42 infrared4)
	(calibration_target instrument42 GroundStation10)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument43 infrared4)
	(supports instrument43 thermograph1)
	(supports instrument43 spectrograph2)
	(calibration_target instrument43 GroundStation9)
	(calibration_target instrument43 GroundStation5)
	(supports instrument44 infrared3)
	(calibration_target instrument44 GroundStation8)
	(calibration_target instrument44 GroundStation10)
	(calibration_target instrument44 GroundStation1)
	(calibration_target instrument44 Star3)
	(supports instrument45 thermograph1)
	(supports instrument45 infrared3)
	(calibration_target instrument45 Star7)
	(supports instrument46 image0)
	(supports instrument46 thermograph1)
	(supports instrument46 infrared3)
	(calibration_target instrument46 GroundStation9)
	(calibration_target instrument46 GroundStation2)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon13)
	(supports instrument47 thermograph1)
	(supports instrument47 infrared4)
	(calibration_target instrument47 Star3)
	(calibration_target instrument47 GroundStation8)
	(calibration_target instrument47 GroundStation5)
	(calibration_target instrument47 GroundStation2)
	(supports instrument48 image0)
	(calibration_target instrument48 GroundStation5)
	(calibration_target instrument48 GroundStation9)
	(calibration_target instrument48 GroundStation8)
	(calibration_target instrument48 GroundStation10)
	(supports instrument49 thermograph1)
	(supports instrument49 infrared3)
	(supports instrument49 spectrograph2)
	(calibration_target instrument49 GroundStation9)
	(supports instrument50 image0)
	(supports instrument50 spectrograph2)
	(supports instrument50 infrared3)
	(calibration_target instrument50 GroundStation9)
	(supports instrument51 spectrograph2)
	(supports instrument51 infrared3)
	(calibration_target instrument51 GroundStation9)
	(calibration_target instrument51 GroundStation5)
	(calibration_target instrument51 Star3)
	(supports instrument52 infrared3)
	(calibration_target instrument52 GroundStation0)
	(supports instrument53 thermograph1)
	(calibration_target instrument53 GroundStation5)
	(calibration_target instrument53 GroundStation8)
	(calibration_target instrument53 GroundStation11)
	(calibration_target instrument53 GroundStation0)
	(supports instrument54 infrared4)
	(calibration_target instrument54 Star7)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation0)
	(supports instrument55 infrared3)
	(supports instrument55 thermograph1)
	(calibration_target instrument55 GroundStation2)
	(calibration_target instrument55 GroundStation8)
	(calibration_target instrument55 GroundStation6)
	(supports instrument56 thermograph1)
	(calibration_target instrument56 GroundStation10)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation6)
)
(:goal (and
	(pointing satellite0 Phenomenon12)
	(pointing satellite2 Star4)
	(pointing satellite3 GroundStation10)
	(pointing satellite5 GroundStation10)
	(pointing satellite6 GroundStation2)
	(pointing satellite7 GroundStation2)
	(pointing satellite9 Star3)
	(have_image Phenomenon12 image0)
	(have_image Phenomenon13 spectrograph2)
))

)
