(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite7 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	satellite9 - satellite
	instrument54 - instrument
	instrument55 - instrument
	thermograph4 - mode
	thermograph2 - mode
	image0 - mode
	infrared3 - mode
	thermograph1 - mode
	GroundStation17 - direction
	Star15 - direction
	Star20 - direction
	Star5 - direction
	Star0 - direction
	Star8 - direction
	Star13 - direction
	GroundStation6 - direction
	Star19 - direction
	Star9 - direction
	Star14 - direction
	GroundStation3 - direction
	GroundStation7 - direction
	GroundStation11 - direction
	Star10 - direction
	GroundStation1 - direction
	GroundStation18 - direction
	Star12 - direction
	GroundStation4 - direction
	Star2 - direction
	Star21 - direction
	GroundStation16 - direction
	Star22 - direction
	Phenomenon23 - direction
)
(:init
	(supports instrument0 thermograph4)
	(calibration_target instrument0 Star15)
	(supports instrument1 thermograph4)
	(supports instrument1 thermograph2)
	(calibration_target instrument1 GroundStation16)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 Star2)
	(supports instrument2 image0)
	(calibration_target instrument2 GroundStation16)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 Star12)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star19)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star12)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 Star20)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 GroundStation17)
	(calibration_target instrument5 GroundStation18)
	(supports instrument6 thermograph2)
	(supports instrument6 infrared3)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star14)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 Star12)
	(supports instrument7 image0)
	(supports instrument7 thermograph1)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star8)
	(supports instrument8 image0)
	(calibration_target instrument8 Star19)
	(calibration_target instrument8 GroundStation7)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star15)
	(supports instrument9 image0)
	(supports instrument9 thermograph2)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 GroundStation16)
	(supports instrument10 thermograph2)
	(supports instrument10 thermograph4)
	(supports instrument10 thermograph1)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 Star13)
	(calibration_target instrument10 Star15)
	(calibration_target instrument10 Star0)
	(supports instrument11 image0)
	(calibration_target instrument11 Star13)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 Star21)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 Star20)
	(supports instrument12 thermograph2)
	(supports instrument12 image0)
	(supports instrument12 infrared3)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star12)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 GroundStation16)
	(calibration_target instrument12 GroundStation17)
	(calibration_target instrument12 Star20)
	(supports instrument13 thermograph1)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 GroundStation17)
	(supports instrument14 thermograph1)
	(supports instrument14 image0)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star14)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 GroundStation3)
	(calibration_target instrument14 GroundStation11)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 Star8)
	(supports instrument15 infrared3)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 GroundStation6)
	(calibration_target instrument15 Star10)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 GroundStation3)
	(calibration_target instrument16 Star9)
	(calibration_target instrument16 Star10)
	(calibration_target instrument16 GroundStation18)
	(calibration_target instrument16 Star15)
	(calibration_target instrument16 GroundStation16)
	(calibration_target instrument16 Star5)
	(supports instrument17 image0)
	(calibration_target instrument17 GroundStation1)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star9)
	(supports instrument18 thermograph4)
	(supports instrument18 infrared3)
	(calibration_target instrument18 Star14)
	(calibration_target instrument18 Star12)
	(supports instrument19 infrared3)
	(calibration_target instrument19 Star2)
	(supports instrument20 infrared3)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 Star8)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 GroundStation7)
	(supports instrument21 image0)
	(calibration_target instrument21 Star20)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 GroundStation17)
	(supports instrument22 infrared3)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 Star9)
	(supports instrument23 thermograph1)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 GroundStation18)
	(calibration_target instrument23 Star5)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star15)
	(supports instrument24 infrared3)
	(calibration_target instrument24 GroundStation1)
	(calibration_target instrument24 Star9)
	(calibration_target instrument24 GroundStation11)
	(calibration_target instrument24 Star15)
	(calibration_target instrument24 Star14)
	(calibration_target instrument24 GroundStation18)
	(calibration_target instrument24 Star10)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 GroundStation4)
	(calibration_target instrument25 Star20)
	(calibration_target instrument25 Star8)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 Star10)
	(supports instrument26 infrared3)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 GroundStation17)
	(calibration_target instrument26 Star5)
	(calibration_target instrument26 GroundStation16)
	(calibration_target instrument26 GroundStation11)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation16)
	(supports instrument27 infrared3)
	(supports instrument27 thermograph2)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 GroundStation1)
	(supports instrument28 thermograph1)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation3)
	(calibration_target instrument28 Star13)
	(calibration_target instrument28 Star21)
	(supports instrument29 image0)
	(supports instrument29 infrared3)
	(calibration_target instrument29 Star12)
	(calibration_target instrument29 Star13)
	(calibration_target instrument29 Star8)
	(calibration_target instrument29 Star21)
	(supports instrument30 thermograph4)
	(supports instrument30 image0)
	(supports instrument30 thermograph1)
	(calibration_target instrument30 Star13)
	(calibration_target instrument30 Star5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument31 image0)
	(supports instrument31 thermograph2)
	(supports instrument31 infrared3)
	(calibration_target instrument31 GroundStation16)
	(calibration_target instrument31 Star21)
	(calibration_target instrument31 Star8)
	(calibration_target instrument31 GroundStation6)
	(calibration_target instrument31 Star14)
	(calibration_target instrument31 GroundStation3)
	(supports instrument32 thermograph1)
	(calibration_target instrument32 GroundStation18)
	(calibration_target instrument32 Star14)
	(calibration_target instrument32 Star0)
	(supports instrument33 thermograph2)
	(supports instrument33 image0)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 image0)
	(calibration_target instrument34 GroundStation16)
	(calibration_target instrument34 GroundStation4)
	(calibration_target instrument34 GroundStation11)
	(calibration_target instrument34 Star10)
	(supports instrument35 infrared3)
	(supports instrument35 thermograph1)
	(supports instrument35 image0)
	(calibration_target instrument35 Star20)
	(calibration_target instrument35 Star12)
	(calibration_target instrument35 Star8)
	(supports instrument36 thermograph1)
	(supports instrument36 thermograph2)
	(supports instrument36 image0)
	(calibration_target instrument36 GroundStation18)
	(calibration_target instrument36 Star21)
	(calibration_target instrument36 Star12)
	(calibration_target instrument36 Star13)
	(supports instrument37 infrared3)
	(calibration_target instrument37 Star20)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 GroundStation17)
	(calibration_target instrument37 GroundStation6)
	(calibration_target instrument37 GroundStation11)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation7)
	(supports instrument38 infrared3)
	(supports instrument38 image0)
	(calibration_target instrument38 GroundStation3)
	(calibration_target instrument38 Star9)
	(supports instrument39 infrared3)
	(supports instrument39 thermograph1)
	(supports instrument39 thermograph2)
	(calibration_target instrument39 Star5)
	(calibration_target instrument39 Star19)
	(calibration_target instrument39 Star2)
	(calibration_target instrument39 GroundStation11)
	(calibration_target instrument39 GroundStation18)
	(supports instrument40 thermograph1)
	(supports instrument40 infrared3)
	(supports instrument40 thermograph2)
	(calibration_target instrument40 GroundStation11)
	(calibration_target instrument40 Star19)
	(supports instrument41 infrared3)
	(supports instrument41 image0)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 Star12)
	(calibration_target instrument41 GroundStation6)
	(calibration_target instrument41 Star9)
	(calibration_target instrument41 GroundStation16)
	(calibration_target instrument41 Star15)
	(calibration_target instrument41 Star8)
	(calibration_target instrument41 GroundStation11)
	(supports instrument42 thermograph1)
	(calibration_target instrument42 Star10)
	(calibration_target instrument42 GroundStation7)
	(calibration_target instrument42 Star19)
	(calibration_target instrument42 GroundStation16)
	(calibration_target instrument42 GroundStation17)
	(supports instrument43 thermograph2)
	(calibration_target instrument43 GroundStation4)
	(calibration_target instrument43 Star8)
	(calibration_target instrument43 Star0)
	(calibration_target instrument43 GroundStation17)
	(calibration_target instrument43 GroundStation16)
	(calibration_target instrument43 Star20)
	(supports instrument44 image0)
	(calibration_target instrument44 Star15)
	(calibration_target instrument44 Star19)
	(calibration_target instrument44 Star13)
	(supports instrument45 image0)
	(supports instrument45 thermograph4)
	(calibration_target instrument45 Star5)
	(calibration_target instrument45 GroundStation4)
	(supports instrument46 thermograph2)
	(calibration_target instrument46 Star20)
	(calibration_target instrument46 Star0)
	(calibration_target instrument46 Star2)
	(calibration_target instrument46 GroundStation6)
	(supports instrument47 infrared3)
	(supports instrument47 thermograph2)
	(calibration_target instrument47 Star9)
	(calibration_target instrument47 Star12)
	(calibration_target instrument47 GroundStation18)
	(calibration_target instrument47 Star0)
	(calibration_target instrument47 GroundStation16)
	(calibration_target instrument47 Star5)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star15)
	(supports instrument48 thermograph4)
	(supports instrument48 infrared3)
	(supports instrument48 thermograph1)
	(calibration_target instrument48 GroundStation3)
	(calibration_target instrument48 Star8)
	(supports instrument49 infrared3)
	(supports instrument49 thermograph1)
	(calibration_target instrument49 GroundStation3)
	(calibration_target instrument49 GroundStation16)
	(calibration_target instrument49 GroundStation6)
	(calibration_target instrument49 Star13)
	(calibration_target instrument49 GroundStation4)
	(supports instrument50 image0)
	(calibration_target instrument50 GroundStation11)
	(supports instrument51 infrared3)
	(calibration_target instrument51 GroundStation3)
	(calibration_target instrument51 Star14)
	(calibration_target instrument51 Star9)
	(calibration_target instrument51 Star21)
	(calibration_target instrument51 Star19)
	(calibration_target instrument51 GroundStation6)
	(supports instrument52 image0)
	(supports instrument52 infrared3)
	(calibration_target instrument52 GroundStation7)
	(supports instrument53 thermograph1)
	(calibration_target instrument53 GroundStation11)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation3)
	(supports instrument54 infrared3)
	(supports instrument54 thermograph2)
	(supports instrument54 image0)
	(calibration_target instrument54 Star12)
	(calibration_target instrument54 GroundStation18)
	(calibration_target instrument54 GroundStation1)
	(calibration_target instrument54 GroundStation4)
	(calibration_target instrument54 Star10)
	(supports instrument55 thermograph1)
	(supports instrument55 infrared3)
	(supports instrument55 image0)
	(calibration_target instrument55 GroundStation16)
	(calibration_target instrument55 Star21)
	(calibration_target instrument55 Star2)
	(calibration_target instrument55 GroundStation4)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star9)
)
(:goal (and
	(pointing satellite1 Star14)
	(pointing satellite5 Star22)
	(pointing satellite8 Star21)
	(pointing satellite9 Star0)
	(have_image Star22 thermograph1)
))

)
