(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite2 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite3 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite4 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite5 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite6 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite7 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	satellite9 - satellite
	instrument57 - instrument
	thermograph4 - mode
	infrared1 - mode
	infrared2 - mode
	thermograph3 - mode
	spectrograph0 - mode
	Star8 - direction
	Star3 - direction
	Star4 - direction
	GroundStation1 - direction
	Star5 - direction
	Star0 - direction
	GroundStation11 - direction
	Star12 - direction
	GroundStation7 - direction
	GroundStation10 - direction
	Star6 - direction
	GroundStation9 - direction
	Star2 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 thermograph3)
	(supports instrument0 thermograph4)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 GroundStation9)
	(supports instrument1 infrared2)
	(supports instrument1 thermograph3)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 GroundStation10)
	(calibration_target instrument1 Star6)
	(supports instrument2 spectrograph0)
	(supports instrument2 thermograph3)
	(calibration_target instrument2 Star6)
	(supports instrument3 infrared2)
	(supports instrument3 spectrograph0)
	(supports instrument3 infrared1)
	(calibration_target instrument3 GroundStation9)
	(supports instrument4 thermograph3)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star12)
	(calibration_target instrument4 Star2)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star5)
	(supports instrument5 thermograph4)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 GroundStation9)
	(supports instrument6 infrared1)
	(supports instrument6 thermograph3)
	(calibration_target instrument6 Star0)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star5)
	(calibration_target instrument7 GroundStation7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument8 thermograph4)
	(supports instrument8 infrared1)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 Star8)
	(supports instrument9 infrared1)
	(calibration_target instrument9 GroundStation11)
	(calibration_target instrument9 Star4)
	(calibration_target instrument9 Star2)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star8)
	(calibration_target instrument10 GroundStation11)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 Star4)
	(supports instrument12 thermograph3)
	(supports instrument12 infrared2)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 Star0)
	(supports instrument13 infrared1)
	(supports instrument13 thermograph3)
	(supports instrument13 infrared2)
	(calibration_target instrument13 Star12)
	(calibration_target instrument13 GroundStation1)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 GroundStation10)
	(supports instrument15 infrared1)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star3)
	(supports instrument16 thermograph3)
	(supports instrument16 thermograph4)
	(supports instrument16 infrared2)
	(calibration_target instrument16 GroundStation7)
	(calibration_target instrument16 Star2)
	(calibration_target instrument16 Star8)
	(calibration_target instrument16 Star0)
	(supports instrument17 thermograph4)
	(supports instrument17 infrared1)
	(supports instrument17 infrared2)
	(calibration_target instrument17 Star6)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument18 infrared2)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star12)
	(calibration_target instrument18 GroundStation1)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star5)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 GroundStation10)
	(supports instrument20 infrared2)
	(supports instrument20 spectrograph0)
	(supports instrument20 infrared1)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 GroundStation10)
	(supports instrument21 infrared2)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 Star2)
	(calibration_target instrument21 Star0)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation7)
	(supports instrument22 spectrograph0)
	(calibration_target instrument22 Star2)
	(supports instrument23 infrared1)
	(supports instrument23 thermograph4)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 GroundStation9)
	(calibration_target instrument23 Star4)
	(calibration_target instrument23 GroundStation10)
	(supports instrument24 infrared2)
	(supports instrument24 infrared1)
	(supports instrument24 spectrograph0)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 GroundStation11)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 thermograph3)
	(calibration_target instrument25 GroundStation1)
	(supports instrument26 thermograph3)
	(supports instrument26 thermograph4)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 Star4)
	(calibration_target instrument26 GroundStation10)
	(supports instrument27 thermograph3)
	(supports instrument27 spectrograph0)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 GroundStation1)
	(calibration_target instrument27 GroundStation10)
	(calibration_target instrument27 Star12)
	(calibration_target instrument27 GroundStation7)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument28 thermograph3)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 Star4)
	(calibration_target instrument28 Star8)
	(supports instrument29 thermograph4)
	(supports instrument29 infrared1)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 Star8)
	(supports instrument30 thermograph3)
	(supports instrument30 thermograph4)
	(supports instrument30 infrared1)
	(calibration_target instrument30 GroundStation10)
	(calibration_target instrument30 Star12)
	(calibration_target instrument30 Star3)
	(calibration_target instrument30 Star4)
	(supports instrument31 thermograph3)
	(supports instrument31 infrared1)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 GroundStation11)
	(supports instrument32 thermograph4)
	(calibration_target instrument32 Star0)
	(calibration_target instrument32 Star3)
	(calibration_target instrument32 GroundStation11)
	(calibration_target instrument32 GroundStation10)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star8)
	(supports instrument33 infrared1)
	(supports instrument33 thermograph3)
	(calibration_target instrument33 Star8)
	(calibration_target instrument33 Star4)
	(calibration_target instrument33 GroundStation11)
	(calibration_target instrument33 GroundStation7)
	(supports instrument34 thermograph3)
	(supports instrument34 thermograph4)
	(supports instrument34 infrared1)
	(calibration_target instrument34 GroundStation1)
	(calibration_target instrument34 GroundStation7)
	(supports instrument35 infrared1)
	(supports instrument35 spectrograph0)
	(calibration_target instrument35 Star12)
	(supports instrument36 infrared1)
	(supports instrument36 thermograph4)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 spectrograph0)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star12)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 GroundStation9)
	(supports instrument38 thermograph3)
	(supports instrument38 spectrograph0)
	(calibration_target instrument38 Star5)
	(calibration_target instrument38 Star8)
	(calibration_target instrument38 GroundStation7)
	(calibration_target instrument38 GroundStation11)
	(supports instrument39 thermograph4)
	(supports instrument39 infrared2)
	(calibration_target instrument39 Star5)
	(supports instrument40 thermograph3)
	(supports instrument40 thermograph4)
	(calibration_target instrument40 Star3)
	(calibration_target instrument40 GroundStation11)
	(calibration_target instrument40 Star6)
	(supports instrument41 infrared2)
	(calibration_target instrument41 GroundStation11)
	(calibration_target instrument41 Star12)
	(supports instrument42 thermograph4)
	(supports instrument42 infrared1)
	(calibration_target instrument42 GroundStation10)
	(calibration_target instrument42 GroundStation11)
	(calibration_target instrument42 Star5)
	(calibration_target instrument42 Star2)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation10)
	(supports instrument43 infrared2)
	(calibration_target instrument43 GroundStation10)
	(calibration_target instrument43 Star5)
	(supports instrument44 infrared1)
	(calibration_target instrument44 GroundStation7)
	(supports instrument45 infrared1)
	(supports instrument45 thermograph3)
	(calibration_target instrument45 GroundStation1)
	(calibration_target instrument45 Star6)
	(calibration_target instrument45 Star0)
	(supports instrument46 infrared2)
	(supports instrument46 thermograph3)
	(calibration_target instrument46 Star2)
	(calibration_target instrument46 Star0)
	(calibration_target instrument46 GroundStation11)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 thermograph4)
	(supports instrument47 spectrograph0)
	(calibration_target instrument47 GroundStation7)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument48 infrared2)
	(supports instrument48 thermograph3)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 Star12)
	(calibration_target instrument48 Star3)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 GroundStation7)
	(calibration_target instrument49 Star5)
	(calibration_target instrument49 Star4)
	(calibration_target instrument49 GroundStation1)
	(supports instrument50 infrared1)
	(supports instrument50 spectrograph0)
	(supports instrument50 thermograph3)
	(calibration_target instrument50 GroundStation1)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation7)
	(supports instrument51 thermograph4)
	(supports instrument51 infrared1)
	(calibration_target instrument51 GroundStation9)
	(calibration_target instrument51 GroundStation1)
	(calibration_target instrument51 GroundStation10)
	(calibration_target instrument51 Star0)
	(supports instrument52 spectrograph0)
	(supports instrument52 infrared1)
	(calibration_target instrument52 Star5)
	(calibration_target instrument52 GroundStation7)
	(supports instrument53 spectrograph0)
	(calibration_target instrument53 Star2)
	(supports instrument54 infrared1)
	(supports instrument54 spectrograph0)
	(supports instrument54 thermograph3)
	(calibration_target instrument54 Star0)
	(calibration_target instrument54 Star5)
	(supports instrument55 spectrograph0)
	(supports instrument55 thermograph4)
	(supports instrument55 infrared1)
	(calibration_target instrument55 GroundStation11)
	(supports instrument56 infrared2)
	(supports instrument56 thermograph3)
	(supports instrument56 infrared1)
	(calibration_target instrument56 Star2)
	(calibration_target instrument56 GroundStation7)
	(calibration_target instrument56 GroundStation10)
	(calibration_target instrument56 Star12)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon14)
	(supports instrument57 spectrograph0)
	(supports instrument57 thermograph3)
	(calibration_target instrument57 Star2)
	(calibration_target instrument57 GroundStation9)
	(calibration_target instrument57 Star6)
	(calibration_target instrument57 GroundStation10)
	(on_board instrument57 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
)
(:goal (and
	(pointing satellite0 GroundStation9)
	(pointing satellite1 Phenomenon13)
	(pointing satellite3 Star6)
	(pointing satellite4 GroundStation9)
	(have_image Phenomenon13 thermograph4)
	(have_image Phenomenon14 thermograph4)
))

)
