(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite2 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite4 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite7 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite8 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite9 - satellite
	instrument44 - instrument
	image3 - mode
	thermograph1 - mode
	thermograph2 - mode
	infrared4 - mode
	infrared0 - mode
	GroundStation8 - direction
	Star10 - direction
	Star12 - direction
	Star5 - direction
	Star7 - direction
	GroundStation11 - direction
	Star1 - direction
	GroundStation2 - direction
	Star3 - direction
	GroundStation4 - direction
	Star6 - direction
	GroundStation0 - direction
	Star9 - direction
	Planet13 - direction
	Phenomenon14 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 Star7)
	(supports instrument1 infrared0)
	(supports instrument1 image3)
	(calibration_target instrument1 Star9)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star7)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star7)
	(calibration_target instrument2 GroundStation0)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 Star5)
	(supports instrument3 thermograph1)
	(supports instrument3 infrared4)
	(supports instrument3 infrared0)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star7)
	(supports instrument4 image3)
	(calibration_target instrument4 GroundStation8)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 infrared4)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star12)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument7 image3)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation4)
	(supports instrument8 infrared0)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star12)
	(supports instrument9 infrared0)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 Star5)
	(supports instrument10 image3)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation0)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 Star12)
	(supports instrument12 infrared4)
	(supports instrument12 image3)
	(supports instrument12 infrared0)
	(calibration_target instrument12 Star1)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 GroundStation11)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 image3)
	(supports instrument14 infrared4)
	(supports instrument14 infrared0)
	(calibration_target instrument14 Star6)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation11)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation11)
	(supports instrument15 infrared0)
	(supports instrument15 image3)
	(calibration_target instrument15 Star9)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 Star6)
	(supports instrument16 infrared0)
	(calibration_target instrument16 Star10)
	(supports instrument17 image3)
	(supports instrument17 thermograph1)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 GroundStation11)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 Star9)
	(supports instrument18 image3)
	(supports instrument18 infrared0)
	(calibration_target instrument18 Star12)
	(supports instrument19 infrared4)
	(supports instrument19 thermograph2)
	(supports instrument19 image3)
	(calibration_target instrument19 Star5)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 Star10)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star9)
	(supports instrument20 image3)
	(calibration_target instrument20 Star6)
	(calibration_target instrument20 Star12)
	(supports instrument21 infrared0)
	(calibration_target instrument21 Star3)
	(calibration_target instrument21 Star7)
	(calibration_target instrument21 GroundStation4)
	(calibration_target instrument21 Star1)
	(supports instrument22 infrared0)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 Star6)
	(calibration_target instrument22 GroundStation8)
	(supports instrument23 infrared0)
	(calibration_target instrument23 Star5)
	(supports instrument24 thermograph1)
	(supports instrument24 infrared0)
	(calibration_target instrument24 GroundStation0)
	(calibration_target instrument24 Star10)
	(calibration_target instrument24 Star12)
	(calibration_target instrument24 Star5)
	(supports instrument25 infrared0)
	(supports instrument25 thermograph2)
	(supports instrument25 image3)
	(calibration_target instrument25 Star1)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star12)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 Star1)
	(supports instrument27 infrared0)
	(supports instrument27 thermograph1)
	(supports instrument27 infrared4)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 GroundStation0)
	(calibration_target instrument27 GroundStation2)
	(calibration_target instrument27 Star5)
	(supports instrument28 thermograph2)
	(calibration_target instrument28 Star1)
	(calibration_target instrument28 Star3)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star7)
	(supports instrument29 image3)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 Star5)
	(calibration_target instrument29 GroundStation11)
	(supports instrument30 infrared0)
	(supports instrument30 infrared4)
	(supports instrument30 thermograph2)
	(calibration_target instrument30 GroundStation8)
	(calibration_target instrument30 GroundStation11)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star10)
	(supports instrument31 thermograph1)
	(supports instrument31 image3)
	(calibration_target instrument31 Star7)
	(calibration_target instrument31 GroundStation2)
	(supports instrument32 infrared4)
	(calibration_target instrument32 Star12)
	(calibration_target instrument32 GroundStation0)
	(calibration_target instrument32 Star5)
	(calibration_target instrument32 GroundStation8)
	(supports instrument33 thermograph2)
	(supports instrument33 thermograph1)
	(calibration_target instrument33 GroundStation8)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument34 infrared4)
	(supports instrument34 infrared0)
	(calibration_target instrument34 GroundStation8)
	(calibration_target instrument34 GroundStation2)
	(calibration_target instrument34 Star5)
	(supports instrument35 thermograph1)
	(supports instrument35 image3)
	(calibration_target instrument35 Star3)
	(supports instrument36 thermograph2)
	(supports instrument36 image3)
	(supports instrument36 infrared0)
	(calibration_target instrument36 Star12)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 Star10)
	(supports instrument37 infrared0)
	(calibration_target instrument37 GroundStation2)
	(supports instrument38 infrared0)
	(supports instrument38 thermograph1)
	(calibration_target instrument38 Star5)
	(calibration_target instrument38 Star6)
	(supports instrument39 infrared4)
	(supports instrument39 infrared0)
	(supports instrument39 thermograph1)
	(calibration_target instrument39 Star7)
	(supports instrument40 thermograph1)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 GroundStation0)
	(calibration_target instrument40 GroundStation11)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star10)
	(supports instrument41 thermograph2)
	(supports instrument41 infrared4)
	(calibration_target instrument41 Star1)
	(supports instrument42 thermograph1)
	(supports instrument42 infrared4)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 GroundStation2)
	(calibration_target instrument42 GroundStation0)
	(supports instrument43 thermograph2)
	(calibration_target instrument43 Star3)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet13)
	(supports instrument44 infrared0)
	(supports instrument44 infrared4)
	(calibration_target instrument44 Star9)
	(calibration_target instrument44 GroundStation0)
	(calibration_target instrument44 Star6)
	(calibration_target instrument44 GroundStation4)
	(on_board instrument44 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation8)
)
(:goal (and
	(pointing satellite1 GroundStation0)
	(pointing satellite2 GroundStation11)
	(pointing satellite7 Star10)
	(pointing satellite8 Star12)
	(pointing satellite9 Star7)
	(have_image Planet13 infrared4)
	(have_image Phenomenon14 infrared4)
))

)
