(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	instrument21 - instrument
	satellite5 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite6 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite7 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite8 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite9 - satellite
	instrument53 - instrument
	instrument54 - instrument
	spectrograph4 - mode
	infrared0 - mode
	image3 - mode
	spectrograph2 - mode
	spectrograph1 - mode
	GroundStation6 - direction
	GroundStation12 - direction
	GroundStation11 - direction
	Star8 - direction
	GroundStation9 - direction
	Star7 - direction
	GroundStation4 - direction
	Star5 - direction
	GroundStation10 - direction
	Star3 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star0 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
)
(:init
	(supports instrument0 spectrograph4)
	(supports instrument0 infrared0)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 Star8)
	(supports instrument1 spectrograph4)
	(supports instrument1 image3)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation11)
	(supports instrument2 spectrograph2)
	(supports instrument2 image3)
	(supports instrument2 spectrograph4)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation11)
	(supports instrument3 spectrograph2)
	(supports instrument3 spectrograph4)
	(supports instrument3 infrared0)
	(calibration_target instrument3 GroundStation12)
	(supports instrument4 spectrograph4)
	(supports instrument4 infrared0)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation12)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star3)
	(supports instrument6 infrared0)
	(supports instrument6 image3)
	(calibration_target instrument6 GroundStation9)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 GroundStation12)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon14)
	(supports instrument7 image3)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 Star3)
	(supports instrument8 spectrograph2)
	(supports instrument8 spectrograph1)
	(supports instrument8 image3)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 GroundStation2)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation12)
	(supports instrument9 spectrograph2)
	(supports instrument9 spectrograph1)
	(supports instrument9 infrared0)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star8)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 GroundStation4)
	(supports instrument11 spectrograph1)
	(supports instrument11 image3)
	(supports instrument11 infrared0)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation12)
	(calibration_target instrument11 Star5)
	(supports instrument12 spectrograph1)
	(supports instrument12 infrared0)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 Star3)
	(supports instrument13 image3)
	(supports instrument13 spectrograph1)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 infrared0)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 GroundStation9)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 GroundStation10)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon13)
	(supports instrument15 spectrograph1)
	(supports instrument15 spectrograph2)
	(supports instrument15 infrared0)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 GroundStation9)
	(calibration_target instrument15 GroundStation6)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 GroundStation10)
	(supports instrument17 image3)
	(supports instrument17 spectrograph2)
	(supports instrument17 infrared0)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 GroundStation9)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 spectrograph2)
	(supports instrument18 infrared0)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation9)
	(supports instrument19 infrared0)
	(supports instrument19 spectrograph2)
	(supports instrument19 spectrograph4)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 GroundStation10)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star8)
	(supports instrument20 image3)
	(supports instrument20 spectrograph2)
	(supports instrument20 infrared0)
	(calibration_target instrument20 GroundStation10)
	(supports instrument21 spectrograph2)
	(supports instrument21 infrared0)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 GroundStation6)
	(calibration_target instrument21 Star7)
	(calibration_target instrument21 GroundStation9)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon14)
	(supports instrument22 infrared0)
	(supports instrument22 spectrograph1)
	(calibration_target instrument22 Star7)
	(calibration_target instrument22 GroundStation11)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 Star8)
	(supports instrument23 infrared0)
	(supports instrument23 spectrograph4)
	(calibration_target instrument23 GroundStation2)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 GroundStation11)
	(supports instrument24 spectrograph2)
	(calibration_target instrument24 Star3)
	(supports instrument25 spectrograph4)
	(supports instrument25 spectrograph2)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 GroundStation9)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 GroundStation10)
	(calibration_target instrument26 GroundStation9)
	(calibration_target instrument26 Star0)
	(supports instrument27 image3)
	(calibration_target instrument27 GroundStation10)
	(calibration_target instrument27 GroundStation9)
	(calibration_target instrument27 GroundStation2)
	(calibration_target instrument27 GroundStation11)
	(supports instrument28 spectrograph2)
	(supports instrument28 spectrograph1)
	(supports instrument28 image3)
	(calibration_target instrument28 GroundStation9)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 GroundStation4)
	(supports instrument29 infrared0)
	(supports instrument29 spectrograph4)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 infrared0)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 Star5)
	(calibration_target instrument30 GroundStation10)
	(supports instrument31 infrared0)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 Star5)
	(calibration_target instrument31 GroundStation11)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star8)
	(supports instrument32 infrared0)
	(calibration_target instrument32 GroundStation2)
	(calibration_target instrument32 GroundStation4)
	(calibration_target instrument32 Star8)
	(calibration_target instrument32 Star7)
	(supports instrument33 spectrograph1)
	(supports instrument33 spectrograph4)
	(supports instrument33 infrared0)
	(calibration_target instrument33 GroundStation12)
	(supports instrument34 spectrograph2)
	(supports instrument34 spectrograph1)
	(calibration_target instrument34 Star5)
	(calibration_target instrument34 Star7)
	(calibration_target instrument34 GroundStation12)
	(calibration_target instrument34 Star8)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 GroundStation6)
	(calibration_target instrument35 Star3)
	(supports instrument36 spectrograph2)
	(calibration_target instrument36 GroundStation10)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star7)
	(calibration_target instrument36 GroundStation9)
	(supports instrument37 spectrograph1)
	(supports instrument37 image3)
	(calibration_target instrument37 Star3)
	(calibration_target instrument37 GroundStation6)
	(supports instrument38 spectrograph2)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation6)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation12)
	(calibration_target instrument38 Star0)
	(supports instrument39 spectrograph1)
	(supports instrument39 spectrograph2)
	(supports instrument39 infrared0)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 GroundStation11)
	(calibration_target instrument39 Star0)
	(calibration_target instrument39 GroundStation1)
	(supports instrument40 spectrograph2)
	(supports instrument40 infrared0)
	(calibration_target instrument40 GroundStation6)
	(supports instrument41 image3)
	(supports instrument41 spectrograph2)
	(calibration_target instrument41 Star8)
	(calibration_target instrument41 Star0)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument42 infrared0)
	(supports instrument42 image3)
	(calibration_target instrument42 Star5)
	(calibration_target instrument42 Star8)
	(supports instrument43 image3)
	(supports instrument43 spectrograph4)
	(calibration_target instrument43 GroundStation12)
	(calibration_target instrument43 GroundStation10)
	(supports instrument44 spectrograph1)
	(supports instrument44 infrared0)
	(supports instrument44 spectrograph2)
	(calibration_target instrument44 GroundStation9)
	(calibration_target instrument44 GroundStation2)
	(supports instrument45 infrared0)
	(supports instrument45 image3)
	(calibration_target instrument45 GroundStation1)
	(calibration_target instrument45 GroundStation10)
	(calibration_target instrument45 GroundStation4)
	(calibration_target instrument45 Star5)
	(supports instrument46 spectrograph2)
	(calibration_target instrument46 GroundStation11)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation4)
	(supports instrument47 image3)
	(supports instrument47 spectrograph2)
	(calibration_target instrument47 GroundStation9)
	(calibration_target instrument47 Star8)
	(calibration_target instrument47 Star7)
	(supports instrument48 spectrograph1)
	(supports instrument48 spectrograph4)
	(supports instrument48 image3)
	(calibration_target instrument48 Star7)
	(calibration_target instrument48 GroundStation4)
	(calibration_target instrument48 GroundStation1)
	(calibration_target instrument48 GroundStation2)
	(supports instrument49 spectrograph1)
	(supports instrument49 spectrograph2)
	(calibration_target instrument49 Star0)
	(supports instrument50 spectrograph2)
	(supports instrument50 spectrograph4)
	(supports instrument50 infrared0)
	(calibration_target instrument50 Star5)
	(calibration_target instrument50 GroundStation4)
	(calibration_target instrument50 Star0)
	(supports instrument51 spectrograph4)
	(supports instrument51 image3)
	(supports instrument51 spectrograph2)
	(calibration_target instrument51 Star3)
	(calibration_target instrument51 Star0)
	(calibration_target instrument51 GroundStation10)
	(supports instrument52 image3)
	(supports instrument52 spectrograph1)
	(supports instrument52 infrared0)
	(calibration_target instrument52 GroundStation1)
	(calibration_target instrument52 GroundStation2)
	(calibration_target instrument52 Star0)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation12)
	(supports instrument53 spectrograph2)
	(calibration_target instrument53 GroundStation2)
	(supports instrument54 spectrograph1)
	(calibration_target instrument54 Star0)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star7)
)
(:goal (and
	(pointing satellite0 GroundStation4)
	(pointing satellite2 GroundStation11)
	(pointing satellite4 GroundStation10)
	(pointing satellite7 GroundStation1)
	(pointing satellite9 Star0)
	(have_image Phenomenon13 spectrograph2)
	(have_image Phenomenon14 spectrograph2)
))

)
